# Generated by Django 5.2.5 on 2025-09-16 18:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebtFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=255)),
                ('firm_name', models.CharField(max_length=255)),
                ('firm_email', models.EmailField(max_length=254)),
                ('firm_phone', models.CharField(max_length=255)),
                ('commitment_size', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rate_index', models.CharField(default='SOFR', max_length=16)),
                ('sofr_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('spread_bps', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Debt Facility',
                'verbose_name_plural': 'Debt Facilities',
                'db_table': 'debt_facility',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
