# Generated by Django 5.2.5 on 2025-09-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicer_name', models.CharField(max_length=100, unique=True)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('servicing_transfer_duration', models.IntegerField()),
                ('board_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thirtday_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sixtyday_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ninetyday_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('onetwentyday_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fc_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bk_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mod_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dil_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thirdparty_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reo_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reo_days', models.IntegerField()),
                ('liqfee_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('liqfee_flat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicer',
                'verbose_name_plural': 'Servicers',
                'db_table': 'servicers',
                'ordering': ['servicer_name'],
                'indexes': [models.Index(fields=['servicer_name'], name='servicers_service_f132f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='StateReference',
            fields=[
                ('state_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
                ('judicialvsnonjudicial', models.BooleanField(default=False, help_text='Is this a judicial foreclosure state')),
                ('fc_state_months', models.IntegerField(help_text='Average months to complete foreclosure')),
                ('eviction_duration', models.IntegerField(help_text='Average months to complete eviction')),
                ('rehab_duration', models.IntegerField(help_text='Average months to complete rehab')),
                ('reo_marketing_duration', models.IntegerField(help_text='Average months to complete reo marketing')),
                ('reo_local_market_ext_duration', models.IntegerField(help_text='Average months to complete reo local market extension')),
                ('dil_duration_avg', models.IntegerField(help_text='Average months to complete dilution')),
                ('property_tax_rate', models.DecimalField(decimal_places=4, help_text='Average property tax rate', max_digits=5)),
                ('transfer_tax_rate', models.DecimalField(decimal_places=4, help_text='Tax rate for property transfers', max_digits=5)),
                ('insurance_rate_avg', models.DecimalField(decimal_places=4, help_text='Average insurance rate', max_digits=5)),
                ('fc_legal_fees_avg', models.DecimalField(decimal_places=2, help_text='Average legal fees for foreclosure', max_digits=10)),
                ('dil_cost_avg', models.DecimalField(decimal_places=2, help_text='Average dilution cost', max_digits=10)),
                ('cfk_cost_avg', models.DecimalField(decimal_places=2, help_text='Average CFK cost', max_digits=10)),
                ('value_adjustment_annual', models.DecimalField(decimal_places=4, help_text='Average value adjustment', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'State Reference',
                'verbose_name_plural': 'State References',
                'db_table': 'state_reference',
                'ordering': ['state_name'],
                'indexes': [models.Index(fields=['state_code'], name='state_refer_state_c_df5719_idx')],
            },
        ),
    ]
