# Generated by Django 5.2.5 on 2025-09-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internalvaluation',
            old_name='internal_uw_arv_value',
            new_name='internal_arv_value',
        ),
        migrations.RenameField(
            model_name='internalvaluation',
            old_name='internal_uw_asis_value',
            new_name='internal_asis_value',
        ),
        migrations.RenameField(
            model_name='internalvaluation',
            old_name='internal_uw_value_date',
            new_name='internal_value_date',
        ),
    ]
