# Generated by Django 5.2.5 on 2025-09-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='debtfacility',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'Debt Facility', 'verbose_name_plural': 'Debt Facilities'},
        ),
    ]
