# Generated by Django 5.2.5 on 2026-01-30 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acq_module', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Link to seller (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='acq_module.seller'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='trade',
            field=models.ForeignKey(blank=True, help_text='Link to trade (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='acq_module.trade'),
        ),
        migrations.AddIndex(
            model_name='commercialunits',
            index=models.Index(fields=['units'], name='commercial__units_7ca743_idx'),
        ),
        migrations.AddField(
            model_name='comparableproperty',
            name='asset_hub',
            field=models.ForeignKey(help_text='Link to hub; multiple comparables per asset are supported.', on_delete=django.db.models.deletion.CASCADE, related_name='comparable_properties', to='core.assetidhub'),
        ),
        migrations.AddField(
            model_name='document',
            name='asset_hub',
            field=models.ForeignKey(blank=True, help_text='Stable hub ID this document belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.assetidhub'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entitymembership',
            name='member_entity',
            field=models.ForeignKey(help_text='The entity that owns a piece (e.g., John Smith)', on_delete=django.db.models.deletion.PROTECT, related_name='parent_memberships', to='core.entity'),
        ),
        migrations.AddField(
            model_name='entitymembership',
            name='parent_entity',
            field=models.ForeignKey(help_text='The entity being owned (e.g., GPM, LLC)', on_delete=django.db.models.deletion.CASCADE, related_name='child_members', to='core.entity'),
        ),
        migrations.AddIndex(
            model_name='fcstatus',
            index=models.Index(fields=['status'], name='fc_status_status_b0c977_idx'),
        ),
        migrations.AddIndex(
            model_name='fcstatus',
            index=models.Index(fields=['order'], name='fc_status_order_cc4970_idx'),
        ),
        migrations.AddField(
            model_name='fctimelines',
            name='fc_status',
            field=models.ForeignKey(help_text='Foreclosure status category this timeline represents', on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='core.fcstatus'),
        ),
        migrations.AddField(
            model_name='fundlegalentity',
            name='fund',
            field=models.ForeignKey(help_text='Entity that this fund legal entity belongs to (no type restriction)', on_delete=django.db.models.deletion.CASCADE, related_name='legal_entities', to='core.entity'),
        ),
        migrations.AddField(
            model_name='fundmembership',
            name='entity',
            field=models.ForeignKey(help_text='Entity that is a member (GP or LP)', on_delete=django.db.models.deletion.PROTECT, related_name='fund_memberships', to='core.entity'),
        ),
        migrations.AddField(
            model_name='fundmembership',
            name='fund',
            field=models.ForeignKey(help_text='Entity representing the fund this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.entity'),
        ),
        migrations.AddField(
            model_name='fundmembership',
            name='investing_through',
            field=models.ForeignKey(blank=True, help_text="Optional: specific fund legal entity they're investing through (e.g., domestic vs offshore feeder)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.fundlegalentity'),
        ),
        migrations.AddField(
            model_name='generalledgerentries',
            name='asset_hub',
            field=models.ForeignKey(blank=True, help_text='Link to AssetIdHub for robust loan/asset tracking across modules', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_entries', to='core.assetidhub'),
        ),
        migrations.AddField(
            model_name='generalledgerentries',
            name='asset_link',
            field=models.ForeignKey(blank=True, help_text='Link to the canonical Asset/Loan ID Hub for robust tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_entries_link', to='core.assetidhub'),
        ),
        migrations.AddField(
            model_name='generalledgerentries',
            name='bucket',
            field=models.ForeignKey(blank=True, help_text='Bucket for high-level aggregation and reporting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='core.generalledgerbucket'),
        ),
        migrations.AddField(
            model_name='generalledgerentries',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this GL entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_entries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalledgerentries',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this GL entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_entries_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalledgerentries',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for flexible categorization', related_name='entries', to='core.generalledgertag'),
        ),
        migrations.AddField(
            model_name='historicalpropertycashflow',
            name='asset_hub',
            field=models.ForeignKey(help_text='Asset this historical cash flow data belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='historical_cashflows', to='core.assetidhub'),
        ),
        migrations.AddIndex(
            model_name='hoaassumption',
            index=models.Index(fields=['property_type'], name='hoa_assumpt_propert_86cbe9_idx'),
        ),
        migrations.AddIndex(
            model_name='hudzipcbsacrosswalk',
            index=models.Index(fields=['zip_code'], name='hud_zip_cbs_zip_cod_2c3bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='hudzipcbsacrosswalk',
            index=models.Index(fields=['cbsa_code'], name='hud_zip_cbs_cbsa_co_ac902a_idx'),
        ),
        migrations.AddIndex(
            model_name='hudzipcbsacrosswalk',
            index=models.Index(fields=['state_code'], name='hud_zip_cbs_state_c_f18227_idx'),
        ),
        migrations.AddIndex(
            model_name='hudzipcbsacrosswalk',
            index=models.Index(fields=['zip_code', 'cbsa_code'], name='hud_zip_cbs_zip_cod_38c6b4_idx'),
        ),
        migrations.AddIndex(
            model_name='hudzipcbsacrosswalk',
            index=models.Index(fields=['zip_code', '-tot_ratio'], name='hud_zip_cbs_zip_cod_fefea5_idx'),
        ),
        migrations.AddField(
            model_name='investorcontribution',
            name='co_investor',
            field=models.ForeignKey(help_text='Co-investor who made this contribution', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.coinvestor'),
        ),
        migrations.AddField(
            model_name='investordistribution',
            name='co_investor',
            field=models.ForeignKey(help_text='Co-investor receiving this distribution', on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='core.coinvestor'),
        ),
        migrations.AddField(
            model_name='leasecomparable',
            name='comparable_property',
            field=models.OneToOneField(help_text='Link to parent comparable property.', on_delete=django.db.models.deletion.CASCADE, related_name='lease_data', to='core.comparableproperty'),
        ),
        migrations.AddField(
            model_name='leasecomparablerentroll',
            name='comparable_property',
            field=models.ForeignKey(help_text='Link to parent comparable property; multiple units per property supported.', on_delete=django.db.models.deletion.CASCADE, related_name='lease_units', to='core.comparableproperty'),
        ),
        migrations.AddField(
            model_name='leasecomparableunitmix',
            name='comparable_property',
            field=models.ForeignKey(help_text='Link to parent comparable property; multiple unit types per property supported.', on_delete=django.db.models.deletion.CASCADE, related_name='lease_unit_mix', to='core.comparableproperty'),
        ),
        migrations.AddField(
            model_name='llcashflowseries',
            name='asset_hub',
            field=models.ForeignKey(help_text='The AssetIdHub this cash flow period belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='ll_cash_flow_series', to='core.assetidhub'),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='asset_hub',
            field=models.OneToOneField(blank=True, help_text='1:1 hub link for this enrichment (mirror of seller_raw_data.asset_hub).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrichment', to='core.assetidhub'),
        ),
        migrations.AddField(
            model_name='mastercrm',
            name='firm_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='core.firmcrm'),
        ),
        migrations.AddField(
            model_name='coinvestor',
            name='crm_contact',
            field=models.ForeignKey(blank=True, help_text='Link to CRM contact for investor name and contact information', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_investor_records', to='core.mastercrm'),
        ),
        migrations.AddField(
            model_name='brokermsaassignment',
            name='broker',
            field=models.ForeignKey(help_text='Broker assigned to this MSA', on_delete=django.db.models.deletion.CASCADE, related_name='msa_assignments', to='core.mastercrm'),
        ),
        migrations.AddField(
            model_name='mastercrm',
            name='msas',
            field=models.ManyToManyField(blank=True, related_name='crm_brokers', through='core.BrokerMSAAssignment', through_fields=('broker', 'msa'), to='core.msareference'),
        ),
        migrations.AddField(
            model_name='brokermsaassignment',
            name='msa',
            field=models.ForeignKey(blank=True, help_text='MSA market assigned to this broker (optional - can be set later)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker_assignments', to='core.msareference'),
        ),
        migrations.AddField(
            model_name='notification',
            name='asset_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='core.assetidhub'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationread',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='core.notification'),
        ),
        migrations.AddField(
            model_name='notificationread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='asset_hub',
            field=models.ForeignKey(blank=True, help_text='Stable hub ID for this photo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_photos', to='core.assetidhub'),
        ),
        migrations.AddField(
            model_name='photo',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this photo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='propertytypeassumption',
            index=models.Index(fields=['property_type'], name='property_ty_propert_da546d_idx'),
        ),
        migrations.AddIndex(
            model_name='propertytypeassumption',
            index=models.Index(fields=['is_active'], name='property_ty_is_acti_6ab36a_idx'),
        ),
        migrations.AddField(
            model_name='rentroll',
            name='asset_hub_id',
            field=models.ForeignKey(help_text='Asset this rent roll belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rent_rolls', to='core.assetidhub'),
        ),
        migrations.AddField(
            model_name='salescomparable',
            name='comparable_property',
            field=models.OneToOneField(help_text='Link to parent comparable property.', on_delete=django.db.models.deletion.CASCADE, related_name='sales_data', to='core.comparableproperty'),
        ),
        migrations.AddIndex(
            model_name='servicer',
            index=models.Index(fields=['servicer_name'], name='servicers_service_f132f6_idx'),
        ),
        migrations.AddIndex(
            model_name='squarefootageassumption',
            index=models.Index(fields=['property_category'], name='square_foot_propert_69d47d_idx'),
        ),
        migrations.AddIndex(
            model_name='squarefootageassumption',
            index=models.Index(fields=['is_active'], name='square_foot_is_acti_6501bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='squarefootageassumption',
            unique_together={('property_category', 'description')},
        ),
        migrations.AddIndex(
            model_name='statereference',
            index=models.Index(fields=['state_code'], name='state_refer_state_c_df5719_idx'),
        ),
        migrations.AddField(
            model_name='msareference',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Primary state for this MSA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msas', to='core.statereference'),
        ),
        migrations.AddField(
            model_name='mastercrm',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='crm_contacts', to='core.statereference'),
        ),
        migrations.AddField(
            model_name='firmcrm',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='crm_firms', to='core.statereference'),
        ),
        migrations.AddField(
            model_name='fctimelines',
            name='state',
            field=models.ForeignKey(help_text='State this timeline applies to', on_delete=django.db.models.deletion.CASCADE, related_name='fc_timelines', to='core.statereference'),
        ),
        migrations.AddField(
            model_name='countyreference',
            name='state',
            field=models.ForeignKey(help_text='State this county belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='counties', to='core.statereference'),
        ),
        migrations.AddIndex(
            model_name='unitbasedassumption',
            index=models.Index(fields=['units_min', 'units_max'], name='unit_based__units_m_ceb39f_idx'),
        ),
        migrations.AddIndex(
            model_name='unitbasedassumption',
            index=models.Index(fields=['is_active'], name='unit_based__is_acti_5f199b_idx'),
        ),
        migrations.AddConstraint(
            model_name='unitbasedassumption',
            constraint=models.CheckConstraint(condition=models.Q(('units_min__gte', 1)), name='units_min_positive'),
        ),
        migrations.AddConstraint(
            model_name='unitbasedassumption',
            constraint=models.CheckConstraint(condition=models.Q(('units_max__isnull', True), ('units_max__gte', models.F('units_min')), _connector='OR'), name='units_max_gte_min'),
        ),
        migrations.AddField(
            model_name='unitmix',
            name='asset_hub_id',
            field=models.ForeignKey(help_text='Asset this unit mix belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='unit_mixes', to='core.assetidhub'),
        ),
        migrations.AddField(
            model_name='valuation',
            name='asset_hub',
            field=models.ForeignKey(blank=True, help_text='Link to hub; multiple valuations per asset are supported.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='valuations', to='core.assetidhub'),
        ),
        migrations.AddField(
            model_name='valuation',
            name='broker_contact',
            field=models.ForeignKey(blank=True, help_text='CRM contact (usually broker) associated with this valuation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuations', to='core.mastercrm'),
        ),
        migrations.AddField(
            model_name='valuation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this valuation record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_valuations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valuation',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this valuation record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_valuations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='valuation',
            field=models.ForeignKey(blank=True, help_text='Valuation this photo is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='core.valuation'),
        ),
        migrations.AddField(
            model_name='document',
            name='valuation',
            field=models.ForeignKey(blank=True, help_text='Valuation this document is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.valuation'),
        ),
        migrations.AddIndex(
            model_name='valuationgradereference',
            index=models.Index(fields=['code'], name='core_valuat_code_9d3a57_idx'),
        ),
        migrations.AddIndex(
            model_name='valuationgradereference',
            index=models.Index(fields=['sort_order'], name='core_valuat_sort_or_d78e1c_idx'),
        ),
        migrations.AddField(
            model_name='valuation',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='Reference grade applied to this valuation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_valuations', to='core.valuationgradereference'),
        ),
        migrations.AddField(
            model_name='assetdetails',
            name='fund_legal_entity',
            field=models.ForeignKey(blank=True, help_text='Fund/Entity associated with this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to='core.fundlegalentity'),
        ),
        migrations.AddField(
            model_name='assetdetails',
            name='trade',
            field=models.ForeignKey(blank=True, help_text='Trade associated with this asset detail', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_details', to='acq_module.trade'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['date'], name='core_calend_date_a92aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['created_by', 'date'], name='core_calend_created_d1363a_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['assigned_to', 'date'], name='core_calend_assigne_142f21_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['seller', 'date'], name='core_calend_seller__b409e9_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['trade', 'date'], name='core_calend_trade_i_85e89b_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['asset_hub', 'date'], name='core_calend_asset_h_848923_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['task_type', 'date'], name='core_calend_task_ty_f8a80b_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['priority', 'date'], name='core_calend_priorit_d30407_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['is_reminder', 'date'], name='core_calend_is_remi_7da7c1_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['completed', 'date'], name='core_calend_complet_b41f1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.CheckConstraint(condition=models.Q(('date__gte', '2020-01-01')), name='calendar_event_date_not_too_old'),
        ),
        migrations.AddIndex(
            model_name='comparableproperty',
            index=models.Index(fields=['asset_hub', 'as_of_date'], name='core_compar_asset_h_b4fafe_idx'),
        ),
        migrations.AddIndex(
            model_name='comparableproperty',
            index=models.Index(fields=['property_type'], name='core_compar_propert_5bf217_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entitymembership',
            unique_together={('parent_entity', 'member_entity')},
        ),
        migrations.AlterUniqueTogether(
            name='fundmembership',
            unique_together={('fund', 'entity')},
        ),
        migrations.AddIndex(
            model_name='generalledgerentries',
            index=models.Index(fields=['posting_date'], name='general_led_posting_868b58_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerentries',
            index=models.Index(fields=['entry_date'], name='general_led_entry_d_25ad1f_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerentries',
            index=models.Index(fields=['company_name', 'posting_date'], name='general_led_company_f773be_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerentries',
            index=models.Index(fields=['loan_number', 'posting_date'], name='general_led_loan_nu_665a55_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerentries',
            index=models.Index(fields=['account_number', 'posting_date'], name='general_led_account_78ef1f_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerentries',
            index=models.Index(fields=['cost_center', 'posting_date'], name='general_led_cost_ce_81fcb4_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalpropertycashflow',
            index=models.Index(fields=['asset_hub', 'year'], name='core_histor_asset_h_6cd6b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='historicalpropertycashflow',
            constraint=models.UniqueConstraint(fields=('asset_hub', 'year'), name='uq_asset_hub_year'),
        ),
        migrations.AddIndex(
            model_name='leasecomparablerentroll',
            index=models.Index(fields=['comparable_property', 'unit_number'], name='core_lease__compara_c5dc24_idx'),
        ),
        migrations.AddIndex(
            model_name='leasecomparablerentroll',
            index=models.Index(fields=['is_occupied'], name='core_lease__is_occu_3ea583_idx'),
        ),
        migrations.AddIndex(
            model_name='leasecomparableunitmix',
            index=models.Index(fields=['comparable_property', 'unit_type'], name='core_lease__compara_31c18a_idx'),
        ),
        migrations.AddIndex(
            model_name='llcashflowseries',
            index=models.Index(fields=['asset_hub', 'period_number'], name='ll_cash_flo_asset_h_9d2076_idx'),
        ),
        migrations.AddIndex(
            model_name='llcashflowseries',
            index=models.Index(fields=['period_date'], name='ll_cash_flo_period__0ff61c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='llcashflowseries',
            unique_together={('asset_hub', 'period_date')},
        ),
        migrations.AddIndex(
            model_name='lldataenrichment',
            index=models.Index(fields=['asset_hub'], name='acq_ll_data_asset_h_0d4542_idx'),
        ),
        migrations.AddIndex(
            model_name='lldataenrichment',
            index=models.Index(fields=['geocode_lat', 'geocode_lng'], name='acq_ll_data_geocode_476637_idx'),
        ),
        migrations.AddIndex(
            model_name='brokermsaassignment',
            index=models.Index(fields=['msa', 'priority'], name='broker_msa__msa_id_ef50bf_idx'),
        ),
        migrations.AddIndex(
            model_name='brokermsaassignment',
            index=models.Index(fields=['broker'], name='broker_msa__broker__078205_idx'),
        ),
        migrations.AddIndex(
            model_name='brokermsaassignment',
            index=models.Index(fields=['is_active'], name='broker_msa__is_acti_4f1d29_idx'),
        ),
        migrations.AddIndex(
            model_name='brokermsaassignment',
            index=models.Index(fields=['msa', 'is_active', 'priority'], name='broker_msa__msa_id_db09aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brokermsaassignment',
            unique_together={('broker', 'msa')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event_type', 'created_at'], name='core_notifi_event_t_c8a797_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['asset_hub', 'created_at'], name='core_notifi_asset_h_8cad96_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationread',
            index=models.Index(fields=['user', 'read_at'], name='core_notifi_user_id_f2892e_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationread',
            constraint=models.UniqueConstraint(fields=('notification', 'user'), name='uniq_notification_user'),
        ),
        migrations.AddIndex(
            model_name='msareference',
            index=models.Index(fields=['msa_code'], name='msa_referen_msa_cod_c3d38a_idx'),
        ),
        migrations.AddIndex(
            model_name='msareference',
            index=models.Index(fields=['state'], name='msa_referen_state_i_f4a701_idx'),
        ),
        migrations.AddIndex(
            model_name='msareference',
            index=models.Index(fields=['msa_name'], name='msa_referen_msa_nam_9ea608_idx'),
        ),
        migrations.AddIndex(
            model_name='mastercrm',
            index=models.Index(fields=['email'], name='core_master_email_80f2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='mastercrm',
            index=models.Index(fields=['firm_ref'], name='core_master_firm_re_199072_idx'),
        ),
        migrations.AddIndex(
            model_name='mastercrm',
            index=models.Index(fields=['tag'], name='core_master_tag_981fef_idx'),
        ),
        migrations.AddIndex(
            model_name='firmcrm',
            index=models.Index(fields=['name'], name='core_firmcr_name_ded35f_idx'),
        ),
        migrations.AddIndex(
            model_name='firmcrm',
            index=models.Index(fields=['tag'], name='core_firmcr_tag_791e31_idx'),
        ),
        migrations.AddIndex(
            model_name='fctimelines',
            index=models.Index(fields=['state', 'fc_status'], name='fc_timeline_state_i_397856_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fctimelines',
            unique_together={('state', 'fc_status')},
        ),
        migrations.AddIndex(
            model_name='countyreference',
            index=models.Index(fields=['county_fips'], name='county_refe_county__01b128_idx'),
        ),
        migrations.AddIndex(
            model_name='countyreference',
            index=models.Index(fields=['state'], name='county_refe_state_i_be0b97_idx'),
        ),
        migrations.AddIndex(
            model_name='countyreference',
            index=models.Index(fields=['county_name'], name='county_refe_county__7a3900_idx'),
        ),
        migrations.AddIndex(
            model_name='countyreference',
            index=models.Index(fields=['state', 'county_name'], name='county_refe_state_i_d9ce79_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['asset_hub'], name='acq_photo_asset_h_ef4ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['source_tag'], name='acq_photo_source__ceca6b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['asset_hub'], name='acq_broker__asset_h_7339f5_idx'),
        ),
        migrations.AddIndex(
            model_name='valuation',
            index=models.Index(fields=['asset_hub'], name='acq_valuati_asset_h_d542f4_idx'),
        ),
        migrations.AddIndex(
            model_name='valuation',
            index=models.Index(fields=['source'], name='acq_valuati_source_9b9a42_idx'),
        ),
        migrations.AddIndex(
            model_name='valuation',
            index=models.Index(fields=['value_date'], name='acq_valuati_value_d_510409_idx'),
        ),
        migrations.AddIndex(
            model_name='valuation',
            index=models.Index(fields=['broker_contact'], name='acq_valuati_broker__ffb5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='valuation',
            index=models.Index(fields=['grade'], name='acq_valuati_grade_i_557190_idx'),
        ),
        migrations.AddConstraint(
            model_name='valuation',
            constraint=models.UniqueConstraint(fields=('asset_hub', 'source', 'value_date'), name='unique_valuation_per_source_date'),
        ),
    ]
