# Generated by Django 5.2.5 on 2025-09-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetidhub',
            name='servicer_id',
            field=models.CharField(blank=True, db_index=True, help_text='External servicer ID for cross-referencing servicer loan data', max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='assetidhub',
            index=models.Index(fields=['servicer_id'], name='core_asseti_service_4a5a4b_idx'),
        ),
    ]
