# Generated by Django 5.2 on 2025-09-19 01:35

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_internal_uw_arv_value_internalvaluation_internal_arv_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internalvaluation',
            name='created_by',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                related_name='created_internal_valuations',
                help_text='User who created this valuation record.',
            ),
        ),
        migrations.AddField(
            model_name='internalvaluation',
            name='updated_by',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                related_name='updated_internal_valuations',
                help_text='User who last updated this valuation record.',
            ),
        ),
    ]
