# Generated by Django 5.2.5 on 2025-09-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicer_statereference'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Legal Entity',
                'verbose_name_plural': 'Legal Entities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='core_legalc_email_0fe955_idx'), models.Index(fields=['firm_name'], name='core_legalc_firm_na_6cd04e_idx')],
            },
        ),
    ]
