# Generated by Django 5.2 on 2025-09-19 01:44

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_iv_created_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brokervalues',
            name='created_by',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                related_name='created_broker_valuations',
                help_text='User who created this broker valuation record.',
            ),
        ),
        migrations.AddField(
            model_name='brokervalues',
            name='updated_by',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                related_name='updated_broker_valuations',
                help_text='User who last updated this broker valuation record.',
            ),
        ),
    ]
