# Generated by Django 5.2 on 2025-09-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assetidhub_servicer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mastercrm',
            old_name='name',
            new_name='contact_name',
        ),
        migrations.AlterField(
            model_name='mastercrm',
            name='tag',
            field=models.CharField(blank=True, choices=[('broker', 'Broker'), ('trading_partner', 'Trading Partner'), ('legal', 'Legal'), ('vendor', 'Vendor')], db_index=True, help_text='Simple type tag for this contact (Broker, Trading Partner, Legal, Vendor).', max_length=32, null=True),
        ),
    ]
