# Generated by Django 5.2.5 on 2025-09-30 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_name_mastercrm_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLTransactionSummary',
            fields=[
                ('asset_hub', models.OneToOneField(help_text='The AssetIdHub this transaction summary belongs to.', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='ll_transaction_summary', serialize=False, to='core.assetidhub')),
                ('purchase_price_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual purchase price paid', max_digits=15, null=True)),
                ('acq_due_diligence_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual due diligence costs', max_digits=15, null=True)),
                ('acq_legal_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual legal costs for acquisition', max_digits=15, null=True)),
                ('acq_title_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual title costs', max_digits=15, null=True)),
                ('acq_other_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual other acquisition costs', max_digits=15, null=True)),
                ('income_principal_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual principal collected', max_digits=15, null=True)),
                ('income_interest_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual interest collected', max_digits=15, null=True)),
                ('income_rent_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual rent collected', max_digits=15, null=True)),
                ('income_cam_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual CAM income', max_digits=15, null=True)),
                ('income_mod_down_payment_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual modification down payment', max_digits=15, null=True)),
                ('expense_servicing_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual servicing fees paid', max_digits=15, null=True)),
                ('expense_am_fees_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual asset management fees', max_digits=15, null=True)),
                ('expense_property_tax_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual property taxes paid', max_digits=15, null=True)),
                ('expense_property_insurance_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual property insurance paid', max_digits=15, null=True)),
                ('legal_foreclosure_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual foreclosure fees', max_digits=15, null=True)),
                ('legal_bankruptcy_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual bankruptcy legal fees', max_digits=15, null=True)),
                ('legal_dil_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual DIL fees', max_digits=15, null=True)),
                ('legal_cash_for_keys_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual cash for keys fees', max_digits=15, null=True)),
                ('legal_eviction_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual eviction fees', max_digits=15, null=True)),
                ('reo_hoa_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual HOA fees paid', max_digits=15, null=True)),
                ('reo_utilities_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual utilities paid', max_digits=15, null=True)),
                ('reo_trashout_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual trashout costs', max_digits=15, null=True)),
                ('reo_renovation_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual renovation costs', max_digits=15, null=True)),
                ('reo_property_preservation_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual property preservation costs', max_digits=15, null=True)),
                ('cre_marketing_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual marketing costs', max_digits=15, null=True)),
                ('cre_ga_pool_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual G&A pool/groundskeeping costs', max_digits=15, null=True)),
                ('cre_maintenance_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual maintenance costs', max_digits=15, null=True)),
                ('fund_taxes_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual fund-level taxes', max_digits=15, null=True)),
                ('fund_legal_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual fund-level legal costs', max_digits=15, null=True)),
                ('fund_consulting_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual fund-level consulting costs', max_digits=15, null=True)),
                ('fund_audit_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual fund-level audit costs', max_digits=15, null=True)),
                ('proceeds_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual gross liquidation proceeds', max_digits=15, null=True)),
                ('broker_closing_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual broker closing costs', max_digits=15, null=True)),
                ('other_closing_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual other closing costs', max_digits=15, null=True)),
                ('net_liquidation_proceeds_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual net liquidation proceeds', max_digits=15, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time this summary was updated from GL entries')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this summary record was created')),
            ],
            options={
                'verbose_name': 'Loan-Level Transaction Summary',
                'verbose_name_plural': 'Loan-Level Transaction Summaries',
                'db_table': 'll_transaction_summary',
                'ordering': ['asset_hub'],
            },
        ),
    ]
