# Generated by Django 5.2 on 2025-09-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_make_valuation_fields_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalvaluation',
            name='internal_arv_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalvaluation',
            name='internal_asis_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalvaluation',
            name='internal_value_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalvaluation',
            name='thirdparty_arv_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalvaluation',
            name='thirdparty_asis_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalvaluation',
            name='thirdparty_value_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
