# Generated by Django 5.2.5 on 2025-10-01 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lltransactionsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLCashFlowSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField(help_text='Period start date (calculated from purchase_date + period_number months)')),
                ('period_number', models.IntegerField(help_text='Sequential period number (0=acquisition, 1=first month, etc.)')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, help_text='Purchase price (negative cash flow in period 0)', max_digits=15)),
                ('acq_due_diligence', models.DecimalField(decimal_places=2, default=0, help_text='Due diligence costs for this period', max_digits=15)),
                ('acq_legal', models.DecimalField(decimal_places=2, default=0, help_text='Legal costs for acquisition in this period', max_digits=15)),
                ('acq_title', models.DecimalField(decimal_places=2, default=0, help_text='Title costs for this period', max_digits=15)),
                ('acq_other', models.DecimalField(decimal_places=2, default=0, help_text='Other acquisition costs for this period', max_digits=15)),
                ('income_principal', models.DecimalField(decimal_places=2, default=0, help_text='Principal collected in this period', max_digits=15)),
                ('income_interest', models.DecimalField(decimal_places=2, default=0, help_text='Interest collected in this period', max_digits=15)),
                ('income_rent', models.DecimalField(decimal_places=2, default=0, help_text='Rent collected in this period', max_digits=15)),
                ('income_cam', models.DecimalField(decimal_places=2, default=0, help_text='CAM income for this period', max_digits=15)),
                ('income_mod_down_payment', models.DecimalField(decimal_places=2, default=0, help_text='Modification down payment for this period', max_digits=15)),
                ('expense_servicing', models.DecimalField(decimal_places=2, default=0, help_text='Servicing fees paid in this period', max_digits=15)),
                ('expense_am_fees', models.DecimalField(decimal_places=2, default=0, help_text='Asset management fees for this period', max_digits=15)),
                ('expense_property_tax', models.DecimalField(decimal_places=2, default=0, help_text='Property taxes paid in this period', max_digits=15)),
                ('expense_property_insurance', models.DecimalField(decimal_places=2, default=0, help_text='Property insurance paid in this period', max_digits=15)),
                ('legal_foreclosure', models.DecimalField(decimal_places=2, default=0, help_text='Foreclosure fees for this period', max_digits=15)),
                ('legal_bankruptcy', models.DecimalField(decimal_places=2, default=0, help_text='Bankruptcy legal fees for this period', max_digits=15)),
                ('legal_dil', models.DecimalField(decimal_places=2, default=0, help_text='DIL fees for this period', max_digits=15)),
                ('legal_cash_for_keys', models.DecimalField(decimal_places=2, default=0, help_text='Cash for keys fees for this period', max_digits=15)),
                ('legal_eviction', models.DecimalField(decimal_places=2, default=0, help_text='Eviction fees for this period', max_digits=15)),
                ('reo_hoa', models.DecimalField(decimal_places=2, default=0, help_text='HOA fees paid in this period', max_digits=15)),
                ('reo_utilities', models.DecimalField(decimal_places=2, default=0, help_text='Utilities paid in this period', max_digits=15)),
                ('reo_trashout', models.DecimalField(decimal_places=2, default=0, help_text='Trashout costs for this period', max_digits=15)),
                ('reo_renovation', models.DecimalField(decimal_places=2, default=0, help_text='Renovation costs for this period', max_digits=15)),
                ('reo_property_preservation', models.DecimalField(decimal_places=2, default=0, help_text='Property preservation costs for this period', max_digits=15)),
                ('cre_marketing', models.DecimalField(decimal_places=2, default=0, help_text='Marketing costs for this period', max_digits=15)),
                ('cre_ga_pool', models.DecimalField(decimal_places=2, default=0, help_text='G&A pool/groundskeeping costs for this period', max_digits=15)),
                ('cre_maintenance', models.DecimalField(decimal_places=2, default=0, help_text='Maintenance costs for this period', max_digits=15)),
                ('fund_taxes', models.DecimalField(decimal_places=2, default=0, help_text='Fund-level taxes for this period', max_digits=15)),
                ('fund_legal', models.DecimalField(decimal_places=2, default=0, help_text='Fund-level legal costs for this period', max_digits=15)),
                ('fund_consulting', models.DecimalField(decimal_places=2, default=0, help_text='Fund-level consulting costs for this period', max_digits=15)),
                ('fund_audit', models.DecimalField(decimal_places=2, default=0, help_text='Fund-level audit costs for this period', max_digits=15)),
                ('proceeds', models.DecimalField(decimal_places=2, default=0, help_text='Gross liquidation proceeds for this period', max_digits=15)),
                ('broker_closing', models.DecimalField(decimal_places=2, default=0, help_text='Broker closing costs for this period', max_digits=15)),
                ('other_closing', models.DecimalField(decimal_places=2, default=0, help_text='Other closing costs for this period', max_digits=15)),
                ('net_liquidation_proceeds', models.DecimalField(decimal_places=2, default=0, help_text='Net liquidation proceeds for this period', max_digits=15)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all income line items for this period', max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all expense line items for this period', max_digits=15)),
                ('net_cash_flow', models.DecimalField(decimal_places=2, default=0, help_text='Net cash flow for this period (income - expenses - costs)', max_digits=15)),
                ('is_underwritten', models.BooleanField(default=False, help_text='True if this data comes from underwritten projections')),
                ('is_realized', models.BooleanField(default=False, help_text='True if this data comes from actual GL transactions')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time this period record was updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this period record was created')),
                ('asset_hub', models.ForeignKey(help_text='The AssetIdHub this cash flow period belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='ll_cash_flow_series', to='core.assetidhub')),
            ],
            options={
                'verbose_name': 'Loan-Level Cash Flow Series',
                'verbose_name_plural': 'Loan-Level Cash Flow Series',
                'db_table': 'll_cash_flow_series',
                'ordering': ['asset_hub', 'period_number'],
                'indexes': [models.Index(fields=['asset_hub', 'period_number'], name='ll_cash_flo_asset_h_9d2076_idx'), models.Index(fields=['period_date'], name='ll_cash_flo_period__0ff61c_idx')],
                'unique_together': {('asset_hub', 'period_date', 'is_underwritten', 'is_realized')},
            },
        ),
    ]
