# Generated by Django 5.2.5 on 2025-09-19 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_internalvaluation_internal_arv_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('internal', 'Internal Valuation'), ('broker', 'Broker Valuation'), ('third_party', 'Third Party Valuation'), ('seller', 'Seller Provided'), ('appraisal', 'Professional Appraisal')], help_text='Source of this valuation.', max_length=20)),
                ('asis_value', models.DecimalField(blank=True, decimal_places=2, help_text='As-is value of the property.', max_digits=15, null=True)),
                ('arv_value', models.DecimalField(blank=True, decimal_places=2, help_text='After-repair value of the property.', max_digits=15, null=True)),
                ('value_date', models.DateField(blank=True, help_text='Date of the valuation.', null=True)),
                ('rehab_est_total', models.DecimalField(blank=True, decimal_places=2, help_text='Total estimated rehabilitation costs.', max_digits=15, null=True)),
                ('roof_est', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('kitchen_est', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bath_est', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('flooring_est', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('windows_est', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('appliances_est', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('plumbing_est', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('electrical_est', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('landscaping_est', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about the valuation.', null=True)),
                ('links', models.URLField(blank=True, help_text='Links to supporting documentation or external resources.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_hub', models.ForeignKey(blank=True, help_text='Link to hub; multiple valuations per asset are supported.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='valuations', to='core.assetidhub')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this valuation record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_valuations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this valuation record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_valuations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valuation',
                'verbose_name_plural': 'Valuations',
                'db_table': 'acq_valuations',
                'ordering': ['-value_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='valuation',
            field=models.ForeignKey(blank=True, help_text='Valuation this document is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.valuation'),
        ),
        migrations.AddField(
            model_name='photo',
            name='valuation',
            field=models.ForeignKey(blank=True, help_text='Valuation this photo is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='core.valuation'),
        ),
        migrations.AddIndex(
            model_name='valuation',
            index=models.Index(fields=['asset_hub'], name='acq_valuati_asset_h_d542f4_idx'),
        ),
        migrations.AddIndex(
            model_name='valuation',
            index=models.Index(fields=['source'], name='acq_valuati_source_9b9a42_idx'),
        ),
        migrations.AddIndex(
            model_name='valuation',
            index=models.Index(fields=['value_date'], name='acq_valuati_value_d_510409_idx'),
        ),
        migrations.AddConstraint(
            model_name='valuation',
            constraint=models.UniqueConstraint(fields=('asset_hub', 'source', 'value_date'), name='unique_valuation_per_source_date'),
        ),
    ]
