# Generated by Django 5.2 on 2025-10-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_acq_due_diligence_llcashflowseries_acq_due_diligence_expenses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(help_text='Number of commercial units (use upper bound for ranges, e.g., 4 for 2-4 units)', unique=True)),
                ('fc_cost_scale', models.DecimalField(decimal_places=2, default=1.0, help_text='Foreclosure cost multiplier (e.g., 1.50 = 150% of base cost)', max_digits=5)),
                ('rehab_cost_scale', models.DecimalField(decimal_places=2, default=1.0, help_text='Rehab cost multiplier (e.g., 1.25 = 125% of base cost)', max_digits=5)),
                ('rehab_duration_scale', models.DecimalField(decimal_places=2, default=1.0, help_text='Rehab duration multiplier (e.g., 1.30 = 130% of base duration)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commercial Unit Scaling',
                'verbose_name_plural': 'Commercial Unit Scalings',
                'db_table': 'commercial_units',
                'ordering': ['units'],
                'indexes': [models.Index(fields=['units'], name='commercial__units_7ca743_idx')],
            },
        ),
    ]
