# Generated by Django 5.2.5 on 2025-09-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_valuation_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuation',
            name='source',
            field=models.CharField(choices=[('internalInitialUW', 'Internal Initial UW Valuation'), ('internal', 'Internal Valuation'), ('broker', 'Broker Valuation'), ('desktop', 'Desktop Valuation'), ('BPOI', 'BPOI'), ('BPOE', 'BPOE'), ('seller', 'Seller Provided'), ('appraisal', 'Professional Appraisal')], help_text='Source of this valuation.', max_length=20),
        ),
    ]
