# Generated by Django 5.2.5 on 2025-10-02 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_commercialunits'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSAReference',
            fields=[
                ('msa_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('msa_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FCStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pre_fc', 'Pre-Foreclosure'), ('first_legal_filed', 'First Legal Filed (NOD/Complaint)'), ('mediation', 'Mediation'), ('order_of_reference', 'Order of Reference (Judicial Only)'), ('judgement', 'Judgment (Judicial Only)'), ('pre_sale_redemption', 'Pre-Sale Redemption'), ('sale_scheduled', 'Sale Scheduled'), ('sale_completed', 'Sale Completed'), ('post_sale_redemption', 'Post-Sale Redemption')], help_text='Current foreclosure status category', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Order in which this status typically occurs (lower numbers = earlier stages)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or context about this foreclosure status', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Foreclosure Status',
                'verbose_name_plural': 'Foreclosure Statuses',
                'db_table': 'fc_status',
                'ordering': ['order', 'status'],
                'indexes': [models.Index(fields=['status'], name='fc_status_status_b0c977_idx'), models.Index(fields=['order'], name='fc_status_order_cc4970_idx')],
            },
        ),
        migrations.CreateModel(
            name='FCTimelines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.IntegerField(blank=True, help_text='Average number of days to complete this status in this state', null=True)),
                ('cost_avg', models.DecimalField(blank=True, decimal_places=2, help_text='Average cost associated with this status in this state', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this status in this state', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fc_status', models.ForeignKey(help_text='Foreclosure status category this timeline represents', on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='core.fcstatus')),
                ('state', models.ForeignKey(help_text='State this timeline applies to', on_delete=django.db.models.deletion.CASCADE, related_name='fc_timelines', to='core.statereference')),
            ],
            options={
                'verbose_name': 'Foreclosure Timeline',
                'verbose_name_plural': 'Foreclosure Timelines',
                'db_table': 'fc_timelines',
                'ordering': ['state', 'fc_status'],
                'indexes': [models.Index(fields=['state', 'fc_status'], name='fc_timeline_state_i_397856_idx')],
                'unique_together': {('state', 'fc_status')},
            },
        ),
    ]
