# Generated by Django 5.2.5 on 2025-10-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_msareference_fcstatus_fctimelines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statereference',
            name='insurance_rate_avg',
            field=models.DecimalField(decimal_places=2, help_text='Average insurance rate (as decimal: 0.01 = 1%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='statereference',
            name='property_tax_rate',
            field=models.DecimalField(decimal_places=2, help_text='Average property tax rate (as decimal: 0.40 = 40%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='statereference',
            name='transfer_tax_rate',
            field=models.DecimalField(decimal_places=2, help_text='Tax rate for property transfers (as decimal: 0.01 = 1%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='statereference',
            name='value_adjustment_annual',
            field=models.DecimalField(decimal_places=2, help_text='Average value adjustment (as decimal: 0.02 = 2%)', max_digits=5),
        ),
    ]
