# Generated by Django 5.2.5 on 2025-10-02 18:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_statereference_insurance_rate_avg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statereference',
            name='insurance_rate_avg',
            field=models.DecimalField(decimal_places=4, help_text='Average insurance rate (as decimal: 0.0040 = 0.40%, range: 0-100%)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))]),
        ),
        migrations.AlterField(
            model_name='statereference',
            name='property_tax_rate',
            field=models.DecimalField(decimal_places=4, help_text='Average property tax rate (as decimal: 0.0063 = 0.63%, range: 0-100%)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))]),
        ),
        migrations.AlterField(
            model_name='statereference',
            name='transfer_tax_rate',
            field=models.DecimalField(decimal_places=4, help_text='Tax rate for property transfers (as decimal: 0.0033 = 0.33%, range: 0-100%)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))]),
        ),
        migrations.AlterField(
            model_name='statereference',
            name='value_adjustment_annual',
            field=models.DecimalField(decimal_places=4, help_text='Average value adjustment (as decimal: 0.0028 = 0.28%, range: -100% to +100%)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('-1.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))]),
        ),
    ]
