# Generated by Django 5.2.5 on 2025-10-06 18:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_servicer_bk_fee_alter_servicer_board_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(help_text='Name of the tenant', max_length=100)),
                ('unit_name', models.CharField(help_text='Name of the unit', max_length=100)),
                ('sq_feet', models.IntegerField(help_text='Square footage of the unit')),
                ('rent', models.DecimalField(decimal_places=2, help_text='Monthly rent amount', max_digits=10)),
                ('cam_month', models.IntegerField(help_text='CAM month')),
                ('lease_term_months', models.IntegerField(blank=True, help_text='Lease term in months. If blank, will be auto-calculated from start/end dates.', null=True)),
                ('lease_start_date', models.DateField(help_text='Lease start date')),
                ('lease_end_date', models.DateField(help_text='Lease end date')),
                ('lease_type', models.CharField(help_text='Type of lease', max_length=50)),
                ('rent_increase_pct', models.DecimalField(decimal_places=2, help_text='Rent increase percentage', max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments about this unit type', null=True)),
                ('asset_hub_id', models.ForeignKey(help_text='Asset this rent roll belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rent_rolls', to='core.assetidhub')),
            ],
        ),
        migrations.CreateModel(
            name='UnitMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(help_text="Type of unit (e.g., '1BR', '2BR', 'Studio', 'Retail', 'Office')", max_length=50)),
                ('unit_count', models.IntegerField(help_text='Number of units of this type', validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_avg_sqft', models.IntegerField(help_text='Average square footage per unit of this type', validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_avg_rent', models.DecimalField(decimal_places=2, help_text='Average monthly rent per unit of this type', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_sqft', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Calculated: unit_avg_rent / unit_avg_sqft (rent per sqft)', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments about this unit type', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_hub_id', models.ForeignKey(help_text='Asset this unit mix belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='unit_mixes', to='core.assetidhub')),
            ],
            options={
                'verbose_name': 'Unit Mix',
                'verbose_name_plural': 'Unit Mix Records',
                'ordering': ['unit_type'],
            },
        ),
    ]
