# Generated by Django 5.2.5 on 2025-10-06 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_comparableproperty_leasecomparable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPropertyCashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Calendar year for this cash flow data (e.g., 2024).')),
                ('gross_rent_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Gross potential rent (GPR) - fully occupied rent for the year.', max_digits=14, null=True)),
                ('cam_income', models.DecimalField(blank=True, decimal_places=2, help_text='CAM income for the year.', max_digits=14, null=True)),
                ('other_income', models.DecimalField(blank=True, decimal_places=2, help_text='Other income (parking, laundry, pet fees, etc.).', max_digits=14, null=True)),
                ('vacancy_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Vacancy percentage for the year.', max_digits=5, null=True)),
                ('vacancy_loss', models.DecimalField(blank=True, decimal_places=2, help_text='Vacancy and credit loss for the year (negative impact on income).', max_digits=14, null=True)),
                ('admin', models.DecimalField(blank=True, decimal_places=2, help_text='Administrative expenses.', max_digits=14, null=True)),
                ('insurance', models.DecimalField(blank=True, decimal_places=2, help_text='Property insurance costs.', max_digits=14, null=True)),
                ('utilities_water', models.DecimalField(blank=True, decimal_places=2, help_text='Water utility expenses.', max_digits=14, null=True)),
                ('utilities_sewer', models.DecimalField(blank=True, decimal_places=2, help_text='Sewer utility expenses.', max_digits=14, null=True)),
                ('utilities_electric', models.DecimalField(blank=True, decimal_places=2, help_text='Electric utility expenses.', max_digits=14, null=True)),
                ('utilities_gas', models.DecimalField(blank=True, decimal_places=2, help_text='Gas utility expenses.', max_digits=14, null=True)),
                ('trash', models.DecimalField(blank=True, decimal_places=2, help_text='Trash removal expenses.', max_digits=14, null=True)),
                ('utilities_other', models.DecimalField(blank=True, decimal_places=2, help_text='Other utility expenses.', max_digits=14, null=True)),
                ('property_management', models.DecimalField(blank=True, decimal_places=2, help_text='Property management fees.', max_digits=14, null=True)),
                ('repairs_maintenance', models.DecimalField(blank=True, decimal_places=2, help_text='Repairs and maintenance costs.', max_digits=14, null=True)),
                ('marketing', models.DecimalField(blank=True, decimal_places=2, help_text='Marketing and leasing costs.', max_digits=14, null=True)),
                ('property_taxes', models.DecimalField(blank=True, decimal_places=2, help_text='Property taxes.', max_digits=14, null=True)),
                ('hoa_fees', models.DecimalField(blank=True, decimal_places=2, help_text='HOA fees (if applicable).', max_digits=14, null=True)),
                ('security_property_preservation', models.DecimalField(blank=True, decimal_places=2, help_text='Security expenses.', max_digits=14, null=True)),
                ('landscaping', models.DecimalField(blank=True, decimal_places=2, help_text='Landscaping and grounds maintenance.', max_digits=14, null=True)),
                ('pool_maintenance', models.DecimalField(blank=True, decimal_places=2, help_text='Pool maintenance costs.', max_digits=14, null=True)),
                ('other_expense', models.DecimalField(blank=True, decimal_places=2, help_text='Other miscellaneous operating expenses.', max_digits=14, null=True)),
                ('notes', models.TextField(blank=True, help_text="Additional notes about this year's performance.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_hub', models.ForeignKey(help_text='Asset this historical cash flow data belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='historical_cashflows', to='core.assetidhub')),
            ],
            options={
                'verbose_name': 'Historical Property Cash Flow',
                'verbose_name_plural': 'Historical Property Cash Flows',
                'db_table': 'core_historical_property_cashflow',
                'ordering': ['asset_hub', '-year'],
                'indexes': [models.Index(fields=['asset_hub', 'year'], name='core_histor_asset_h_6cd6b4_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset_hub', 'year'), name='uq_asset_hub_year')],
            },
        ),
    ]
