# Generated by Django 5.2.5 on 2025-10-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_historicalpropertycashflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetidhub',
            name='is_commercial',
            field=models.BooleanField(blank=True, help_text='Simple tag: True for commercial assets, False for residential. If blank, inferred at save time.', null=True),
        ),
    ]
