# Generated by Django 5.2.5 on 2025-10-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_assetidhub_is_commercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentroll',
            name='cam_month',
            field=models.IntegerField(blank=True, help_text='CAM month', null=True),
        ),
        migrations.AlterField(
            model_name='rentroll',
            name='lease_end_date',
            field=models.DateField(blank=True, help_text='Lease end date', null=True),
        ),
        migrations.AlterField(
            model_name='rentroll',
            name='lease_start_date',
            field=models.DateField(blank=True, help_text='Lease start date', null=True),
        ),
        migrations.AlterField(
            model_name='rentroll',
            name='lease_type',
            field=models.CharField(blank=True, help_text='Type of lease', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rentroll',
            name='rent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rent amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rentroll',
            name='rent_increase_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rent increase percentage', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rentroll',
            name='sq_feet',
            field=models.IntegerField(blank=True, help_text='Square footage of the unit', null=True),
        ),
        migrations.AlterField(
            model_name='rentroll',
            name='tenant_name',
            field=models.CharField(blank=True, help_text='Name of the tenant', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rentroll',
            name='unit_name',
            field=models.CharField(blank=True, help_text='Name of the unit', max_length=100, null=True),
        ),
    ]
