# Generated by Django 5.2.5 on 2025-10-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_rentroll_cam_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpropertycashflow',
            old_name='gross_rent_revenue',
            new_name='gross_potential_rent_revenue',
        ),
        migrations.RemoveField(
            model_name='historicalpropertycashflow',
            name='vacancy_loss',
        ),
        migrations.AlterField(
            model_name='historicalpropertycashflow',
            name='vacancy_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vacancy percentage for the year (as decimal, e.g., 5.00 for 5%).', max_digits=5, null=True),
        ),
    ]
