# Generated by Django 5.2.5 on 2025-10-10 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0013_tradelevelassumption_servicer_and_more'),
        ('core', '0018_rename_gross_rent_revenue_historicalpropertycashflow_gross_potential_rent_revenue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercrm',
            name='tag',
            field=models.CharField(blank=True, choices=[('broker', 'Broker'), ('trading_partner', 'Trading Partner'), ('investor', 'Investor'), ('legal', 'Legal'), ('vendor', 'Vendor')], db_index=True, help_text='Contact type: Broker, Trading Partner, Investor, Legal, or Vendor', max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title/description', max_length=255)),
                ('date', models.DateField(help_text='Event date')),
                ('time', models.CharField(default='All Day', help_text="Event time (e.g., '9:00 AM - 10:00 AM' or 'All Day')", max_length=50)),
                ('description', models.TextField(blank=True, default='', help_text='Additional event details')),
                ('category', models.CharField(choices=[('bg-primary', 'Primary (Blue)'), ('bg-success', 'Success (Green)'), ('bg-info', 'Info (Cyan)'), ('bg-warning', 'Warning (Yellow)'), ('bg-danger', 'Danger (Red)'), ('bg-secondary', 'Secondary (Gray)')], default='bg-primary', help_text='Event color category', max_length=50)),
                ('is_reminder', models.BooleanField(default=False, help_text='Is this a reminder/alert?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_hub', models.ForeignKey(blank=True, help_text='Link to specific asset (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.assetidhub')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, help_text='Link to seller (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='acq_module.seller')),
                ('trade', models.ForeignKey(blank=True, help_text='Link to trade (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='acq_module.trade')),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['date', 'time'],
                'indexes': [models.Index(fields=['date'], name='core_calend_date_a92aa1_idx'), models.Index(fields=['created_by', 'date'], name='core_calend_created_d1363a_idx'), models.Index(fields=['seller', 'date'], name='core_calend_seller__b409e9_idx'), models.Index(fields=['trade', 'date'], name='core_calend_trade_i_85e89b_idx')],
            },
        ),
    ]
