# Generated by Django 5.2 on 2025-10-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_mastercrm_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercrm',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='crm_contacts', to='core.statereference'),
        ),
    ]
