# Generated by Django 5.2 on 2025-10-15 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_mastercrm_states'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mastercrm',
            name='core_master_state_717dd6_idx',
        ),
        migrations.RemoveField(
            model_name='mastercrm',
            name='state',
        ),
    ]
