# Generated by Django 5.2 on 2025-10-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_mastercrm_core_master_state_717dd6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetidhub',
            name='asset_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('LIQUIDATED', 'Liquidated')], db_index=True, default='ACTIVE', help_text='Canonical lifecycle status for this asset hub (drives UI dropdown and module coordination).', max_length=32),
        ),
    ]
