# Generated by Django 5.2.5 on 2025-10-22 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_assetidhub_asset_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='broker_contact',
            field=models.ForeignKey(blank=True, help_text='CRM contact (usually broker) associated with this valuation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuations', to='core.mastercrm'),
        ),
        migrations.CreateModel(
            name='ValuationGradeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], help_text='Canonical grade code selected from the fixed set (A+, A, B, C, D, F).', max_length=2, unique=True)),
                ('label', models.CharField(help_text='Plain-language grade label for UI display.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Extended guidance on when to use this grade.', null=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Controls ordering of grades in dropdowns.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this grade was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this grade was last updated.')),
            ],
            options={
                'verbose_name': 'Valuation Grade Reference',
                'verbose_name_plural': 'Valuation Grade References',
                'db_table': 'core_valuation_grade_reference',
                'ordering': ['sort_order', 'code'],
                'indexes': [models.Index(fields=['code'], name='core_valuat_code_9d3a57_idx'), models.Index(fields=['sort_order'], name='core_valuat_sort_or_d78e1c_idx')],
            },
        ),
        migrations.AddField(
            model_name='valuation',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='Reference grade applied to this valuation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_valuations', to='core.valuationgradereference'),
        ),
        migrations.AddIndex(
            model_name='valuation',
            index=models.Index(fields=['broker_contact'], name='acq_valuati_broker__ffb5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='valuation',
            index=models.Index(fields=['grade'], name='acq_valuati_grade_i_557190_idx'),
        ),
    ]
