# Generated by Django 5.2 on 2025-10-23 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_valuation_broker_contact_valuationgradereference_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrokerValues',
        ),
    ]
