# Generated by Django 5.2 on 2025-10-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_brokervalues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternalValuation',
        ),
    ]
