# Generated by Django 5.2.5 on 2025-10-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_delete_internalvaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercrm',
            name='tag',
            field=models.CharField(blank=True, choices=[('broker', 'Broker'), ('trading_partner', 'Trading Partner'), ('investor', 'Investor'), ('legal', 'Legal'), ('vendor', 'Vendor'), ('servicer', 'Servicer')], db_index=True, help_text='Contact type: Broker, Trading Partner, Investor, Legal, Servicer, or Vendor', max_length=32, null=True),
        ),
    ]
