# Generated by Django 5.2 on 2025-10-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_mastercrm_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtfacility',
            name='commitment_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='debtfacility',
            name='facility_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='debtfacility',
            name='firm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='debtfacility',
            name='rate_index',
            field=models.CharField(blank=True, default='SOFR', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='debtfacility',
            name='sofr_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='jvequitypartner',
            name='acq_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='jvequitypartner',
            name='am_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='jvequitypartner',
            name='commitment_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='jvequitypartner',
            name='gp_contribution_paydown',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='jvequitypartner',
            name='jv_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jvequitypartner',
            name='lp_contribution_paydown',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='jvequitypartner',
            name='lp_pref',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='jvequitypartner',
            name='partner_firm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
