# Generated by Django 5.2 on 2025-10-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_debtfacility_commitment_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtfacility',
            name='firm_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='debtfacility',
            name='firm_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jvequitypartner',
            name='partner_firm_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='jvequitypartner',
            name='partner_firm_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
