# Generated by Django 5.2 on 2025-10-27 21:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_debtfacility_firm_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total committed capital amount', max_digits=18, null=True)),
                ('ownership_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Ownership percentage (e.g., 25.50 for 25.5%)', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this investor is currently active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the investor', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crm_contact', models.ForeignKey(blank=True, help_text='Link to CRM contact for investor name and contact information', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_investor_records', to='core.mastercrm')),
            ],
            options={
                'verbose_name': 'Co-Investor',
                'verbose_name_plural': 'Co-Investors',
                'db_table': 'co_investor',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InvestorContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_date', models.DateField(help_text='Date when capital was contributed')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Contribution amount', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('payment_method', models.CharField(blank=True, help_text='Payment method (wire, check, ACH, etc.)', max_length=100, null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Payment reference or transaction number', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this contribution', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_investor', models.ForeignKey(help_text='Co-investor who made this contribution', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.coinvestor')),
            ],
            options={
                'verbose_name': 'Investor Contribution',
                'verbose_name_plural': 'Investor Contributions',
                'db_table': 'investor_contribution',
                'ordering': ['-contribution_date', '-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InvestorDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', models.DateField(help_text='Date when distribution was made')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Distribution amount', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('distribution_type', models.CharField(choices=[('return_of_capital', 'Return of Capital'), ('profit_distribution', 'Profit Distribution'), ('preferred_return', 'Preferred Return'), ('promote', 'Promote/Carried Interest'), ('other', 'Other')], default='profit_distribution', help_text='Type of distribution', max_length=50)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method (wire, check, ACH, etc.)', max_length=100, null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Payment reference or transaction number', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this distribution', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_investor', models.ForeignKey(help_text='Co-investor receiving this distribution', on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='core.coinvestor')),
            ],
            options={
                'verbose_name': 'Investor Distribution',
                'verbose_name_plural': 'Investor Distributions',
                'db_table': 'investor_distribution',
                'ordering': ['-distribution_date', '-created_at'],
                'managed': True,
            },
        ),
    ]
