# Generated by Django 5.2 on 2025-10-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_coinvestor_investorcontribution_investordistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(help_text='Official fund name', max_length=255)),
                ('fund_type', models.CharField(choices=[('commingled', 'Commingled Fund'), ('separate_account', 'Separate Account'), ('jv', 'Joint Venture'), ('spv', 'Special Purpose Vehicle'), ('other', 'Other')], default='commingled', help_text='Fund structure type', max_length=50)),
                ('fund_status', models.CharField(choices=[('fundraising', 'Fundraising'), ('active', 'Active/Investing'), ('harvesting', 'Harvesting/Liquidating'), ('closed', 'Closed'), ('liquidated', 'Fully Liquidated')], default='fundraising', help_text='Current fund lifecycle status', max_length=50)),
                ('target_fund_size', models.DecimalField(blank=True, decimal_places=2, help_text='Target total capital to raise', max_digits=18, null=True)),
                ('total_commitments', models.DecimalField(blank=True, decimal_places=2, help_text='Total committed capital from all investors', max_digits=18, null=True)),
                ('total_funded', models.DecimalField(blank=True, decimal_places=2, help_text='Total capital actually contributed/funded', max_digits=18, null=True)),
                ('inception_date', models.DateField(blank=True, help_text='Fund inception/formation date', null=True)),
                ('first_close_date', models.DateField(blank=True, help_text='Date of first capital close', null=True)),
                ('final_close_date', models.DateField(blank=True, help_text='Date of final capital close', null=True)),
                ('investment_period_end', models.DateField(blank=True, help_text='End of investment period', null=True)),
                ('fund_term_years', models.PositiveIntegerField(blank=True, help_text='Fund term in years (e.g., 10)', null=True)),
                ('maturity_date', models.DateField(blank=True, help_text='Fund maturity/termination date', null=True)),
                ('management_fee_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Annual management fee percentage (e.g., 1.50 for 1.5%)', max_digits=5, null=True)),
                ('acquisition_fee_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Acquisition fee percentage (e.g., 1.00 for 1%)', max_digits=5, null=True)),
                ('disposition_fee_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Disposition fee percentage (e.g., 1.00 for 1%)', max_digits=5, null=True)),
                ('am_fees', models.DecimalField(blank=True, decimal_places=2, help_text='Asset management fees (absolute dollar amount)', max_digits=18, null=True)),
                ('acq_fees', models.DecimalField(blank=True, decimal_places=2, help_text='Acquisition fees (absolute dollar amount)', max_digits=18, null=True)),
                ('lp_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='LP ownership percentage (e.g., 80.00 for 80%)', max_digits=5, null=True)),
                ('gp_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='GP ownership percentage (e.g., 20.00 for 20%)', max_digits=5, null=True)),
                ('lp_contribution_paydown', models.DecimalField(blank=True, decimal_places=2, help_text='Actual LP capital contributed/paid down', max_digits=18, null=True)),
                ('gp_contribution_paydown', models.DecimalField(blank=True, decimal_places=2, help_text='Actual GP capital contributed/paid down', max_digits=18, null=True)),
                ('preferred_return_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Preferred return hurdle rate (e.g., 8.00 for 8%)', max_digits=5, null=True)),
                ('lp_promote', models.DecimalField(blank=True, decimal_places=2, help_text='LP promote percentage after hurdle (e.g., 80.00 for 80%)', max_digits=5, null=True)),
                ('gp_promote_pct', models.DecimalField(blank=True, decimal_places=2, help_text='GP promote/carried interest percentage (e.g., 20.00 for 20%)', max_digits=5, null=True)),
                ('gp_catchup_pct', models.DecimalField(blank=True, decimal_places=2, help_text='GP catch-up percentage (e.g., 100.00 for 100%)', max_digits=5, null=True)),
                ('investment_strategy', models.TextField(blank=True, help_text='Description of investment strategy and focus', null=True)),
                ('target_geography', models.CharField(blank=True, help_text="Target geographic focus (e.g., 'US Nationwide', 'Southeast US')", max_length=255, null=True)),
                ('legal_entity_name', models.CharField(blank=True, help_text='Legal entity name (if different from fund name)', max_length=255, null=True)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID/EIN', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the fund', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fund',
                'verbose_name_plural': 'Funds',
                'db_table': 'fund',
                'ordering': ['-inception_date', 'fund_name'],
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='jvequitypartner',
            options={'managed': True, 'verbose_name': 'Equity Partner (DEPRECATED)', 'verbose_name_plural': 'Equity Partners (DEPRECATED)'},
        ),
    ]
