# Generated by Django 5.2 on 2025-10-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_fund_alter_jvequitypartner_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOAAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('SFR', 'SFR'), ('Manufactured', 'Manufactured'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('2-4 Family', '2-4 Family'), ('Land', 'Land'), ('Multifamily 5+', 'Multifamily 5+'), ('Industrial', 'Industrial'), ('Mixed Use', 'Mixed Use'), ('Storage', 'Storage'), ('Healthcare', 'Healthcare')], help_text='Property type matching SellerRawData.PropertyType choices', max_length=20, unique=True)),
                ('monthly_hoa_fee', models.DecimalField(decimal_places=2, help_text='Default monthly HOA fee for this property type', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about HOA assumptions for this property type', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HOA Assumption',
                'verbose_name_plural': 'HOA Assumptions',
                'db_table': 'hoa_assumptions',
                'ordering': ['property_type'],
                'indexes': [models.Index(fields=['property_type'], name='hoa_assumpt_propert_86cbe9_idx')],
            },
        ),
    ]
