# Generated by Django 5.2 on 2025-10-30 03:49

from django.db import migrations
from decimal import Decimal


def populate_hoa_defaults(apps, schema_editor):
    """Populate HOA assumptions with default values for key property types."""
    HOAAssumption = apps.get_model('core', 'HOAAssumption')
    
    # Default HOA values as specified by user
    default_values = [
        ('Condo', Decimal('400.00'), 'Default HOA fee for condominium properties'),
        ('SFR', Decimal('200.00'), 'Default HOA fee for single-family residential properties'),
        ('Townhouse', Decimal('300.00'), 'Default HOA fee for townhouse properties'),
        ('2-4 Family', Decimal('300.00'), 'Default HOA fee for 2-4 family properties'),
    ]
    
    # Create HOA assumption records
    for property_type, monthly_fee, notes in default_values:
        HOAAssumption.objects.get_or_create(
            property_type=property_type,
            defaults={
                'monthly_hoa_fee': monthly_fee,
                'notes': notes,
            }
        )


def reverse_populate_hoa_defaults(apps, schema_editor):
    """Remove the default HOA assumptions."""
    HOAAssumption = apps.get_model('core', 'HOAAssumption')
    
    # Property types to remove
    property_types = ['Condo', 'SFR', 'Townhouse', '2-4 Family']
    
    # Delete the default records
    HOAAssumption.objects.filter(property_type__in=property_types).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_hoa_assumption_model'),
    ]

    operations = [
        migrations.RunPython(
            populate_hoa_defaults,
            reverse_populate_hoa_defaults,
        ),
    ]
