# Generated by Django 5.2 on 2025-10-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_populate_hoa_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoaassumption',
            name='property_type',
            field=models.CharField(help_text='Property type (typically residential types like SFR, Condo, Townhouse, etc.)', max_length=20, unique=True),
        ),
    ]
