# Generated by Django 5.2 on 2025-10-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_hoa_property_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='statereference',
            name='broker_closing_cost_fees_avg',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Average broker closing cost fees', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statereference',
            name='other_closing_cost_fees_avg',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Average other closing cost fees', max_digits=10),
            preserve_default=False,
        ),
    ]
