# Generated by Django 5.2.5 on 2025-10-31 00:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_statereference_broker_closing_cost_fees_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statereference',
            name='landscaping_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average monthly landscaping cost in dollars', max_digits=10),
        ),
        migrations.AddField(
            model_name='statereference',
            name='marketing_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average monthly marketing cost in dollars', max_digits=10),
        ),
        migrations.AddField(
            model_name='statereference',
            name='pool_maintenance_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average monthly pool maintenance cost in dollars', max_digits=10),
        ),
        migrations.AddField(
            model_name='statereference',
            name='property_management_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average monthly property management cost in dollars', max_digits=10),
        ),
        migrations.AddField(
            model_name='statereference',
            name='renovation_cost_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average one-time renovation cost in dollars', max_digits=10),
        ),
        migrations.AddField(
            model_name='statereference',
            name='repairs_maintenance_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average monthly repairs and maintenance cost in dollars', max_digits=10),
        ),
        migrations.AddField(
            model_name='statereference',
            name='security_cost_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average monthly security cost in dollars', max_digits=10),
        ),
        migrations.AddField(
            model_name='statereference',
            name='trashout_cost_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average one-time trashout cost in dollars', max_digits=10),
        ),
        migrations.AddField(
            model_name='statereference',
            name='utility_electric_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average monthly electric utility cost in dollars', max_digits=10),
        ),
        migrations.AddField(
            model_name='statereference',
            name='utility_gas_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average monthly gas utility cost in dollars', max_digits=10),
        ),
        migrations.AddField(
            model_name='statereference',
            name='utility_other_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average monthly other utility costs in dollars', max_digits=10),
        ),
        migrations.AddField(
            model_name='statereference',
            name='utility_sewer_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average monthly sewer utility cost in dollars', max_digits=10),
        ),
        migrations.AddField(
            model_name='statereference',
            name='utility_trash_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average monthly trash utility cost in dollars', max_digits=10),
        ),
        migrations.AddField(
            model_name='statereference',
            name='utility_water_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average monthly water utility cost in dollars', max_digits=10),
        ),
    ]
