# Generated by Django 5.2 on 2025-11-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_propertytypeassumption_squarefootageassumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicer',
            name='liqfee_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Liquidation fee percentage as decimal (e.g., 0.015 = 1.5%)', max_digits=10, null=True),
        ),
    ]
