# Generated by Django 5.2.5 on 2025-11-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_update_servicer_liqfee_pct_decimal_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoaassumption',
            name='property_type',
            field=models.CharField(choices=[('SFR', 'SFR'), ('Manufactured', 'Manufactured'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('2-4 Family', '2-4 Family'), ('Multifamily 5+', 'Multifamily 5+'), ('Land', 'Land'), ('Industrial', 'Industrial'), ('Mixed Use', 'Mixed Use'), ('Storage', 'Storage'), ('Healthcare', 'Healthcare')], help_text='Property type (typically residential types like SFR, Condo, Townhouse, etc.)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='landscaping_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly landscaping cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='marketing_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly marketing cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='pool_maintenance_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly pool maintenance cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='property_management_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly property management cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='property_type',
            field=models.CharField(choices=[('SFR', 'SFR'), ('Manufactured', 'Manufactured'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('2-4 Family', '2-4 Family'), ('Multifamily 5+', 'Multifamily 5+'), ('Land', 'Land'), ('Industrial', 'Industrial'), ('Mixed Use', 'Mixed Use'), ('Storage', 'Storage'), ('Healthcare', 'Healthcare')], help_text='Property type for these assumptions', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='renovation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='One-time renovation cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='repairs_maintenance_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly repairs and maintenance cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='security_cost_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly security cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='trashout_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='One-time trashout cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='utility_electric_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly electric utility cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='utility_gas_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly gas utility cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='utility_other_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly other utility costs in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='utility_sewer_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly sewer utility cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='utility_trash_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly trash utility cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='utility_water_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly water utility cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='squarefootageassumption',
            name='landscaping_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Landscaping cost per square foot per month', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='squarefootageassumption',
            name='marketing_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Marketing cost per square foot per month', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='squarefootageassumption',
            name='pool_maintenance_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Pool maintenance cost per square foot per month', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='squarefootageassumption',
            name='property_management_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Property management cost per square foot per month', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='squarefootageassumption',
            name='renovation_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Renovation cost per square foot (one-time)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='squarefootageassumption',
            name='repairs_maintenance_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Repairs and maintenance cost per square foot per month', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='squarefootageassumption',
            name='security_cost_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Security cost per square foot per month', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='squarefootageassumption',
            name='trashout_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Trashout cost per square foot (one-time)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='squarefootageassumption',
            name='utility_electric_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Electric cost per square foot per month', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='squarefootageassumption',
            name='utility_gas_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Gas cost per square foot per month', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='squarefootageassumption',
            name='utility_other_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Other utility cost per square foot per month', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='squarefootageassumption',
            name='utility_sewer_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Sewer cost per square foot per month', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='squarefootageassumption',
            name='utility_trash_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Trash cost per square foot per month', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='squarefootageassumption',
            name='utility_water_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Water cost per square foot per month', max_digits=8, null=True),
        ),
    ]
