# Generated by Django 5.2.5 on 2025-11-05 03:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_squarefootageassumption_sqft_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedgerEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(db_index=True, help_text='General ledger entry identifier or reference number', max_length=100)),
                ('company_name', models.CharField(db_index=True, help_text='Name of the company associated with this GL entry', max_length=255)),
                ('loan_number', models.CharField(blank=True, db_index=True, help_text='Loan number associated with this GL entry (if applicable)', max_length=100, null=True)),
                ('borrower_name', models.CharField(blank=True, help_text='Name of the borrower associated with this loan', max_length=255, null=True)),
                ('document_number', models.CharField(blank=True, db_index=True, help_text='Internal document number for this GL entry', max_length=100, null=True)),
                ('external_document_number', models.CharField(blank=True, help_text='External document number or reference from third-party systems', max_length=100, null=True)),
                ('document_type', models.CharField(blank=True, help_text='Type of document (e.g., Invoice, Receipt, Journal Entry, etc.)', max_length=100, null=True)),
                ('loan_type', models.CharField(blank=True, help_text='Type of loan (e.g., Commercial, Residential, etc.)', max_length=100, null=True)),
                ('date_funded', models.DateField(blank=True, help_text='Date when the loan was funded (if applicable)', null=True)),
                ('posting_date', models.DateField(db_index=True, help_text='Date when the GL entry was posted to the ledger')),
                ('entry_date', models.DateField(db_index=True, help_text='Date when the GL entry was created or entered into the system')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total transaction amount (if using a single amount field)', max_digits=15, null=True)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit amount for this GL entry (increases liability/equity/revenue)', max_digits=15)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Debit amount for this GL entry (increases assets/expenses)', max_digits=15)),
                ('account_number', models.CharField(db_index=True, help_text='Chart of accounts number for this GL entry', max_length=50)),
                ('account_name', models.CharField(help_text='Name of the account from the chart of accounts', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the GL entry transaction', null=True)),
                ('reason_code', models.CharField(blank=True, help_text='Code indicating the reason or category for this GL entry', max_length=50, null=True)),
                ('comment', models.TextField(blank=True, help_text='Additional comments or notes about this GL entry', null=True)),
                ('cost_center', models.CharField(blank=True, db_index=True, help_text='Cost center code for departmental tracking and allocation', max_length=50, null=True)),
                ('cost_center_name', models.CharField(blank=True, help_text='Name of the cost center for easier identification', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created in the database')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
            ],
            options={
                'verbose_name': 'General Ledger Entry',
                'verbose_name_plural': 'General Ledger Entries',
                'db_table': 'general_ledger_entries',
                'ordering': ['-posting_date', '-entry_date'],
                'indexes': [models.Index(fields=['posting_date'], name='general_led_posting_868b58_idx'), models.Index(fields=['entry_date'], name='general_led_entry_d_25ad1f_idx'), models.Index(fields=['company_name', 'posting_date'], name='general_led_company_f773be_idx'), models.Index(fields=['loan_number', 'posting_date'], name='general_led_loan_nu_665a55_idx'), models.Index(fields=['account_number', 'posting_date'], name='general_led_account_78ef1f_idx'), models.Index(fields=['cost_center', 'posting_date'], name='general_led_cost_ce_81fcb4_idx')],
            },
        ),
    ]
