# Generated by Django 5.2.5 on 2025-11-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_generalledgerentries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledgerentries',
            name='entry',
            field=models.CharField(db_index=True, help_text='General ledger entry identifier or reference number', max_length=100, unique=True),
        ),
    ]
