# Generated by Django 5.2.5 on 2025-11-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_generalledgerentries_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, help_text='Chart of accounts number for this account', max_length=50, unique=True)),
                ('account_name', models.CharField(help_text='Name of the account from the chart of accounts', max_length=255)),
                ('account_type', models.CharField(help_text='Type of account (e.g., Asset, Liability, Equity, Revenue, Expense)', max_length=50)),
                ('transaction_table_reference', models.CharField(blank=True, help_text='Reference to the LLTransactionSummary/LLCashFlowSeries field this account maps to', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Chart of Accounts',
                'verbose_name_plural': 'Chart of Accounts',
                'db_table': 'chart_of_accounts',
                'ordering': ['account_number'],
            },
        ),
    ]
