# Generated by Django 5.2.5 on 2025-11-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_chartofaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='lltransactionsummary',
            name='gross_purchase_price_realized',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual gross purchase price paid', max_digits=15, null=True),
        ),
    ]
