# Generated by Django 5.2.5 on 2025-11-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_lltransactionsummary_gross_purchase_price_realized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercrm',
            name='tag',
            field=models.CharField(blank=True, choices=[('broker', 'Broker'), ('trading_partner', 'Trading Partner'), ('investor', 'Investor'), ('legal', 'Legal'), ('vendor', 'Vendor'), ('servicer', 'Servicer'), ('title_company', 'Title Company')], db_index=True, help_text='Contact type: Broker, Trading Partner, Investor, Legal, Servicer, or Vendor', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='landscaping_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Monthly landscaping cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='marketing_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Monthly marketing cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='pool_maintenance_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Monthly pool maintenance cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='property_management_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Monthly property management cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='renovation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='One-time renovation cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='repairs_maintenance_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Monthly repairs and maintenance cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='security_cost_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Monthly security cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='trashout_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='One-time trashout cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='utility_electric_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Monthly electric utility cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='utility_gas_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Monthly gas utility cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='utility_other_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Monthly other utility costs in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='utility_sewer_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Monthly sewer utility cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='utility_trash_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Monthly trash utility cost in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypeassumption',
            name='utility_water_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Monthly water utility cost in dollars', max_digits=10, null=True),
        ),
    ]
