# Generated by Django 5.2.5 on 2025-11-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_add_default_none_to_property_type_assumptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='recommend_rehab',
            field=models.BooleanField(default=False, help_text='Whether to recommend rehabilitation.'),
        ),
        migrations.AddField(
            model_name='valuation',
            name='recommend_rehab_reason',
            field=models.TextField(blank=True, help_text='Reason for recommending rehabilitation.', null=True),
        ),
    ]
