# Generated by Django 5.2.5 on 2025-11-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_valuation_recommend_rehab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='appliances_grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], help_text='Condition grade for appliances (A+ to F).', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='valuation',
            name='bath_grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], help_text='Condition grade for bathrooms (A+ to F).', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='valuation',
            name='electrical_grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], help_text='Condition grade for electrical (A+ to F).', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='valuation',
            name='flooring_grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], help_text='Condition grade for flooring (A+ to F).', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='valuation',
            name='kitchen_grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], help_text='Condition grade for kitchen (A+ to F).', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='valuation',
            name='landscaping_grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], help_text='Condition grade for landscaping (A+ to F).', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='valuation',
            name='plumbing_grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], help_text='Condition grade for plumbing (A+ to F).', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='valuation',
            name='roof_grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], help_text='Condition grade for roof (A+ to F).', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='valuation',
            name='windows_grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], help_text='Condition grade for windows (A+ to F).', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='appliances_est',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost for appliance repairs/replacement.', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='bath_est',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost for bathroom repairs/upgrades.', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='electrical_est',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost for electrical repairs/upgrades.', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='flooring_est',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost for flooring repairs/replacement.', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='kitchen_est',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost for kitchen repairs/upgrades.', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='landscaping_est',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost for landscaping improvements.', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='plumbing_est',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost for plumbing repairs.', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='roof_est',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost for roof repairs/replacement.', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='windows_est',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost for window repairs/replacement.', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='valuationgradereference',
            name='code',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], help_text='Canonical grade code selected from the fixed set (A+, A, B, C, D, F). Uses centralized Grade enum from model_co_lookupTables.', max_length=2, unique=True),
        ),
    ]
