# Generated by Django 5.2.5 on 2025-11-13 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_valuation_appliances_grade_valuation_bath_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerMSAAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1, help_text='Assignment priority (1 = primary, 2 = backup, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this broker-MSA assignment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker MSA Assignment',
                'verbose_name_plural': 'Broker MSA Assignments',
                'db_table': 'broker_msa_assignments',
                'ordering': ['msa', 'priority', 'broker'],
            },
        ),
        migrations.CreateModel(
            name='CountyReference',
            fields=[
                ('county_fips', models.CharField(help_text='5-digit FIPS code (2-digit state + 3-digit county)', max_length=5, primary_key=True, serialize=False)),
                ('county_name', models.CharField(help_text="Official county name (e.g., 'Los Angeles County', 'Cook County')", max_length=100)),
                ('population', models.IntegerField(blank=True, help_text='County population (from latest Census estimate)', null=True)),
                ('county_seat', models.CharField(blank=True, help_text='County seat (main city where courthouse is located)', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this county is currently active')),
            ],
            options={
                'verbose_name': 'County Reference',
                'verbose_name_plural': 'County References',
                'db_table': 'county_reference',
                'ordering': ['state', 'county_name'],
            },
        ),
        migrations.CreateModel(
            name='ZIPReference',
            fields=[
                ('zip_code', models.CharField(help_text='5-digit ZIP code (USPS format)', max_length=5, primary_key=True, serialize=False)),
                ('city_name', models.CharField(blank=True, help_text='Primary city name for this ZIP code', max_length=100, null=True)),
                ('zip_type', models.CharField(choices=[('STANDARD', 'Standard'), ('PO_BOX', 'PO Box'), ('UNIQUE', 'Unique (Single Building)'), ('MILITARY', 'Military')], default='STANDARD', help_text='ZIP code type classification', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this ZIP code is currently active per USPS')),
            ],
            options={
                'verbose_name': 'ZIP Code Reference',
                'verbose_name_plural': 'ZIP Code References',
                'db_table': 'zip_reference',
                'ordering': ['zip_code'],
            },
        ),
        migrations.AlterModelOptions(
            name='msareference',
            options={'ordering': ['msa_name'], 'verbose_name': 'MSA Reference', 'verbose_name_plural': 'MSA References'},
        ),
        migrations.AddField(
            model_name='msareference',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Primary state for this MSA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msas', to='core.statereference'),
        ),
        migrations.AlterField(
            model_name='msareference',
            name='msa_code',
            field=models.CharField(help_text='5-digit CBSA code from Census Bureau', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='msareference',
            name='msa_name',
            field=models.CharField(help_text="Full MSA name from Census Bureau (e.g., 'New York-Newark-Jersey City, NY-NJ-PA')", max_length=255),
        ),
        migrations.AddIndex(
            model_name='msareference',
            index=models.Index(fields=['msa_code'], name='msa_referen_msa_cod_c3d38a_idx'),
        ),
        migrations.AddIndex(
            model_name='msareference',
            index=models.Index(fields=['state'], name='msa_referen_state_i_f4a701_idx'),
        ),
        migrations.AddIndex(
            model_name='msareference',
            index=models.Index(fields=['msa_name'], name='msa_referen_msa_nam_9ea608_idx'),
        ),
        migrations.AlterModelTable(
            name='msareference',
            table='msa_reference',
        ),
        migrations.AddField(
            model_name='brokermsaassignment',
            name='broker',
            field=models.ForeignKey(help_text='Broker assigned to this MSA', on_delete=django.db.models.deletion.CASCADE, related_name='msa_assignments', to='core.mastercrm'),
        ),
        migrations.AddField(
            model_name='brokermsaassignment',
            name='msa',
            field=models.ForeignKey(help_text='MSA market assigned to this broker', on_delete=django.db.models.deletion.CASCADE, related_name='broker_assignments', to='core.msareference'),
        ),
        migrations.AddField(
            model_name='countyreference',
            name='state',
            field=models.ForeignKey(help_text='State this county belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='counties', to='core.statereference'),
        ),
        migrations.AddField(
            model_name='zipreference',
            name='county',
            field=models.ForeignKey(blank=True, help_text='Primary county this ZIP code belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zip_codes', to='core.countyreference'),
        ),
        migrations.AddField(
            model_name='zipreference',
            name='msa',
            field=models.ForeignKey(blank=True, help_text='MSA this ZIP code belongs to (null for rural areas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zip_codes', to='core.msareference'),
        ),
        migrations.AddField(
            model_name='zipreference',
            name='state',
            field=models.ForeignKey(help_text='State this ZIP code belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='zip_codes', to='core.statereference'),
        ),
        migrations.AddIndex(
            model_name='brokermsaassignment',
            index=models.Index(fields=['msa', 'priority'], name='broker_msa__msa_id_ef50bf_idx'),
        ),
        migrations.AddIndex(
            model_name='brokermsaassignment',
            index=models.Index(fields=['broker'], name='broker_msa__broker__078205_idx'),
        ),
        migrations.AddIndex(
            model_name='brokermsaassignment',
            index=models.Index(fields=['is_active'], name='broker_msa__is_acti_4f1d29_idx'),
        ),
        migrations.AddIndex(
            model_name='brokermsaassignment',
            index=models.Index(fields=['msa', 'is_active', 'priority'], name='broker_msa__msa_id_db09aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brokermsaassignment',
            unique_together={('broker', 'msa')},
        ),
        migrations.AddIndex(
            model_name='countyreference',
            index=models.Index(fields=['county_fips'], name='county_refe_county__01b128_idx'),
        ),
        migrations.AddIndex(
            model_name='countyreference',
            index=models.Index(fields=['state'], name='county_refe_state_i_be0b97_idx'),
        ),
        migrations.AddIndex(
            model_name='countyreference',
            index=models.Index(fields=['county_name'], name='county_refe_county__7a3900_idx'),
        ),
        migrations.AddIndex(
            model_name='countyreference',
            index=models.Index(fields=['state', 'county_name'], name='county_refe_state_i_d9ce79_idx'),
        ),
        migrations.AddIndex(
            model_name='countyreference',
            index=models.Index(fields=['is_active'], name='county_refe_is_acti_eec6af_idx'),
        ),
        migrations.AddIndex(
            model_name='zipreference',
            index=models.Index(fields=['zip_code'], name='zip_referen_zip_cod_e20e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='zipreference',
            index=models.Index(fields=['state'], name='zip_referen_state_i_3a3461_idx'),
        ),
        migrations.AddIndex(
            model_name='zipreference',
            index=models.Index(fields=['county'], name='zip_referen_county__ad88fc_idx'),
        ),
        migrations.AddIndex(
            model_name='zipreference',
            index=models.Index(fields=['msa'], name='zip_referen_msa_id_02a3fa_idx'),
        ),
        migrations.AddIndex(
            model_name='zipreference',
            index=models.Index(fields=['city_name'], name='zip_referen_city_na_13dd5c_idx'),
        ),
        migrations.AddIndex(
            model_name='zipreference',
            index=models.Index(fields=['is_active'], name='zip_referen_is_acti_0d6889_idx'),
        ),
        migrations.AddIndex(
            model_name='zipreference',
            index=models.Index(fields=['state', 'msa'], name='zip_referen_state_i_79e77e_idx'),
        ),
        migrations.AddIndex(
            model_name='zipreference',
            index=models.Index(fields=['state', 'county'], name='zip_referen_state_i_4d9291_idx'),
        ),
    ]
