# Generated by Django 5.2.5 on 2025-11-13 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_brokermsaassignment_countyreference_zipreference_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='countyreference',
            name='county_refe_is_acti_eec6af_idx',
        ),
        migrations.RemoveIndex(
            model_name='zipreference',
            name='zip_referen_is_acti_0d6889_idx',
        ),
        migrations.RemoveField(
            model_name='countyreference',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='zipreference',
            name='is_active',
        ),
    ]
