# Generated by Django 5.2.5 on 2025-11-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_countyreference_county_refe_is_acti_eec6af_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipreference',
            name='county_fips_all',
            field=models.CharField(blank=True, help_text='All county FIPS codes for this ZIP (pipe-separated for multi-county ZIPs)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zipreference',
            name='county_weights',
            field=models.TextField(blank=True, help_text='JSON of county FIPS to percentage weight for multi-county ZIPs', null=True),
        ),
    ]
