# Generated by Django 5.2.5 on 2025-11-14 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_zipreference_county_fips_all_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='final_close_date',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='first_close_date',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='target_geography',
        ),
    ]
