# Generated by Django 5.2.5 on 2025-11-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_fund_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fund_status',
            field=models.CharField(choices=[('fundraising', 'Fundraising'), ('active', 'Active/Investing'), ('harvesting', 'Harvesting/Liquidating'), ('closed', 'Closed')], default='fundraising', help_text='Current fund lifecycle status', max_length=50),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_type',
            field=models.CharField(choices=[('commingled', 'Commingled Fund'), ('separate_account', 'Separate Account'), ('jv', 'Joint Venture'), ('spv', 'Special Purpose Vehicle'), ('wholly_owned', 'Wholly Owned'), ('other', 'Other')], default='commingled', help_text='Fund structure type', max_length=50),
        ),
    ]
