# Generated by Django 5.2.5 on 2025-11-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_update_fund_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fund_type',
            field=models.CharField(choices=[('commingled', 'Commingled Fund'), ('separate_account', 'Separate Account'), ('jv', 'Joint Venture'), ('spv', 'Special Purpose Vehicle'), ('wholly_owned', 'Wholly Owned'), ('asset_management', 'Asset Management'), ('other', 'Other')], default='commingled', help_text='Fund structure type', max_length=50),
        ),
    ]
