# Generated by Django 5.2.5 on 2025-11-14 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_add_asset_management_fund_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(help_text='Legal entity name', max_length=255)),
                ('entity_type', models.CharField(choices=[('fund', 'Fund'), ('spv', 'Special Purpose Vehicle'), ('llc', 'Limited Liability Company'), ('lp', 'Limited Partnership'), ('corporation', 'Corporation'), ('trust', 'Trust'), ('other', 'Other')], help_text='Type of legal entity', max_length=50)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID/EIN', max_length=50, null=True)),
                ('formation_date', models.DateField(blank=True, help_text='Entity formation date', null=True)),
                ('formation_state', models.CharField(blank=True, help_text='State of formation (e.g., DE, NV)', max_length=2, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether entity is currently active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the entity', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.OneToOneField(blank=True, help_text='Link to Fund record if this entity is a fund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_entity', to='core.fund')),
            ],
            options={
                'verbose_name': 'Legal Entity',
                'verbose_name_plural': 'Legal Entities',
                'db_table': 'legal_entity',
                'ordering': ['entity_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage', models.DecimalField(decimal_places=2, help_text='Ownership percentage (e.g., 80.00 for 80%)', max_digits=5)),
                ('ownership_type', models.CharField(choices=[('equity', 'Equity'), ('preferred_equity', 'Preferred Equity'), ('mezzanine', 'Mezzanine Debt'), ('debt', 'Senior Debt'), ('other', 'Other')], default='equity', help_text='Type of ownership interest', max_length=50)),
                ('acquisition_date', models.DateField(blank=True, help_text='Date ownership was acquired', null=True)),
                ('disposition_date', models.DateField(blank=True, help_text='Date ownership was disposed (if sold)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this ownership record is currently active')),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost basis of acquisition', max_digits=18, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, help_text='Current estimated value', max_digits=18, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional ownership notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owned_asset', models.ForeignKey(blank=True, help_text='Asset being owned (for direct asset ownership)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownership_records', to='core.assetidhub')),
                ('owned_entity', models.ForeignKey(blank=True, help_text='Entity being owned (for entity ownership, e.g. Fund owns SPV)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownership_structure', to='core.legalentity')),
                ('owner_entity', models.ForeignKey(help_text='Entity that owns the interest', on_delete=django.db.models.deletion.CASCADE, related_name='owned_interests', to='core.legalentity')),
            ],
            options={
                'verbose_name': 'Ownership Record',
                'verbose_name_plural': 'Ownership Records',
                'db_table': 'ownership',
                'ordering': ['-acquisition_date', '-created_at'],
                'managed': True,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('owned_asset__isnull', False), ('owned_entity__isnull', True)), models.Q(('owned_asset__isnull', True), ('owned_entity__isnull', False)), _connector='OR'), name='ownership_must_be_asset_or_entity')],
            },
        ),
    ]
