# Generated by Django 5.2.5 on 2025-11-14 18:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_add_legalentity_ownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Entity name (person name, company name, trust name, etc.)', max_length=255)),
                ('entity_type', models.CharField(choices=[('individual', 'Individual'), ('llc', 'LLC'), ('jv', 'Joint Venture'), ('corporation', 'Corporation'), ('partnership', 'Partnership'), ('trust', 'Trust'), ('other', 'Other')], help_text='Type of legal entity', max_length=50)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID/EIN/SSN', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, help_text='Primary email contact', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Primary phone contact', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this entity is currently active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the entity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'db_table': 'entity',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FundLegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(help_text='Official legal name of the entity', max_length=255)),
                ('entity_role', models.CharField(choices=[('fund', 'Fund'), ('gp', 'GP'), ('lp', 'LP'), ('spv', 'SPV')], help_text='Role this entity plays in the fund structure', max_length=50)),
                ('jurisdiction', models.CharField(help_text='State/country of formation (e.g., Delaware, Cayman Islands)', max_length=100)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID/EIN for this entity', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this entity is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(help_text='Parent fund that this legal entity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='legal_entities', to='core.fund')),
            ],
            options={
                'verbose_name': 'Fund Legal Entity',
                'verbose_name_plural': 'Fund Legal Entities',
                'db_table': 'fund_legal_entity',
                'ordering': ['fund', 'entity_role', 'legal_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EntityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage', models.DecimalField(decimal_places=2, help_text='Percentage ownership in parent entity', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('membership_date', models.DateField(help_text='When they became a member/owner')),
                ('capital_account', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current capital account balance', max_digits=18)),
                ('distribution_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Distribution % if different from ownership % (optional)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this membership is currently active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this membership')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_entity', models.ForeignKey(help_text='The entity that owns a piece (e.g., John Smith)', on_delete=django.db.models.deletion.PROTECT, related_name='parent_memberships', to='core.entity')),
                ('parent_entity', models.ForeignKey(help_text='The entity being owned (e.g., GPM, LLC)', on_delete=django.db.models.deletion.CASCADE, related_name='child_members', to='core.entity')),
            ],
            options={
                'verbose_name': 'Entity Membership',
                'verbose_name_plural': 'Entity Memberships',
                'db_table': 'entity_membership',
                'ordering': ['parent_entity', '-ownership_percentage'],
                'managed': True,
                'unique_together': {('parent_entity', 'member_entity')},
            },
        ),
        migrations.CreateModel(
            name='FundMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('gp', 'General Partner'), ('lp', 'Limited Partner')], help_text='GP or LP designation', max_length=20)),
                ('admission_date', models.DateField(help_text='Date when entity joined the fund')),
                ('ownership_percentage', models.DecimalField(decimal_places=2, help_text='Ownership percentage in fund (e.g., 20.00 for 20%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('capital_committed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total capital commitment', max_digits=18)),
                ('capital_contributed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Capital actually contributed to date', max_digits=18)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this membership is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(help_text='Entity that is a member (GP or LP)', on_delete=django.db.models.deletion.PROTECT, related_name='fund_memberships', to='core.entity')),
                ('fund', models.ForeignKey(help_text='Fund that this entity is a member of', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.fund')),
                ('investing_through', models.ForeignKey(blank=True, help_text="Optional: specific fund legal entity they're investing through (e.g., domestic vs offshore feeder)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.fundlegalentity')),
            ],
            options={
                'verbose_name': 'Fund Membership',
                'verbose_name_plural': 'Fund Memberships',
                'db_table': 'fund_membership',
                'ordering': ['fund', 'member_type', '-ownership_percentage'],
                'managed': True,
                'unique_together': {('fund', 'entity')},
            },
        ),
    ]
