# Generated by Django 5.2.5 on 2025-11-14 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_entity_fundlegalentity_entitymembership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalentity',
            name='fund',
        ),
        migrations.AlterField(
            model_name='fundmembership',
            name='fund',
            field=models.ForeignKey(help_text="Fund entity (Entity with type 'Fund') that this entity is a member of", limit_choices_to={'entity_type': 'fund'}, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.entity'),
        ),
        migrations.AlterField(
            model_name='fundlegalentity',
            name='fund',
            field=models.ForeignKey(help_text="Fund entity (Entity with type 'Fund') that this legal entity belongs to", limit_choices_to={'entity_type': 'fund'}, on_delete=django.db.models.deletion.CASCADE, related_name='legal_entities', to='core.entity'),
        ),
        migrations.DeleteModel(
            name='JVEquityPartner',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='owned_entity',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='owner_entity',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='owned_asset',
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('fund', 'Fund'), ('individual', 'Individual'), ('llc', 'LLC'), ('jv', 'Joint Venture'), ('corporation', 'Corporation'), ('partnership', 'Partnership'), ('spv', 'SPV'), ('trust', 'Trust'), ('other', 'Other')], help_text='Type of legal entity', max_length=50),
        ),
        migrations.AlterField(
            model_name='fundmembership',
            name='member_type',
            field=models.CharField(choices=[('gp', 'General Partner'), ('lp', 'Limited Partner'), ('co_investor', 'Co-Investor'), ('spv', 'Special Purpose Vehicle'), ('other', 'Other')], help_text='GP or LP designation', max_length=20),
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
        migrations.DeleteModel(
            name='LegalEntity',
        ),
        migrations.DeleteModel(
            name='Ownership',
        ),
    ]
