# Generated by Django 5.2.5 on 2025-11-14 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remove_legalentity_fund_alter_fundmembership_fund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundlegalentity',
            name='fund',
            field=models.ForeignKey(help_text='Entity that this fund legal entity belongs to (no type restriction)', on_delete=django.db.models.deletion.CASCADE, related_name='legal_entities', to='core.entity'),
        ),
        migrations.AlterField(
            model_name='fundmembership',
            name='fund',
            field=models.ForeignKey(help_text='Entity representing the fund this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.entity'),
        ),
    ]
