# Generated by Django 5.2.5 on 2025-11-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_fundlegalentity_fund_alter_fundmembership_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundlegalentity',
            name='entity_role',
            field=models.CharField(blank=True, choices=[('fund', 'Fund'), ('gp', 'GP'), ('lp', 'LP'), ('spv', 'SPV')], help_text='Role this entity plays in the fund structure', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fundlegalentity',
            name='jurisdiction',
            field=models.CharField(blank=True, help_text='State/country of formation (e.g., Delaware, Cayman Islands)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fundlegalentity',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Official legal name of the entity', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fundlegalentity',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Tax ID/EIN for this entity', max_length=50, null=True),
        ),
    ]
