# Generated by Django 5.2.5 on 2025-11-14 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_fundlegalentity_entity_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDetails',
            fields=[
                ('asset', models.OneToOneField(help_text='Asset this detail row belongs to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details', serialize=False, to='core.assetidhub')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund_legal_entity', models.ForeignKey(blank=True, help_text='Fund/Entity associated with this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to='core.fundlegalentity')),
            ],
            options={
                'verbose_name': 'Asset Detail',
                'verbose_name_plural': 'Asset Details',
                'db_table': 'asset_details',
            },
        ),
    ]
