# Generated by Django 5.2.5 on 2025-11-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_assetdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundlegalentity',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Internal nickname/alias for this legal entity', max_length=255, null=True),
        ),
    ]
