# Generated by Django 5.2.5 on 2025-11-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_fundlegalentity_legal_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundlegalentity',
            options={'managed': True, 'ordering': ['fund', 'entity_role', 'nickname_name'], 'verbose_name': 'Fund Legal Entity', 'verbose_name_plural': 'Fund Legal Entities'},
        ),
        migrations.RenameField(
            model_name='fundlegalentity',
            old_name='legal_name',
            new_name='nickname_name',
        ),
        migrations.AlterField(
            model_name='fundlegalentity',
            name='entity_role',
            field=models.CharField(blank=True, choices=[('fund', 'Fund'), ('gp', 'GP'), ('lp', 'LP'), ('spv', 'SPV'), ('jv', 'Joint Venture'), ('co_investor', 'Co-Investor'), ('other', 'Other')], help_text='Role this entity plays in the fund structure', max_length=50, null=True),
        ),
    ]
