# Generated by Django 5.2.5 on 2025-11-14 23:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_fundlegalentity_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HUDZIPCBSACrosswalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(db_index=True, help_text='5-digit ZIP code from HUD crosswalk', max_length=5)),
                ('cbsa_code', models.CharField(blank=True, db_index=True, help_text='5-digit CBSA code (blank for rural ZIPs)', max_length=5, null=True)),
                ('city', models.CharField(blank=True, help_text='USPS preferred city name', max_length=100, null=True)),
                ('state_code', models.CharField(db_index=True, help_text='Two-letter state code', max_length=2)),
                ('res_ratio', models.DecimalField(decimal_places=9, default=Decimal('0.0'), help_text='Residential address ratio (0.0 to 1.0)', max_digits=12)),
                ('bus_ratio', models.DecimalField(decimal_places=9, default=Decimal('0.0'), help_text='Business address ratio (0.0 to 1.0)', max_digits=12)),
                ('oth_ratio', models.DecimalField(decimal_places=9, default=Decimal('0.0'), help_text='Other address ratio (0.0 to 1.0)', max_digits=12)),
                ('tot_ratio', models.DecimalField(db_index=True, decimal_places=9, default=Decimal('0.0'), help_text='Total address ratio (0.0 to 1.0) - use for dominant CBSA selection', max_digits=12)),
                ('imported_at', models.DateTimeField(auto_now_add=True, help_text='When this record was imported')),
            ],
            options={
                'verbose_name': 'HUD ZIP-CBSA Crosswalk',
                'verbose_name_plural': 'HUD ZIP-CBSA Crosswalks',
                'db_table': 'hud_zip_cbsa_crosswalk',
                'ordering': ['zip_code', '-tot_ratio'],
                'indexes': [models.Index(fields=['zip_code'], name='hud_zip_cbs_zip_cod_2c3bfc_idx'), models.Index(fields=['cbsa_code'], name='hud_zip_cbs_cbsa_co_ac902a_idx'), models.Index(fields=['state_code'], name='hud_zip_cbs_state_c_f18227_idx'), models.Index(fields=['zip_code', 'cbsa_code'], name='hud_zip_cbs_zip_cod_38c6b4_idx'), models.Index(fields=['zip_code', '-tot_ratio'], name='hud_zip_cbs_zip_cod_fefea5_idx')],
            },
        ),
    ]
