# Generated by Django 5.2.5 on 2025-11-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_lldataenrichment_msa_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_county_fips',
            field=models.CharField(blank=True, help_text='County FIPS code from Geocodio census data.', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_county_name',
            field=models.CharField(blank=True, help_text='County name from Geocodio census data.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_csa_code',
            field=models.CharField(blank=True, help_text='Combined Statistical Area code from Geocodio census data.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_csa_name',
            field=models.CharField(blank=True, help_text='Combined Statistical Area name from Geocodio census data.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_full_fips',
            field=models.CharField(blank=True, help_text='Full FIPS code from Geocodio census data.', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_msa_type',
            field=models.CharField(blank=True, help_text='MSA type (metropolitan/micropolitan) from Geocodio census data.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_school_district',
            field=models.CharField(blank=True, help_text='School district name from Geocodio school field.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_state_fips',
            field=models.CharField(blank=True, help_text='State FIPS code from Geocodio census data.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_tract_code',
            field=models.CharField(blank=True, help_text='Census tract code from Geocodio census data.', max_length=10, null=True),
        ),
    ]
