# Generated by Django 5.2.5 on 2025-11-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_lldataenrichment_geocode_county_fips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercrm',
            name='msas',
            field=models.ManyToManyField(blank=True, related_name='crm_brokers', through='core.BrokerMSAAssignment', through_fields=('broker', 'msa'), to='core.msareference'),
        ),
        migrations.AddField(
            model_name='mastercrm',
            name='preferred',
            field=models.BooleanField(default=False),
        ),
    ]
