# Generated by Django 5.2.5 on 2025-11-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_mastercrm_msas_mastercrm_preferred'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tag', models.CharField(blank=True, choices=[('broker', 'Broker'), ('trading_partner', 'Trading Partner'), ('investor', 'Investor'), ('legal', 'Legal'), ('vendor', 'Vendor'), ('servicer', 'Servicer'), ('title_company', 'Title Company')], db_index=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firm CRM',
                'verbose_name_plural': 'Firm CRM',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='mastercrm',
            name='core_master_firm_d00762_idx',
        ),
        migrations.RemoveField(
            model_name='mastercrm',
            name='firm',
        ),
        migrations.AddField(
            model_name='firmcrm',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='crm_firms', to='core.statereference'),
        ),
        migrations.AddField(
            model_name='mastercrm',
            name='firm_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='core.firmcrm'),
        ),
        migrations.AddIndex(
            model_name='mastercrm',
            index=models.Index(fields=['firm_ref'], name='core_master_firm_re_199072_idx'),
        ),
        migrations.AddIndex(
            model_name='firmcrm',
            index=models.Index(fields=['name'], name='core_firmcr_name_ded35f_idx'),
        ),
        migrations.AddIndex(
            model_name='firmcrm',
            index=models.Index(fields=['tag'], name='core_firmcr_tag_791e31_idx'),
        ),
    ]
