# Generated by Django 5.2.5 on 2025-11-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_firmcrm_remove_mastercrm_core_master_firm_d00762_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lldataenrichment',
            name='acq_ll_data_seller__cbb3b3_idx',
        ),
        migrations.RemoveField(
            model_name='lldataenrichment',
            name='seller_raw_data',
        ),
        migrations.AlterField(
            model_name='firmcrm',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='lldataenrichment',
            index=models.Index(fields=['asset_hub'], name='acq_ll_data_asset_h_0d4542_idx'),
        ),
    ]
