# Generated by Django 5.2.5 on 2025-11-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_remove_lldataenrichment_acq_ll_data_seller__cbb3b3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercrm',
            name='preferred',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], db_index=True, help_text='Preferred broker flag stored as yes/no text', max_length=3, null=True),
        ),
    ]
