# Generated by Django 5.2.5 on 2025-11-17 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0038_remove_sellerrawdata_drop_date_and_more'),
        ('core', '0069_alter_mastercrm_preferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdetails',
            name='trade',
            field=models.ForeignKey(blank=True, help_text='Trade associated with this asset detail', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_details', to='acq_module.trade'),
        ),
    ]
