# Generated by Django 5.2.5 on 2025-11-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_assetdetails_trade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetidhub',
            name='asset_status',
        ),
        migrations.RemoveField(
            model_name='assetidhub',
            name='is_commercial',
        ),
        migrations.AddField(
            model_name='assetdetails',
            name='asset_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('LIQUIDATED', 'Liquidated')], db_index=True, default='ACTIVE', help_text='Canonical lifecycle status for this asset hub (drives UI dropdown and module coordination).', max_length=32),
        ),
        migrations.AddField(
            model_name='assetdetails',
            name='is_commercial',
            field=models.BooleanField(blank=True, help_text='Simple tag: True for commercial assets, False for residential. If blank, inferred at save time.', null=True),
        ),
    ]
