# Generated by Django 5.2.5 on 2025-11-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_remove_assetidhub_asset_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdetails',
            name='servicer_id',
            field=models.CharField(blank=True, db_index=True, help_text='Servicer ID snapshot copied from AssetIdHub.servicer_id for admin/SQL use.', max_length=64, null=True),
        ),
    ]
