# Generated by Django 5.2.5 on 2025-11-18 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_assetdetails_servicer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokermsaassignment',
            name='msa',
            field=models.ForeignKey(blank=True, help_text='MSA market assigned to this broker (optional - can be set later)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker_assignments', to='core.msareference'),
        ),
    ]
