# Generated by Django 5.2.5 on 2025-11-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_brokermsaassignment_msa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetdetails',
            name='servicer_id',
        ),
    ]
