# Generated by Django 5.2.5 on 2025-11-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_remove_assetdetails_servicer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdetails',
            name='legacy_flag',
            field=models.BooleanField(blank=True, db_index=True, help_text='Flag indicating if this asset is a legacy asset', null=True),
        ),
    ]
