# Generated by Django 5.2.5 on 2025-11-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_assetdetails_legacy_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='lltransactionsummary',
            name='realized_gross_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Realized gross cost basis (aggregated actual costs)', max_digits=15, null=True),
        ),
    ]
