# Generated by Django 5.2.5 on 2025-11-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_lltransactionsummary_realized_gross_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='trashout_est_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total estimated trashout costs.', max_digits=15, null=True),
        ),
    ]
