# Generated by Django 5.2.5 on 2025-11-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_valuation_trashout_est_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuation',
            name='recommend_rehab',
            field=models.BooleanField(blank=True, default=False, help_text='Whether to recommend rehabilitation.', null=True),
        ),
    ]
