# Generated by Django 5.2.5 on 2025-11-24 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_alter_valuation_recommend_rehab'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedgerBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bucket name', max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text='Short code for the bucket', max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GL Bucket',
                'verbose_name_plural': 'GL Buckets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneralLedgerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the tag', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'GL Tag',
                'verbose_name_plural': 'GL Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='generalledgerentries',
            name='ai_notes',
            field=models.TextField(blank=True, help_text='AI-generated notes, insights, or suggestions for this GL entry (future AI integration)', null=True),
        ),
        migrations.AddField(
            model_name='generalledgerentries',
            name='asset_hub',
            field=models.ForeignKey(blank=True, help_text='Link to AssetIdHub for robust loan/asset tracking across modules', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_entries', to='core.assetidhub'),
        ),
        migrations.AddField(
            model_name='generalledgerentries',
            name='asset_link',
            field=models.ForeignKey(blank=True, help_text='Link to the canonical Asset/Loan ID Hub for robust tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_entries_link', to='core.assetidhub'),
        ),
        migrations.AddField(
            model_name='generalledgerentries',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this GL entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_entries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalledgerentries',
            name='requires_review',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag indicating this entry requires human review or attention'),
        ),
        migrations.AddField(
            model_name='generalledgerentries',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Notes from review process or reasons for flagging', null=True),
        ),
        migrations.AddField(
            model_name='generalledgerentries',
            name='tag',
            field=models.CharField(blank=True, choices=[('loan_origination', 'Loan Origination'), ('loan_payment', 'Loan Payment'), ('loan_modification', 'Loan Modification'), ('property_acquisition', 'Property Acquisition'), ('property_disposition', 'Property Disposition'), ('operating_expense', 'Operating Expense'), ('capital_expense', 'Capital Expense'), ('interest_income', 'Interest Income'), ('interest_expense', 'Interest Expense'), ('fee_income', 'Fee Income'), ('impairment', 'Impairment'), ('recovery', 'Recovery'), ('adjustment', 'Adjustment'), ('other', 'Other')], db_index=True, help_text='Categorical tag for GL entry type (e.g., Loan Origination, Property Acquisition)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generalledgerentries',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this GL entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_entries_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generalledgerentries',
            name='loan_number',
            field=models.CharField(blank=True, db_index=True, help_text='Loan number associated with this GL entry (legacy field, prefer asset_link)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='recommend_rehab',
            field=models.BooleanField(default=False, help_text='Whether to recommend rehabilitation.'),
        ),
        migrations.AddField(
            model_name='generalledgerentries',
            name='bucket',
            field=models.ForeignKey(blank=True, help_text='Bucket for high-level aggregation and reporting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='core.generalledgerbucket'),
        ),
        migrations.AddField(
            model_name='generalledgerentries',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for flexible categorization', related_name='entries', to='core.generalledgertag'),
        ),
    ]
