# Generated by Django 5.2.5 on 2025-11-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_generalledgerbucket_generalledgertag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledgerentries',
            name='is_legacy_aggregate',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this is a legacy aggregate/summary entry (not a live transaction)'),
        ),
        migrations.AddField(
            model_name='generalledgerentries',
            name='legacy_period',
            field=models.CharField(blank=True, help_text='Period this legacy aggregate represents (e.g., "2023-Q4", "2024-Jan", "Pre-2024")', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generalledgerentries',
            name='legacy_source',
            field=models.CharField(blank=True, help_text='Source system or file for legacy data (e.g., "QuickBooks Export 2023", "Excel Backfill")', max_length=255, null=True),
        ),
    ]
