# Generated by Django 5.2.5 on 2025-11-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_generalledgerentries_is_legacy_aggregate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalledgerentries',
            name='is_legacy_aggregate',
        ),
        migrations.RemoveField(
            model_name='generalledgerentries',
            name='legacy_period',
        ),
        migrations.RemoveField(
            model_name='generalledgerentries',
            name='legacy_source',
        ),
        migrations.AddField(
            model_name='lltransactionsummary',
            name='expense_other_realized',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual other operating expenses', max_digits=15, null=True),
        ),
    ]
