# Generated by Django 5.2.5 on 2025-11-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_remove_generalledgerentries_is_legacy_aggregate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lltransactionsummary',
            old_name='proceeds_realized',
            new_name='gross_liquidation_proceeds_realized',
        ),
        migrations.AddField(
            model_name='lltransactionsummary',
            name='acq_total_realized',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total realized acquisition costs (sum of acq_*_realized)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='lltransactionsummary',
            name='cre_total_realized',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total realized CRE expenses (sum of cre_*_realized)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='lltransactionsummary',
            name='fund_total_realized',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total realized fund-level expenses (sum of fund_*_realized)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='lltransactionsummary',
            name='legal_total_realized',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total realized legal/DIL costs (sum of legal_*_realized)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='lltransactionsummary',
            name='operating_expenses_total_realized',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total realized operating expenses (sum of expense_*_realized)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='lltransactionsummary',
            name='reo_total_realized',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total realized REO expenses (sum of reo_*_realized)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='lltransactionsummary',
            name='total_expenses_realized',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total realized expenses (sum of all realized expense subtotals)', max_digits=15, null=True),
        ),
    ]
