# Generated by Django 5.2.5 on 2025-11-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_rename_proceeds_realized_lltransactionsummary_gross_liquidation_proceeds_realized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetidhub',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetidhub',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
