# Generated by Django 5.2.5 on 2025-11-26 17:09

from django.db import migrations, models
from django.utils import timezone


def _populate_missing_assetdetails_timestamps(apps, schema_editor):
    AssetDetails = apps.get_model('core', 'AssetDetails')
    now = timezone.now()

    AssetDetails.objects.filter(created_at__isnull=True).update(created_at=now)
    AssetDetails.objects.filter(updated_at__isnull=True).update(updated_at=now)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_alter_assetdetails_timestamps_nullable'),
    ]

    operations = [
        migrations.RunPython(
            _populate_missing_assetdetails_timestamps,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
            preserve_default=False,
        ),
    ]
