# Generated by Django 5.2.5 on 2025-11-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_alter_assetdetails_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lltransactionsummary',
            name='rehab_trashout_total_realized',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total realized rehab + trashout costs', max_digits=15, null=True),
        ),
    ]
