# Generated by Django 5.2.5 on 2025-11-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_lltransactionsummary_rehab_trashout_total_realized'),
    ]

    operations = [
        migrations.AddField(
            model_name='lltransactionsummary',
            name='reo_closing_cost_realized',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual REO closing costs (broker + other closing fees)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='lltransactionsummary',
            name='operating_expenses_total_realized',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total realized operating expenses (excludes servicing fees)', max_digits=15, null=True),
        ),
    ]
