# Generated by Django 5.2.5 on 2025-12-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_lltransactionsummary_reo_closing_cost_realized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicer',
            name='is_default_for_trade_assumptions',
            field=models.BooleanField(default=False, help_text='Whether this servicer should be used as the default selection in trade assumptions'),
        ),
    ]
