# Generated by Django 5.2.5 on 2025-12-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_servicer_is_default_for_trade_assumptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_school_district_grade_high',
            field=models.CharField(blank=True, help_text='Highest grade served by the school district.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_school_district_grade_low',
            field=models.CharField(blank=True, help_text='Lowest grade served by the school district (e.g. PK, KG).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_school_district_lea_code',
            field=models.CharField(blank=True, help_text='School district LEA code from Geocodio school field.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_school_district_type',
            field=models.CharField(blank=True, help_text='School district type reported by Geocodio (unified, elementary, secondary).', max_length=32, null=True),
        ),
    ]
