# Generated by Django 5.2.5 on 2025-12-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_lldataenrichment_geocode_school_district_grade_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_block_code',
            field=models.CharField(blank=True, help_text='Census block code from Geocodio census data.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_block_group',
            field=models.CharField(blank=True, help_text='Census block group from Geocodio census data.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_census_source',
            field=models.CharField(blank=True, help_text='Source string from Geocodio census data.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_census_year',
            field=models.CharField(blank=True, help_text='Census year used for Geocodio census data.', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_county_subdivision_class_code',
            field=models.CharField(blank=True, help_text='County subdivision class code from Geocodio census data.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_county_subdivision_class_desc',
            field=models.CharField(blank=True, help_text='County subdivision class description from Geocodio census data.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_county_subdivision_fips',
            field=models.CharField(blank=True, help_text='County subdivision FIPS code from Geocodio census data.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_county_subdivision_name',
            field=models.CharField(blank=True, help_text='County subdivision name from Geocodio census data.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_metdiv_code',
            field=models.CharField(blank=True, help_text='Metropolitan division code from Geocodio census data.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_metdiv_name',
            field=models.CharField(blank=True, help_text='Metropolitan division name from Geocodio census data.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_place_fips',
            field=models.CharField(blank=True, help_text='Place FIPS code from Geocodio census data.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lldataenrichment',
            name='geocode_place_name',
            field=models.CharField(blank=True, help_text='Place name from Geocodio census data.', max_length=255, null=True),
        ),
    ]
