# Generated by Django 5.2.5 on 2025-12-16 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_lldataenrichment_geocode_block_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('trade_import', 'Trade Import'), ('task_changed', 'Task Changed'), ('asset_liquidated', 'Asset Liquidated')], db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('asset_hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='core.assetidhub')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='core.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event_type', 'created_at'], name='core_notifi_event_t_3a1b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['asset_hub', 'created_at'], name='core_notifi_asset_h_a4f001_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationread',
            constraint=models.UniqueConstraint(fields=('notification', 'user'), name='uniq_notification_user'),
        ),
        migrations.AddIndex(
            model_name='notificationread',
            index=models.Index(fields=['user', 'read_at'], name='core_notifi_user_id_1b9f4c_idx'),
        ),
    ]
