# Generated by Django 5.2.5 on 2025-12-16 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_notification_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_event_t_c8a797_idx',
            old_name='core_notifi_event_t_3a1b6d_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_asset_h_8cad96_idx',
            old_name='core_notifi_asset_h_a4f001_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationread',
            new_name='core_notifi_user_id_f2892e_idx',
            old_name='core_notifi_user_id_1b9f4c_idx',
        ),
    ]
