# Generated by Django 5.2.5 on 2025-12-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0092_rename_core_notifi_event_t_3a1b6d_idx_core_notifi_event_t_c8a797_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Visible to all users when true; otherwise private to creator",
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nod_noi", "NOD/NOI"),
                    ("fc_counsel", "FC Counsel"),
                    ("escrow", "Escrow"),
                    ("reo", "REO"),
                ],
                help_text="Standardized follow-up reason",
                max_length=32,
                null=True,
            ),
        ),
    ]
