# Generated by Django 5.2.5 on 2025-12-18 17:10

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_calendarevent_is_public_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerPII',
            fields=[
                ('asset', models.OneToOneField(help_text='Asset this borrower PII belongs to (primary key)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='borrower_pii', serialize=False, to='core.assetidhub')),
                ('borrower1_ssn', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Social Security Number for primary borrower (encrypted)', max_length=11, null=True)),
                ('borrower1_dob', encrypted_fields.fields.EncryptedDateField(blank=True, help_text='Date of birth for primary borrower (encrypted)', null=True)),
                ('borrower1_dod', encrypted_fields.fields.EncryptedDateField(blank=True, help_text='Date of death for primary borrower if applicable (encrypted)', null=True)),
                ('borrower1_phone', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Phone number for primary borrower (encrypted)', max_length=20, null=True)),
                ('borrower2_ssn', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Social Security Number for co-borrower (encrypted)', max_length=11, null=True)),
                ('borrower2_dob', encrypted_fields.fields.EncryptedDateField(blank=True, help_text='Date of birth for co-borrower (encrypted)', null=True)),
                ('borrower2_dod', encrypted_fields.fields.EncryptedDateField(blank=True, help_text='Date of death for co-borrower if applicable (encrypted)', null=True)),
                ('borrower2_phone', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Phone number for co-borrower (encrypted)', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this PII record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this PII record was last modified')),
            ],
            options={
                'verbose_name': 'Borrower PII',
                'verbose_name_plural': 'Borrower PII Records',
                'db_table': 'core_borrower_pii',
                'db_table_comment': 'Encrypted borrower personally identifiable information (SSN, DOB, phone)',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['created_at'], name='borrower_pii_created_idx'), models.Index(fields=['updated_at'], name='borrower_pii_updated_idx')],
            },
        ),
    ]
