# Generated by Django 5.2.5 on 2026-01-08 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0044_servicerloanextract_servicertransactionextract'),
        ('core', '0095_remove_core_borrower_pii_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User assigned to this task (for notifications)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_calendar_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='priority',
            field=models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('routine', 'Routine'), ('low', 'Low')], default='routine', help_text='Priority level for tasks', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='category',
            field=models.CharField(choices=[('realized_liquidation', 'Realized Liquidation'), ('projected_liquidation', 'Projected Liquidation'), ('trade', 'Trade'), ('follow_up', 'Task'), ('milestone', 'Milestone')], db_index=True, default='milestone', help_text='Event category (frontend determines visual styling)', max_length=50),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='date',
            field=models.DateField(db_index=True, help_text='Event date'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='reason',
            field=models.CharField(blank=True, choices=[('follow_up', 'Follow-up'), ('nod_noi', 'NOD/NOI'), ('fc_counsel', 'FC Counsel'), ('escrow', 'Escrow'), ('reo', 'REO'), ('document_review', 'Document Review'), ('contact_borrower', 'Contact Borrower'), ('legal', 'Legal'), ('inspection', 'Inspection'), ('other', 'Other')], help_text='Standardized task reason', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(db_index=True, help_text='Event title/description', max_length=255),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['assigned_to', 'date'], name='core_calend_assigne_142f21_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['asset_hub', 'date'], name='core_calend_asset_h_848923_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['category', 'date'], name='core_calend_categor_48d1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['priority', 'date'], name='core_calend_priorit_d30407_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['is_reminder', 'date'], name='core_calend_is_remi_7da7c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.CheckConstraint(condition=models.Q(('date__gte', '2020-01-01')), name='calendar_event_date_not_too_old'),
        ),
    ]
