# Generated by Django 5.2.5 on 2026-01-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_add_calendar_event_completed_flag'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='core_calend_complet_b41f1a_idx',
            old_name='core_calend_completed_date_idx',
        ),
    ]
