# Generated by Django 5.2.5 on 2026-01-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_rename_core_calend_completed_date_idx_core_calend_complet_b41f1a_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Event title/description (optional - events tagged by category)', max_length=255),
        ),
    ]
