# Generated by Django 5.2.5 on 2026-01-09 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0044_servicerloanextract_servicertransactionextract'),
        ('core', '0099_alter_calendarevent_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='calendarevent',
            name='core_calend_categor_48d1d0_idx',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='category',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='reason',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='task_type',
            field=models.CharField(choices=[('follow_up', 'Follow-up'), ('nod_noi', 'NOD/NOI'), ('fc_counsel', 'FC Counsel'), ('escrow', 'Escrow'), ('reo', 'REO'), ('document_review', 'Document Review'), ('contact_borrower', 'Contact Borrower'), ('legal', 'Legal'), ('inspection', 'Inspection'), ('other', 'Other')], db_index=True, default='follow_up', help_text='Type of task', max_length=50),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['task_type', 'date'], name='core_calend_task_ty_f8a80b_idx'),
        ),
    ]
