# Generated by Django 5.2.5 on 2026-01-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_simplify_calendar_event_to_tasks_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdetails',
            name='asset_class',
            field=models.CharField(blank=True, choices=[('NPL', 'NPL'), ('REO', 'REO'), ('PERFORMING', 'Performing')], db_index=True, help_text='High-level asset classification (NPL, REO, Performing).', max_length=32, null=True),
        ),
    ]
