# Generated by Django 5.2.5 on 2025-09-17 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acq_module', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerdocument',
            name='asset_hub',
            field=models.ForeignKey(blank=True, help_text='Stable hub ID (from broker_valuation.seller_raw_data.asset_hub).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_documents', to='core.assetidhub'),
        ),
        migrations.AddField(
            model_name='brokervalues',
            name='asset_hub',
            field=models.OneToOneField(blank=True, help_text='TEMP: nullable during staged migration; will be PK in next migration.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='broker_values', to='core.assetidhub'),
        ),
        migrations.AddField(
            model_name='brokerdocument',
            name='broker_valuation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='acq_module.brokervalues'),
        ),
        migrations.AddField(
            model_name='internalvaluation',
            name='asset_hub',
            field=models.OneToOneField(blank=True, help_text='TEMP: nullable during staged migration; will be PK in next migration.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internal_valuation', to='core.assetidhub'),
        ),
        migrations.AddField(
            model_name='photo',
            name='asset_hub',
            field=models.ForeignKey(blank=True, help_text='Stable hub ID for this photo (from seller_raw_data.asset_hub).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_photos', to='core.assetidhub'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['name'], name='acq_module__name_aea276_idx'),
        ),
        migrations.AddField(
            model_name='sellerrawdata',
            name='asset_hub',
            field=models.OneToOneField(blank=True, help_text='One hub per asset; one raw row per hub (set during ETL).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acq_raw', to='core.assetidhub'),
        ),
        migrations.AddField(
            model_name='sellerrawdata',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_raw_data', to='acq_module.seller'),
        ),
        migrations.AddField(
            model_name='photo',
            name='seller_raw_data',
            field=models.ForeignKey(help_text='SellerRawData record this photo belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='acq_module.sellerrawdata'),
        ),
        migrations.AddField(
            model_name='loanlevelassumption',
            name='seller_raw_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_assumptions', to='acq_module.sellerrawdata'),
        ),
        migrations.AddField(
            model_name='trade',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='acq_module.seller'),
        ),
        migrations.AddField(
            model_name='sellerrawdata',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_raw_data', to='acq_module.trade'),
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_assumptions', to='acq_module.trade'),
        ),
        migrations.AddIndex(
            model_name='brokerdocument',
            index=models.Index(fields=['broker_valuation'], name='acq_broker__broker__caad64_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['seller_raw_data'], name='acq_photo_seller__ed789e_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['source_tag'], name='acq_photo_source__ceca6b_idx'),
        ),
        migrations.AddIndex(
            model_name='loanlevelassumption',
            index=models.Index(fields=['seller_raw_data'], name='loan_level__seller__1ecd72_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['seller'], name='acq_module__seller__17bbd4_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerrawdata',
            index=models.Index(fields=['id'], name='acq_module__id_9f5dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerrawdata',
            index=models.Index(fields=['asset_status'], name='acq_module__asset_s_58e584_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerrawdata',
            index=models.Index(fields=['seller'], name='acq_module__seller__bcce23_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerrawdata',
            index=models.Index(fields=['trade'], name='acq_module__trade_i_6d8159_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerrawdata',
            index=models.Index(fields=['state'], name='acq_module__state_2f12db_idx'),
        ),
        migrations.AddIndex(
            model_name='tradelevelassumption',
            index=models.Index(fields=['trade'], name='trade_level_trade_i_ee4dcc_idx'),
        ),
    ]
