# Generated by Django 5.2.5 on 2026-01-31 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0001_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcqAsset',
            fields=[
                ('asset_hub', models.OneToOneField(help_text="1:1 with hub; this model's PK equals the hub ID.", on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='acq_asset', serialize=False, to='core.assetidhub')),
                ('asset_status', models.CharField(blank=True, choices=[('NPL', 'NPL'), ('REO', 'REO'), ('PERF', 'PERF'), ('RPL', 'RPL')], max_length=100, null=True)),
                ('acq_status', models.CharField(choices=[('KEEP', 'Keep'), ('DROP', 'Drop')], db_index=True, default='KEEP', help_text='Asset-level status: KEEP (in active pool) or DROP (excluded).', max_length=20)),
                ('asset_class', models.CharField(blank=True, choices=[('REAL_ESTATE_1_4', 'Real Estate 1-4'), ('MULTIFAMILY_5_PLUS', 'Multifamily 5+'), ('COMMERCIAL', 'Commercial'), ('PERFORMING_NOTE', 'Performing Note'), ('NPL', 'NPL')], help_text='Primary asset class (Real Estate 1-4, Multifamily 5+, Commercial, Performing Note, NPL).', max_length=30, null=True)),
                ('real_estate_subclass_type', models.CharField(blank=True, choices=[('SFR', 'Single Family'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('2-4 Family', '2-4 Family'), ('Manufactured', 'Manufactured'), ('Land', 'Land')], help_text='Subtype for Real Estate 1-4 assets (only when asset_class=REAL_ESTATE_1_4).', max_length=20, null=True)),
                ('multifamily_subclass_type', models.CharField(blank=True, choices=[('Garden', 'Garden'), ('Mid-Rise', 'Mid-Rise'), ('High-Rise', 'High-Rise'), ('Student', 'Student Housing'), ('Senior', 'Senior Housing'), ('Affordable', 'Affordable Housing')], help_text='Subtype for Multifamily 5+ assets (only when asset_class=MULTIFAMILY_5_PLUS).', max_length=20, null=True)),
                ('commercial_subclass_type', models.CharField(blank=True, choices=[('Office', 'Office'), ('Retail', 'Retail'), ('Industrial', 'Industrial'), ('Mixed Use', 'Mixed Use'), ('Storage', 'Storage'), ('Hospitality', 'Hospitality'), ('Healthcare', 'Healthcare')], help_text='Subtype for Commercial assets (only when asset_class=COMMERCIAL).', max_length=20, null=True)),
                ('note_subclass_type', models.CharField(blank=True, choices=[('NPL', 'NPL'), ('PERF', 'PERF'), ('RPL', 'RPL')], help_text='Subclass for note assets (only when asset_class=PERFORMING_NOTE or NPL).', max_length=10, null=True)),
                ('as_of_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(blank=True, help_text='Nullable reference for assets without a seller.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acq_assets', to='acq_module.seller')),
                ('trade', models.ForeignKey(blank=True, help_text='Nullable reference for assets not tied to a deal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acq_assets', to='acq_module.trade')),
            ],
            options={
                'verbose_name': 'Acquisition Asset',
                'verbose_name_plural': 'Acquisition Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcqForeclosureTimeline',
            fields=[
                ('asset', models.OneToOneField(help_text='1:1 link to acquisition asset.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='foreclosure_timeline', serialize=False, to='acq_module.acqasset')),
                ('fc_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('fc_first_legal_date', models.DateField(blank=True, null=True)),
                ('fc_referred_date', models.DateField(blank=True, null=True)),
                ('fc_judgement_date', models.DateField(blank=True, null=True)),
                ('fc_scheduled_sale_date', models.DateField(blank=True, null=True)),
                ('fc_sale_date', models.DateField(blank=True, null=True)),
                ('fc_starting', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Acquisition Foreclosure Timeline',
                'verbose_name_plural': 'Acquisition Foreclosure Timelines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcqLoan',
            fields=[
                ('asset', models.OneToOneField(help_text='1:1 link to acquisition asset.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='loan', serialize=False, to='acq_module.acqasset')),
                ('sellertape_id', models.CharField(max_length=100)),
                ('sellertape_altid', models.CharField(blank=True, max_length=100, null=True)),
                ('borrower1_last', models.CharField(blank=True, help_text='If entity, put entity in borrower1_last.', max_length=100, null=True)),
                ('borrower1_first', models.CharField(blank=True, max_length=100, null=True)),
                ('borrower2_last', models.CharField(blank=True, max_length=100, null=True)),
                ('borrower2_first', models.CharField(blank=True, max_length=100, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('deferred_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('last_paid_date', models.DateField(blank=True, null=True)),
                ('first_pay_date', models.DateField(blank=True, null=True)),
                ('origination_date', models.DateField(blank=True, null=True)),
                ('original_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('original_term', models.IntegerField(blank=True, null=True)),
                ('original_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('original_maturity_date', models.DateField(blank=True, null=True)),
                ('origination_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('origination_arv', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('origination_value_date', models.DateField(blank=True, null=True)),
                ('default_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('months_dlq', models.IntegerField(blank=True, null=True)),
                ('current_maturity_date', models.DateField(blank=True, null=True)),
                ('current_term', models.IntegerField(blank=True, null=True)),
                ('accrued_note_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('accrued_default_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('escrow_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('escrow_advance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('recoverable_corp_advance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('late_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('other_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('suspense_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('product_type', models.CharField(blank=True, choices=[('BPL', 'BPL'), ('HECM', 'HECM'), ('VA', 'VA'), ('Conv', 'Conv'), ('Commercial', 'Commercial'), ('Bridge', 'Bridge')], max_length=50, null=True)),
                ('bk_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('bk_chapter', models.CharField(blank=True, max_length=10, null=True)),
                ('mod_flag', models.BooleanField(default=False)),
                ('mod_date', models.DateField(blank=True, null=True)),
                ('mod_maturity_date', models.DateField(blank=True, null=True)),
                ('mod_term', models.IntegerField(blank=True, null=True)),
                ('mod_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('mod_initial_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Acquisition Loan',
                'verbose_name_plural': 'Acquisition Loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcqProperty',
            fields=[
                ('asset', models.OneToOneField(help_text='1:1 link to acquisition asset.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='property', serialize=False, to='acq_module.acqasset')),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=100, null=True)),
                ('occupancy', models.CharField(blank=True, choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied'), ('Unknown', 'Unknown')], default='Unknown', max_length=100, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('sq_ft', models.IntegerField(blank=True, null=True)),
                ('lot_size', models.IntegerField(blank=True, null=True)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('baths', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Acquisition Property',
                'verbose_name_plural': 'Acquisition Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SellerRawData',
        ),
        migrations.AddIndex(
            model_name='acqforeclosuretimeline',
            index=models.Index(fields=['asset'], name='acq_module__asset_i_5f38e3_idx'),
        ),
        migrations.AddIndex(
            model_name='acqloan',
            index=models.Index(fields=['asset'], name='acq_module__asset_i_1b7bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='acqloan',
            index=models.Index(fields=['product_type'], name='acq_module__product_a42cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='acqproperty',
            index=models.Index(fields=['asset'], name='acq_module__asset_i_244c70_idx'),
        ),
        migrations.AddIndex(
            model_name='acqproperty',
            index=models.Index(fields=['state'], name='acq_module__state_f120c6_idx'),
        ),
        migrations.AddIndex(
            model_name='acqasset',
            index=models.Index(fields=['asset_hub'], name='acq_module__asset_h_b1e5f3_idx'),
        ),
        migrations.AddIndex(
            model_name='acqasset',
            index=models.Index(fields=['acq_status'], name='acq_module__acq_sta_e5bab7_idx'),
        ),
        migrations.AddIndex(
            model_name='acqasset',
            index=models.Index(fields=['asset_class'], name='acq_module__asset_c_4dfad8_idx'),
        ),
        migrations.AddIndex(
            model_name='acqasset',
            index=models.Index(fields=['asset_status'], name='acq_module__asset_s_1cb5fa_idx'),
        ),
        migrations.AddIndex(
            model_name='acqasset',
            index=models.Index(fields=['seller'], name='acq_module__seller__ce4f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='acqasset',
            index=models.Index(fields=['trade'], name='acq_module__trade_i_b01c41_idx'),
        ),
    ]
