# Generated by Django 5.2.5 on 2026-01-31 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0002_acqasset_acqforeclosuretimeline_acqloan_acqproperty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcqBankruptcy',
            fields=[
                ('loan', models.OneToOneField(help_text='1:1 link to acquisition loan.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bankruptcy', serialize=False, to='acq_module.acqloan')),
                ('bk_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('bk_chapter', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Acquisition Bankruptcy',
                'verbose_name_plural': 'Acquisition Bankruptcies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcqModification',
            fields=[
                ('loan', models.OneToOneField(help_text='1:1 link to acquisition loan.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='modification', serialize=False, to='acq_module.acqloan')),
                ('mod_flag', models.BooleanField(default=False)),
                ('mod_date', models.DateField(blank=True, null=True)),
                ('mod_maturity_date', models.DateField(blank=True, null=True)),
                ('mod_term', models.IntegerField(blank=True, null=True)),
                ('mod_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('mod_initial_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Acquisition Modification',
                'verbose_name_plural': 'Acquisition Modifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Trade_Deal',
        ),
        migrations.RemoveField(
            model_name='acqloan',
            name='bk_chapter',
        ),
        migrations.RemoveField(
            model_name='acqloan',
            name='bk_flag',
        ),
        migrations.RemoveField(
            model_name='acqloan',
            name='mod_date',
        ),
        migrations.RemoveField(
            model_name='acqloan',
            name='mod_flag',
        ),
        migrations.RemoveField(
            model_name='acqloan',
            name='mod_initial_balance',
        ),
        migrations.RemoveField(
            model_name='acqloan',
            name='mod_maturity_date',
        ),
        migrations.RemoveField(
            model_name='acqloan',
            name='mod_rate',
        ),
        migrations.RemoveField(
            model_name='acqloan',
            name='mod_term',
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('PASS', 'Pass'), ('INDICATIVE', 'Indicative'), ('DD', 'Due Diligence'), ('AWARDED', 'Awarded'), ('CLOSED', 'Closed'), ('BOARD', 'Boarded')], db_index=True, default='INDICATIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='acqbankruptcy',
            index=models.Index(fields=['loan'], name='acq_module__loan_id_9a9bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='acqbankruptcy',
            index=models.Index(fields=['bk_flag'], name='acq_module__bk_flag_7a4610_idx'),
        ),
        migrations.AddIndex(
            model_name='acqmodification',
            index=models.Index(fields=['loan'], name='acq_module__loan_id_b1e1c2_idx'),
        ),
        migrations.AddIndex(
            model_name='acqmodification',
            index=models.Index(fields=['mod_flag'], name='acq_module__mod_fla_1e8040_idx'),
        ),
    ]
