# Generated by Django 5.2 on 2025-09-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='broker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='poc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
