# Generated by Django 5.2 on 2025-09-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0003_alter_seller_broker_alter_seller_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerrawdata',
            name='accrued_default_interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='accrued_note_interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='additional_arv_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='additional_asis_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='additional_value_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='as_of_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='asset_status',
            field=models.CharField(blank=True, choices=[('NPL', 'NPL'), ('REO', 'REO'), ('PERF', 'PERF'), ('RPL', 'RPL')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='bk_flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='current_maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='current_term',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='default_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='deferred_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='escrow_advance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='escrow_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='fc_flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='first_pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='last_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='late_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='original_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='original_maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='original_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='original_term',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='origination_arv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='origination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='origination_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='origination_value_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='other_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='recoverable_corp_advance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='seller_arv_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='seller_asis_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='seller_value_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='suspense_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
