# Generated by Django 5.2.5 on 2025-10-01 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0004_alter_sellerrawdata_accrued_default_interest_and_more'),
        ('core', '0007_rename_acq_due_diligence_llcashflowseries_acq_due_diligence_expenses_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sellerrawdata',
            name='acq_module__id_9f5dd7_idx',
        ),
        migrations.RemoveField(
            model_name='sellerrawdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='asset_hub',
            field=models.OneToOneField(default=1, help_text="1:1 with hub; this model's PK equals the hub ID.", on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='acq_raw', serialize=False, to='core.assetidhub'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='sellerrawdata',
            index=models.Index(fields=['asset_hub'], name='acq_module__asset_h_39657d_idx'),
        ),
    ]
