# Generated by Django 5.2.5 on 2025-08-22 02:07

import acq_module.models.valuations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0005_internalvaluation_appliances_est_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokervalues',
            name='broker_rehab_est',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='brokerphoto',
            name='photo',
            field=models.ImageField(upload_to=acq_module.models.valuations.get_broker_photo_path),
        ),
        migrations.AlterField(
            model_name='brokervalues',
            name='broker_arv_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='brokervalues',
            name='broker_asis_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='brokervalues',
            name='broker_value_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
