# Generated by Django 5.2.5 on 2025-10-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0005_remove_sellerrawdata_acq_module__id_9f5dd7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticModelAssumptions',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('version_name', models.CharField(default='Default', help_text='Version name for tracking assumption changes', max_length=100)),
                ('perf_rpl_hold_period', models.IntegerField(help_text='Default hold period for performing/re-performing loans (months)')),
                ('mod_rate', models.DecimalField(decimal_places=4, help_text='Default modification interest rate', max_digits=6)),
                ('mod_legal_term', models.IntegerField(help_text='Default modification legal term in months')),
                ('mod_amort_term', models.IntegerField(help_text='Default modification amortization term in months')),
                ('max_mod_ltv', models.DecimalField(decimal_places=4, help_text='Maximum loan-to-value ratio for modifications (e.g., 0.95 for 95%)', max_digits=6)),
                ('mod_io_flag', models.BooleanField(default=False, help_text='Default IO (interest-only) flag for modifications')),
                ('mod_down_pmt', models.DecimalField(decimal_places=4, help_text='Default modification down payment percentage', max_digits=6)),
                ('mod_orig_cost', models.DecimalField(decimal_places=4, help_text='Default modification original cost percentage', max_digits=6)),
                ('mod_setup', models.DecimalField(decimal_places=4, help_text='Default modification setup cost percentage', max_digits=6)),
                ('mod_hold', models.IntegerField(help_text='Default modification hold period in months')),
                ('acq_legal_cost', models.DecimalField(decimal_places=4, help_text='Default acquisition legal cost percentage', max_digits=6)),
                ('acq_dd_cost', models.DecimalField(decimal_places=4, help_text='Default acquisition due diligence cost percentage', max_digits=6)),
                ('acq_tax_title_cost', models.DecimalField(decimal_places=4, help_text='Default acquisition tax title cost percentage', max_digits=6)),
                ('am_fee_pct', models.DecimalField(decimal_places=4, help_text='Default AM fee percentage', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Static Model Assumptions (Settings)',
                'verbose_name_plural': 'Static Model Assumptions (Settings)',
                'db_table': 'static_model_assumptions',
            },
        ),
        migrations.RemoveField(
            model_name='tradelevelassumption',
            name='mod_balance',
        ),
        migrations.RemoveField(
            model_name='tradelevelassumption',
            name='mod_date',
        ),
        migrations.RemoveField(
            model_name='tradelevelassumption',
            name='mod_maturity_date',
        ),
        migrations.RemoveField(
            model_name='tradelevelassumption',
            name='mod_rate',
        ),
        migrations.RemoveField(
            model_name='tradelevelassumption',
            name='mod_term',
        ),
        migrations.RemoveField(
            model_name='tradelevelassumption',
            name='perf_rpl_hold_period',
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='bid_date',
            field=models.DateField(help_text='Date the bid was submitted'),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='discount_rate',
            field=models.DecimalField(decimal_places=4, help_text='Discount rate for NPV calculations (can override static default)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='pctUPB',
            field=models.DecimalField(decimal_places=2, help_text='Purchase price as percentage of UPB', max_digits=15),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='servicing_transfer_date',
            field=models.DateField(blank=True, help_text='Date servicing transfers to new servicer', null=True),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='settlement_date',
            field=models.DateField(help_text='Expected or actual settlement date'),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='target_irr',
            field=models.DecimalField(decimal_places=4, help_text='Target internal rate of return for this trade', max_digits=6),
        ),
        migrations.AddIndex(
            model_name='tradelevelassumption',
            index=models.Index(fields=['bid_date'], name='trade_level_bid_dat_8ae0de_idx'),
        ),
    ]
