# Generated by Django 5.2.5 on 2025-10-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0006_staticmodelassumptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelevelassumption',
            name='acq_dd_cost',
            field=models.DecimalField(decimal_places=4, default=0.003, help_text='Acquisition due diligence cost percentage', max_digits=6),
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='acq_legal_cost',
            field=models.DecimalField(decimal_places=4, default=0.005, help_text='Acquisition legal cost percentage', max_digits=6),
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='acq_tax_title_cost',
            field=models.DecimalField(decimal_places=4, default=0.002, help_text='Acquisition tax/title cost percentage', max_digits=6),
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='am_fee_pct',
            field=models.DecimalField(decimal_places=4, default=0.01, help_text='AM fee percentage', max_digits=6),
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='max_mod_ltv',
            field=models.DecimalField(decimal_places=4, default=0.95, help_text='Maximum LTV for modifications', max_digits=6),
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='mod_amort_term',
            field=models.IntegerField(default=360, help_text='Modification amortization term in months'),
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='mod_down_pmt',
            field=models.DecimalField(decimal_places=4, default=0.05, help_text='Modification down payment percentage', max_digits=6),
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='mod_hold_duration',
            field=models.IntegerField(default=6, help_text='Modification hold duration in months'),
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='mod_io_flag',
            field=models.BooleanField(default=False, help_text='IO (interest-only) flag for modifications'),
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='mod_legal_term',
            field=models.IntegerField(default=360, help_text='Modification legal term in months'),
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='mod_orig_cost',
            field=models.DecimalField(decimal_places=4, default=0.02, help_text='Modification origination cost percentage', max_digits=6),
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='mod_rate',
            field=models.DecimalField(decimal_places=4, default=0.04, help_text='Modification interest rate', max_digits=6),
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='mod_setup_duration',
            field=models.IntegerField(default=6, help_text='Modification setup duration in months'),
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='perf_rpl_hold_period',
            field=models.IntegerField(default=12, help_text='Hold period for performing/re-performing loans (months)'),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='discount_rate',
            field=models.DecimalField(decimal_places=4, default=0.12, help_text='Discount rate for NPV calculations', max_digits=6),
        ),
    ]
