# Generated by Django 5.2 on 2025-08-22 04:45

import acq_module.models.valuations
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0006_brokervalues_broker_rehab_est_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerphoto',
            name='photo',
            field=models.ImageField(upload_to=acq_module.models.valuations.get_broker_photo_path),
        ),
        migrations.CreateModel(
            name='BrokerInviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Opaque invite token used in public URL.', max_length=64, unique=True)),
                ('broker_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('broker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField(help_text='When this invite token expires.')),
                ('single_use', models.BooleanField(default=True, help_text='If true, lock after first successful submit.')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the token was first used to submit values.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('seller_raw_data', models.ForeignKey(help_text='SellerRawData row this invite is for.', on_delete=django.db.models.deletion.CASCADE, related_name='broker_invites', to='acq_module.sellerrawdata')),
            ],
            options={
                'verbose_name': 'Broker Invite Token',
                'verbose_name_plural': 'Broker Invite Tokens',
                'db_table': 'acq_broker_invite_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller_raw_data'], name='acq_broker__seller__4d70bd_idx'), models.Index(fields=['expires_at'], name='acq_broker__expires_ce6fd0_idx')],
            },
        ),
    ]
