# Generated by Django 5.2 on 2025-10-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0007_tradelevelassumption_acq_dd_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradelevelassumption',
            name='am_fee_pct',
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='am_fee_per_loan',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Asset management fee in dollars per loan per month', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='acq_dd_cost',
            field=models.DecimalField(decimal_places=2, default=150.0, help_text='Acquisition due diligence cost in dollars per loan', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='acq_legal_cost',
            field=models.DecimalField(decimal_places=2, default=300.0, help_text='Acquisition legal cost in dollars per loan', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='acq_tax_title_cost',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Acquisition tax/title cost in dollars per loan', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='max_mod_ltv',
            field=models.DecimalField(decimal_places=4, default=0.95, help_text='Maximum LTV for modifications as decimal (e.g., 0.95 = 95%)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='mod_down_pmt',
            field=models.DecimalField(decimal_places=4, default=0.05, help_text='Modification down payment as decimal (e.g., 0.05 = 5%)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='mod_orig_cost',
            field=models.DecimalField(decimal_places=4, default=0.02, help_text='Modification origination cost as decimal (e.g., 0.02 = 2%)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='mod_rate',
            field=models.DecimalField(decimal_places=4, default=0.04, help_text='Modification interest rate as decimal (e.g., 0.04 = 4%)', max_digits=6),
        ),
    ]
