# Generated by Django 5.2.5 on 2025-10-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0008_remove_tradelevelassumption_am_fee_pct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradelevelassumption',
            name='am_fee_per_loan',
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='am_fee_pct',
            field=models.DecimalField(decimal_places=4, default=0.01, help_text='Asset management fee as decimal (e.g., 0.01 = 1%)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='mod_orig_cost',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Modification origination cost in dollars per loan', max_digits=10),
        ),
    ]
