# Generated by Django 5.2.5 on 2025-08-22 04:54

import acq_module.models.valuations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0008_rename_brokerinvitetoken_to_brokercrm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerphoto',
            name='photo',
            field=models.ImageField(upload_to=acq_module.models.valuations.get_broker_photo_path),
        ),
    ]
