# Generated by Django 5.2.5 on 2025-08-22 17:03

import acq_module.models.valuations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0009_alter_brokerphoto_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brokercrm',
            old_name='broker_msa',
            new_name='broker_city',
        ),
        migrations.AlterField(
            model_name='brokerphoto',
            name='photo',
            field=models.ImageField(upload_to=acq_module.models.valuations.get_broker_photo_path),
        ),
    ]
