# Generated by Django 5.2.5 on 2025-10-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0009_remove_tradelevelassumption_am_fee_per_loan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerrawdata',
            name='product_type',
            field=models.CharField(blank=True, choices=[('BPL', 'BPL'), ('HECM', 'HECM'), ('VA', 'VA'), ('Conv', 'Conv'), ('Commercial', 'Commercial')], max_length=50, null=True),
        ),
    ]
