# Generated by Django 5.2.5 on 2025-10-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0010_sellerrawdata_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerrawdata',
            name='property_type',
            field=models.CharField(blank=True, choices=[('SFR', 'SFR'), ('Manufactured', 'Manufactured'), ('Condo', 'Condo'), ('2-4 Family', '2-4 Family'), ('Land', 'Land'), ('Multifamily 5+', 'Multifamily 5+'), ('Industrial', 'Industrial'), ('Mixed Use', 'Mixed Use'), ('Storage', 'Storage')], default='SFR', max_length=100, null=True),
        ),
    ]
