# Generated by Django 5.2 on 2025-08-22 17:25

import acq_module.models.valuations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0010_rename_broker_msa_brokercrm_broker_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerphoto',
            name='photo',
            field=models.ImageField(upload_to=acq_module.models.valuations.get_broker_photo_path),
        ),
    ]
