# Generated by Django 5.2.5 on 2025-08-22 17:34

import acq_module.models.valuations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0011_alter_brokerphoto_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokercrm',
            options={'ordering': ['-created_at'], 'verbose_name': 'Broker', 'verbose_name_plural': 'Brokers'},
        ),
        migrations.RemoveIndex(
            model_name='brokercrm',
            name='acq_broker__seller__4d70bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='brokercrm',
            name='acq_broker__expires_ce6fd0_idx',
        ),
        migrations.RemoveField(
            model_name='brokercrm',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='brokercrm',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='brokercrm',
            name='seller_raw_data',
        ),
        migrations.RemoveField(
            model_name='brokercrm',
            name='single_use',
        ),
        migrations.RemoveField(
            model_name='brokercrm',
            name='token',
        ),
        migrations.RemoveField(
            model_name='brokercrm',
            name='used_at',
        ),
        migrations.AlterField(
            model_name='brokerphoto',
            name='photo',
            field=models.ImageField(upload_to=acq_module.models.valuations.get_broker_photo_path),
        ),
        migrations.AddIndex(
            model_name='brokercrm',
            index=models.Index(fields=['broker_state'], name='acq_broker__broker__472f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='brokercrm',
            index=models.Index(fields=['broker_email'], name='acq_broker__broker__31921e_idx'),
        ),
    ]
