# Generated by Django 5.2.5 on 2025-10-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0011_alter_sellerrawdata_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerrawdata',
            name='sellertape_altid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='sellertape_id',
            field=models.CharField(max_length=100),
        ),
    ]
