# Generated by Django 5.2.5 on 2025-08-22 17:38

import acq_module.models.valuations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0012_alter_brokercrm_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='brokercrm',
            new_name='brokercrm_broker__9a0b1f_idx',
            old_name='acq_broker__broker__472f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='brokercrm',
            new_name='brokercrm_broker__fe2cb8_idx',
            old_name='acq_broker__broker__31921e_idx',
        ),
        migrations.AlterField(
            model_name='brokerphoto',
            name='photo',
            field=models.ImageField(upload_to=acq_module.models.valuations.get_broker_photo_path),
        ),
        migrations.AlterModelTable(
            name='brokercrm',
            table='brokercrm',
        ),
    ]
