# Generated by Django 5.2.5 on 2025-10-07 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0012_alter_sellerrawdata_sellertape_altid_and_more'),
        ('core', '0018_rename_gross_rent_revenue_historicalpropertycashflow_gross_potential_rent_revenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelevelassumption',
            name='servicer',
            field=models.ForeignKey(blank=True, help_text='Selected servicing company for this trade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_level_assumptions', to='core.servicer'),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='property_type',
            field=models.CharField(blank=True, choices=[('SFR', 'SFR'), ('Manufactured', 'Manufactured'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('2-4 Family', '2-4 Family'), ('Land', 'Land'), ('Multifamily 5+', 'Multifamily 5+'), ('Industrial', 'Industrial'), ('Mixed Use', 'Mixed Use'), ('Storage', 'Storage')], default='SFR', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='tradelevelassumption',
            index=models.Index(fields=['servicer'], name='trade_level_service_444dc7_idx'),
        ),
    ]
