# Generated by Django 5.2.5 on 2025-08-25 18:02

import acq_module.models.valuations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0013_rename_acq_broker__broker__472f2d_idx_brokercrm_broker__9a0b1f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerphoto',
            name='photo',
            field=models.ImageField(upload_to=acq_module.models.valuations.get_broker_photo_path),
        ),
    ]
