# Generated by Django 5.2.5 on 2025-10-10 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0013_tradelevelassumption_servicer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerrawdata',
            name='drop_date',
            field=models.DateTimeField(blank=True, help_text='When asset was dropped', null=True),
        ),
        migrations.AddField(
            model_name='sellerrawdata',
            name='drop_reason',
            field=models.CharField(blank=True, help_text='Reason for dropping asset', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerrawdata',
            name='dropped_by',
            field=models.ForeignKey(blank=True, help_text='User who dropped the asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropped_acq_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerrawdata',
            name='is_dropped',
            field=models.BooleanField(default=False, help_text='Asset dropped from active bidding list'),
        ),
    ]
