# Generated by Django 5.2.5 on 2025-10-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0015_alter_sellerrawdata_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
