# Generated by Django 5.2.5 on 2025-08-26 22:48

import acq_module.models.valuations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0016_unify_photos_and_broker_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokerphoto',
            name='broker_valuation',
        ),
        migrations.RemoveField(
            model_name='documentphoto',
            name='seller_raw_data',
        ),
        migrations.RemoveField(
            model_name='publicphoto',
            name='seller_raw_data',
        ),
        migrations.RenameIndex(
            model_name='photo',
            new_name='acq_photo_seller__ed789e_idx',
            old_name='acq_photo_seller_idx',
        ),
        migrations.RenameIndex(
            model_name='photo',
            new_name='acq_photo_source__ceca6b_idx',
            old_name='acq_photo_source_tag_idx',
        ),
        migrations.AlterField(
            model_name='brokerdocument',
            name='file',
            field=models.FileField(upload_to=acq_module.models.valuations.get_broker_document_path),
        ),
        migrations.AddIndex(
            model_name='brokerdocument',
            index=models.Index(fields=['broker_valuation'], name='acq_broker__broker__caad64_idx'),
        ),
        migrations.DeleteModel(
            name='BrokerPhoto',
        ),
        migrations.DeleteModel(
            name='DocumentPhoto',
        ),
        migrations.DeleteModel(
            name='PublicPhoto',
        ),
    ]
