# Generated by Django 5.2 on 2025-10-16 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0016_alter_trade_trade_name'),
        ('core', '0022_remove_mastercrm_core_master_state_717dd6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerrawdata',
            name='is_dropped',
        ),
        migrations.AddField(
            model_name='sellerrawdata',
            name='acq_status',
            field=models.CharField(choices=[('PASS', 'Pass'), ('DD', 'Due Diligence'), ('DROP', 'Drop'), ('AWARDED', 'Awarded'), ('BOARD', 'Boarded')], db_index=True, default='PASS', help_text='Acquisition lifecycle status (Pass, DD, Drop, Awarded, Board).', max_length=20),
        ),
        migrations.AddIndex(
            model_name='sellerrawdata',
            index=models.Index(fields=['acq_status'], name='acq_module__acq_sta_5e53c5_idx'),
        ),
    ]
