# Generated by Django 5.2.5 on 2025-10-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0017_remove_sellerrawdata_is_dropped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('PASS', 'Pass'), ('DD', 'Due Diligence'), ('AWARDED', 'Awarded'), ('BOARD', 'Boarded'), ('ARCHIVE', 'Archive')], db_index=True, default='DD', max_length=20),
        ),
    ]
