# Generated by Django 5.2.5 on 2025-08-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0017_remove_brokerphoto_broker_valuation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokervalues',
            name='broker_links',
            field=models.URLField(blank=True, null=True),
        ),
    ]
