# Generated by Django 5.2.5 on 2025-10-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0019_alter_trade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('PASS', 'Pass'), ('INDICATIVE', 'Indicative'), ('DD', 'Due Diligence'), ('AWARDED', 'Awarded'), ('BOARD', 'Boarded')], db_index=True, default='INDICATIVE', max_length=20),
        ),
    ]
