# Generated by Django 5.2 on 2025-08-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0019_trade_created_at_trade_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellerrawdata',
            unique_together=set(),
        ),
    ]
