# Generated by Django 5.2 on 2025-08-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0020_alter_sellerrawdata_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statereference',
            name='value_adjustment_annual',
            field=models.DecimalField(decimal_places=4, help_text='Average value adjustment', max_digits=10),
        ),
    ]
