# Generated by Django 5.2 on 2025-10-28 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0020_alter_trade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerrawdata',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_raw_data', to='acq_module.seller'),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_raw_data', to='acq_module.trade'),
        ),
    ]
