# Generated by Django 5.2.5 on 2025-08-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0021_alter_statereference_value_adjustment_annual'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerrawdata',
            name='occupancy',
            field=models.CharField(choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied'), ('Unknown', 'Unknown')], default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='sellerrawdata',
            name='property_type',
            field=models.CharField(choices=[('SFR', 'SFR'), ('Manufactured', 'Manufactured'), ('Condo', 'Condo'), ('2-4 Family', '2-4 Family'), ('Land', 'Land'), ('Multifamily 5+', 'Multifamily 5+')], default='SFR', max_length=100),
        ),
    ]
