# Generated by Django 5.2 on 2025-10-28 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0021_alter_sellerrawdata_seller_alter_sellerrawdata_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerrawdata',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Nullable reference so Seller deletions preserve this raw row.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_raw_data', to='acq_module.seller'),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='trade',
            field=models.ForeignKey(blank=True, help_text='Nullable reference so Trade deletions keep the raw asset record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_raw_data', to='acq_module.trade'),
        ),
    ]
