# Generated by Django 5.2 on 2025-10-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0022_alter_sellerrawdata_seller_alter_sellerrawdata_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerrawdata',
            name='acq_status',
            field=models.CharField(choices=[('PASS', 'Pass'), ('DD', 'Due Diligence'), ('DROP', 'Drop'), ('AWARDED', 'Awarded'), ('BOARD', 'Boarded')], db_index=True, default='DD', help_text='Acquisition lifecycle status (Pass, DD, Drop, Awarded, Board); defaults to Due Diligence.', max_length=20),
        ),
    ]
