# Generated by Django 5.2.5 on 2025-09-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0022_sellerrawdata_occupancy_sellerrawdata_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerrawdata',
            name='baths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerrawdata',
            name='beds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerrawdata',
            name='lot_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerrawdata',
            name='sq_ft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerrawdata',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='asset_status',
            field=models.CharField(choices=[('NPL', 'NPL'), ('REO', 'REO'), ('PERF', 'PERF'), ('RPL', 'RPL')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='occupancy',
            field=models.CharField(blank=True, choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied'), ('Unknown', 'Unknown')], default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='property_type',
            field=models.CharField(blank=True, choices=[('SFR', 'SFR'), ('Manufactured', 'Manufactured'), ('Condo', 'Condo'), ('2-4 Family', '2-4 Family'), ('Land', 'Land'), ('Multifamily 5+', 'Multifamily 5+')], default='SFR', max_length=100, null=True),
        ),
    ]
