# Generated by Django 5.2.5 on 2025-09-11 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0023_sellerrawdata_baths_sellerrawdata_beds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlDataEnrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geocode_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geocode_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geocode_used_address', models.CharField(blank=True, max_length=255, null=True)),
                ('geocode_full_address', models.CharField(blank=True, max_length=255, null=True)),
                ('geocode_display_address', models.CharField(blank=True, max_length=255, null=True)),
                ('geocoded_at', models.DateTimeField(blank=True, null=True)),
                ('geocode_county', models.CharField(blank=True, max_length=255, null=True)),
                ('geocode_msa', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller_raw_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment', to='acq_module.sellerrawdata')),
            ],
            options={
                'verbose_name': 'Loan Level Data Enrichment',
                'verbose_name_plural': 'Loan Level Data Enrichments',
                'db_table': 'acq_ll_data_enrichment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller_raw_data'], name='acq_ll_data_seller__cbb3b3_idx'), models.Index(fields=['geocode_lat', 'geocode_lng'], name='acq_ll_data_geocode_476637_idx')],
            },
        ),
    ]
