# Generated by Django 5.2.5 on 2025-10-28 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0023_alter_sellerrawdata_acq_status'),
        ('core', '0031_fund_alter_jvequitypartner_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sellerrawdata',
            constraint=models.CheckConstraint(condition=models.Q(('property_type__isnull', True), ('property_type__in', ['SFR', 'Manufactured', 'Condo', 'Townhouse', '2-4 Family', 'Land', 'Multifamily 5+', 'Industrial', 'Mixed Use', 'Storage', 'Healthcare']), _connector='OR'), name='valid_property_type'),
        ),
        migrations.AddConstraint(
            model_name='sellerrawdata',
            constraint=models.CheckConstraint(condition=models.Q(('product_type__isnull', True), ('product_type__in', ['BPL', 'HECM', 'VA', 'Conv', 'Commercial']), _connector='OR'), name='valid_product_type'),
        ),
        migrations.AddConstraint(
            model_name='sellerrawdata',
            constraint=models.CheckConstraint(condition=models.Q(('occupancy__isnull', True), ('occupancy__in', ['Vacant', 'Occupied', 'Unknown']), _connector='OR'), name='valid_occupancy'),
        ),
        migrations.AddConstraint(
            model_name='sellerrawdata',
            constraint=models.CheckConstraint(condition=models.Q(('asset_status__isnull', True), ('asset_status__in', ['NPL', 'REO', 'PERF', 'RPL']), _connector='OR'), name='valid_asset_status'),
        ),
    ]
