# Generated by Django 5.2 on 2025-10-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0024_sellerrawdata_valid_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='acq_dd_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=150.0, help_text='Acquisition due diligence cost in dollars per loan', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='acq_legal_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=300.0, help_text='Acquisition legal cost in dollars per loan', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='acq_tax_title_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=100.0, help_text='Acquisition tax/title cost in dollars per loan', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='am_fee_pct',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.01, help_text='Asset management fee as decimal (e.g., 0.01 = 1%)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='bid_date',
            field=models.DateField(blank=True, help_text='Date the bid was submitted', null=True),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='discount_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.12, help_text='Discount rate for NPV calculations', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='max_mod_ltv',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.95, help_text='Maximum LTV for modifications as decimal (e.g., 0.95 = 95%)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='mod_amort_term',
            field=models.IntegerField(blank=True, default=360, help_text='Modification amortization term in months', null=True),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='mod_down_pmt',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.05, help_text='Modification down payment as decimal (e.g., 0.05 = 5%)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='mod_hold_duration',
            field=models.IntegerField(blank=True, default=6, help_text='Modification hold duration in months', null=True),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='mod_io_flag',
            field=models.BooleanField(blank=True, default=False, help_text='IO (interest-only) flag for modifications', null=True),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='mod_legal_term',
            field=models.IntegerField(blank=True, default=360, help_text='Modification legal term in months', null=True),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='mod_orig_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=500.0, help_text='Modification origination cost in dollars per loan', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='mod_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.04, help_text='Modification interest rate as decimal (e.g., 0.04 = 4%)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='mod_setup_duration',
            field=models.IntegerField(blank=True, default=6, help_text='Modification setup duration in months', null=True),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='pctUPB',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price as percentage of UPB', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='perf_rpl_hold_period',
            field=models.IntegerField(blank=True, default=12, help_text='Hold period for performing/re-performing loans (months)', null=True),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='settlement_date',
            field=models.DateField(blank=True, help_text='Expected or actual settlement date', null=True),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='target_irr',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Target internal rate of return for this trade', max_digits=6, null=True),
        ),
    ]
