# Generated by Django 5.2.5 on 2025-09-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0024_lldataenrichment'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokercrm',
            name='broker_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
