# Generated by Django 5.2 on 2025-10-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0025_alter_tradelevelassumption_acq_dd_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteSaleAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumption_name', models.CharField(help_text="Descriptive name for this note sale assumption (e.g., 'High Balance Low FICO')", max_length=100)),
                ('base_note_sale_pct', models.DecimalField(decimal_places=4, default=1.0, help_text='Base note sale percentage before discounts (e.g., 1.0000 = 100%)', max_digits=6)),
                ('balance_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum current balance for this assumption (null = no minimum)', max_digits=15, null=True)),
                ('balance_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum current balance for this assumption (null = no maximum)', max_digits=15, null=True)),
                ('balance_discount_factor', models.DecimalField(decimal_places=4, default=1.0, help_text='Balance discount factor (e.g., 0.9000 = 90%, 1.0500 = 105%)', max_digits=6)),
                ('maturity_months_min', models.IntegerField(blank=True, help_text='Minimum months to maturity for this assumption (null = no minimum)', null=True)),
                ('maturity_months_max', models.IntegerField(blank=True, help_text='Maximum months to maturity for this assumption (null = no maximum)', null=True)),
                ('maturity_discount_factor', models.DecimalField(decimal_places=4, default=1.0, help_text='Maturity discount factor (e.g., 0.8500 = 85%, 1.1000 = 110%)', max_digits=6)),
                ('fico_min', models.IntegerField(blank=True, help_text='Minimum FICO score for this assumption (null = no minimum)', null=True)),
                ('fico_max', models.IntegerField(blank=True, help_text='Maximum FICO score for this assumption (null = no maximum)', null=True)),
                ('fico_discount_factor', models.DecimalField(decimal_places=4, default=1.0, help_text='FICO discount factor (e.g., 0.7500 = 75%, 1.2000 = 120%)', max_digits=6)),
                ('priority', models.IntegerField(default=0, help_text='Priority when multiple assumptions match (higher number wins)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this assumption', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assumption is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Note Sale Assumption',
                'verbose_name_plural': 'Note Sale Assumptions',
                'db_table': 'note_sale_assumptions',
                'ordering': ['-priority', 'assumption_name'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='note_sale_a_is_acti_2f9317_idx'), models.Index(fields=['balance_min', 'balance_max'], name='note_sale_a_balance_8a07ef_idx'), models.Index(fields=['fico_min', 'fico_max'], name='note_sale_a_fico_mi_acf2e7_idx')],
            },
        ),
    ]
