# Generated by Django 5.2.5 on 2025-09-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0025_brokercrm_broker_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPartnerCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.CharField(help_text='Firm or organization name for the trading partner.', max_length=255)),
                ('name', models.CharField(blank=True, help_text="Primary contact person's full name.", max_length=255, null=True)),
                ('email', models.EmailField(blank=True, help_text='Primary contact email address.', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Primary contact phone number (free-form, include country code if applicable).', max_length=255, null=True)),
                ('altname', models.CharField(blank=True, help_text="Alternate contact person's full name.", max_length=255, null=True)),
                ('altemail', models.EmailField(blank=True, help_text='Alternate contact email address.', max_length=254, null=True)),
                ('alt_phone', models.CharField(blank=True, help_text='Alternate contact phone number.', max_length=255, null=True)),
                ('nda_flag', models.BooleanField(default=False, help_text='Whether an NDA is required/expected with this partner.')),
                ('nda_signed', models.DateField(blank=True, help_text='Date the NDA was fully executed (leave blank if not signed).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trading Partner',
                'verbose_name_plural': 'Trading Partners',
                'db_table': 'tradingpartnercrm',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='tradingpart_email_27ec99_idx'), models.Index(fields=['firm'], name='tradingpart_firm_0dbe26_idx')],
            },
        ),
    ]
