# Generated by Django 5.2 on 2025-10-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0026_notesaleassumption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notesaleassumption',
            options={'ordering': ['index_order', 'factor_type', '-priority', 'factor_name'], 'verbose_name': 'Note Sale Assumption', 'verbose_name_plural': 'Note Sale Assumptions'},
        ),
        migrations.RemoveIndex(
            model_name='notesaleassumption',
            name='note_sale_a_is_acti_2f9317_idx',
        ),
        migrations.RemoveIndex(
            model_name='notesaleassumption',
            name='note_sale_a_balance_8a07ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='notesaleassumption',
            name='note_sale_a_fico_mi_acf2e7_idx',
        ),
        migrations.RemoveField(
            model_name='notesaleassumption',
            name='assumption_name',
        ),
        migrations.RemoveField(
            model_name='notesaleassumption',
            name='balance_discount_factor',
        ),
        migrations.RemoveField(
            model_name='notesaleassumption',
            name='balance_max',
        ),
        migrations.RemoveField(
            model_name='notesaleassumption',
            name='balance_min',
        ),
        migrations.RemoveField(
            model_name='notesaleassumption',
            name='base_note_sale_pct',
        ),
        migrations.RemoveField(
            model_name='notesaleassumption',
            name='fico_discount_factor',
        ),
        migrations.RemoveField(
            model_name='notesaleassumption',
            name='fico_max',
        ),
        migrations.RemoveField(
            model_name='notesaleassumption',
            name='fico_min',
        ),
        migrations.RemoveField(
            model_name='notesaleassumption',
            name='maturity_discount_factor',
        ),
        migrations.RemoveField(
            model_name='notesaleassumption',
            name='maturity_months_max',
        ),
        migrations.RemoveField(
            model_name='notesaleassumption',
            name='maturity_months_min',
        ),
        migrations.AddField(
            model_name='notesaleassumption',
            name='discount_factor',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Discount factor (e.g., 0.9000 = 90%, 1.1000 = 110%)', max_digits=6),
        ),
        migrations.AddField(
            model_name='notesaleassumption',
            name='factor_name',
            field=models.CharField(default=1, help_text="Descriptive name (e.g., 'High Balance Premium', 'Poor Credit Discount')", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notesaleassumption',
            name='factor_type',
            field=models.CharField(choices=[('BALANCE', 'Current Balance'), ('MATURITY', 'Months to Maturity'), ('FICO', 'FICO Score'), ('LTV', 'Loan-to-Value Ratio'), ('PROPERTY_TYPE', 'Property Type')], default=1, help_text='Type of factor this discount applies to', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notesaleassumption',
            name='index_order',
            field=models.IntegerField(default=1, help_text='Calculation order (1-5, lower numbers calculated first)'),
        ),
        migrations.AddField(
            model_name='notesaleassumption',
            name='range_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum value for this range (null = no maximum)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='notesaleassumption',
            name='range_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum value for this range (null = no minimum)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='notesaleassumption',
            name='range_value',
            field=models.CharField(blank=True, help_text="Exact value match for string factors (e.g., 'SFR', 'Condo')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notesaleassumption',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this discount factor is currently active'),
        ),
        migrations.AlterField(
            model_name='notesaleassumption',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this discount factor', null=True),
        ),
        migrations.AlterField(
            model_name='notesaleassumption',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority when multiple ranges match same factor type (higher wins)'),
        ),
        migrations.AddIndex(
            model_name='notesaleassumption',
            index=models.Index(fields=['factor_type', 'is_active'], name='note_sale_a_factor__773373_idx'),
        ),
        migrations.AddIndex(
            model_name='notesaleassumption',
            index=models.Index(fields=['index_order', 'priority'], name='note_sale_a_index_o_83868b_idx'),
        ),
        migrations.AddIndex(
            model_name='notesaleassumption',
            index=models.Index(fields=['range_min', 'range_max'], name='note_sale_a_range_m_f1f59d_idx'),
        ),
    ]
