# Generated by Django 5.2.5 on 2025-09-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0026_tradingpartnercrm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brokercrm',
        ),
        migrations.DeleteModel(
            name='TradingPartnerCRM',
        ),
    ]
