# Generated by Django 5.2 on 2025-10-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0027_alter_notesaleassumption_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelevelassumption',
            name='acq_broker_fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Acquisition broker fees in dollars per loan', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='acq_other_costs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Acquisition other costs in dollars per loan', max_digits=10, null=True),
        ),
    ]
