# Generated by Django 5.2.5 on 2025-09-16 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0027_delete_brokercrm_delete_tradingpartnercrm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicer',
        ),
        migrations.DeleteModel(
            name='StateReference',
        ),
    ]
