# Generated by Django 5.2.5 on 2025-09-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0028_delete_servicer_delete_statereference'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerrawdata',
            name='sellertape_altid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
