# Generated by Django 5.2 on 2025-10-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0028_tradelevelassumption_acq_broker_fees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradelevelassumption',
            old_name='am_fee_pct',
            new_name='liq_am_fee_pct',
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='liq_broker_cc_pct',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.01, help_text='Broker closing cost as decimal (e.g., 0.01 = 1%)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='liq_tax_transfer_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Tax transfer cost in dollars per loan', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='liq_title_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Title cost in dollars per loan', max_digits=10, null=True),
        ),
    ]
