# Generated by Django 5.2.5 on 2025-10-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0029_rename_am_fee_pct_tradelevelassumption_liq_am_fee_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='servicing_transfer_date',
            field=models.DateField(blank=True, help_text='Date servicing transfers to new servicer (defaults to settlement_date + 30 days if not set)', null=True),
        ),
    ]
