# Generated by Django 5.2.5 on 2025-10-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0030_alter_tradelevelassumption_servicing_transfer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanlevelassumption',
            name='fc_duration_override_months',
            field=models.IntegerField(blank=True, default=0, help_text='User override to adjust FC duration in months (positive adds months, negative subtracts months from calculated FC duration)', null=True),
        ),
    ]
