# Generated by Django 5.2.5 on 2025-10-31 21:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0031_loanlevelassumption_fc_duration_override_months'),
        ('core', '0037_propertytypeassumption_squarefootageassumption_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loanlevelassumption',
            name='loan_level__seller__1ecd72_idx',
        ),
        migrations.RemoveField(
            model_name='loanlevelassumption',
            name='seller_raw_data',
        ),
        migrations.AddField(
            model_name='loanlevelassumption',
            name='asset_hub',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loan_assumptions', to='core.assetidhub'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanlevelassumption',
            name='estimated_rehab_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loanlevelassumption',
            name='estimated_reo_months',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanlevelassumption',
            name='fc_duration_override_months',
            field=models.IntegerField(blank=True, help_text='User override to adjust FC duration in months (positive adds months, negative subtracts months from calculated FC duration). NULL means no override.', null=True),
        ),
        migrations.AlterField(
            model_name='loanlevelassumption',
            name='foreclosure_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loanlevelassumption',
            name='legal_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loanlevelassumption',
            name='monthly_carrying_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loanlevelassumption',
            name='months_to_resolution',
            field=models.IntegerField(blank=True, help_text='Estimated months to resolve the loan', null=True),
        ),
        migrations.AlterField(
            model_name='loanlevelassumption',
            name='probability_of_cure',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Probability between 0 and 1', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='loanlevelassumption',
            name='probability_of_foreclosure',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Probability between 0 and 1', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='loanlevelassumption',
            name='property_preservation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loanlevelassumption',
            name='recovery_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Expected recovery percentage of principal', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='loanlevelassumption',
            index=models.Index(fields=['asset_hub'], name='loan_level__asset_h_4b21dc_idx'),
        ),
    ]
