# Generated by Django 5.2 on 2025-11-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0032_remove_loanlevelassumption_loan_level__seller__1ecd72_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanlevelassumption',
            name='acquisition_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='User-entered acquisition price for this asset. If not set, will be calculated from trade assumptions.', max_digits=15, null=True),
        ),
    ]
