# Generated by Django 5.2.5 on 2025-11-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0033_add_acquisition_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='acq_broker_fees',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, help_text='Acquisition broker fees in dollars per loan', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='acq_other_costs',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, help_text='Acquisition other costs in dollars per loan', max_digits=10, null=True),
        ),
    ]
