# Generated by Django 5.2.5 on 2025-11-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0034_alter_tradelevelassumption_acq_broker_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanlevelassumption',
            name='reo_fc_duration_override_months',
            field=models.IntegerField(blank=True, help_text='User override to adjust FC duration in months for REO Sale model (positive adds months, negative subtracts months). NULL means no override.', null=True),
        ),
        migrations.AddField(
            model_name='loanlevelassumption',
            name='reo_marketing_override_months',
            field=models.IntegerField(blank=True, help_text='User override to adjust REO marketing duration in months (positive adds months, negative subtracts months). NULL means no override.', null=True),
        ),
        migrations.AddField(
            model_name='loanlevelassumption',
            name='reo_renovation_override_months',
            field=models.IntegerField(blank=True, help_text='User override to adjust REO renovation duration in months (positive adds months, negative subtracts months). NULL means no override.', null=True),
        ),
        migrations.AlterField(
            model_name='loanlevelassumption',
            name='fc_duration_override_months',
            field=models.IntegerField(blank=True, help_text='User override to adjust FC duration in months for FC Sale model (positive adds months, negative subtracts months from calculated FC duration). NULL means no override.', null=True),
        ),
    ]
