# Generated by Django 5.2.5 on 2025-11-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0035_loanlevelassumption_reo_fc_duration_override_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerrawdata',
            name='property_type',
            field=models.CharField(blank=True, choices=[('SFR', 'SFR'), ('Manufactured', 'Manufactured'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('2-4 Family', '2-4 Family'), ('Multifamily 5+', 'Multifamily 5+'), ('Land', 'Land'), ('Industrial', 'Industrial'), ('Mixed Use', 'Mixed Use'), ('Storage', 'Storage'), ('Healthcare', 'Healthcare')], default='SFR', max_length=100, null=True),
        ),
    ]
