# Generated by Django 5.2.5 on 2025-11-07 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0036_alter_sellerrawdata_property_type'),
        ('core', '0045_add_default_none_to_property_type_assumptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='servicer',
            field=models.ForeignKey(blank=True, default=1, help_text='Selected servicing company for this trade (defaults to StateBridge)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_level_assumptions', to='core.servicer'),
        ),
    ]
