# Generated by Django 5.2.5 on 2025-11-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0037_alter_tradelevelassumption_servicer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerrawdata',
            name='drop_date',
        ),
        migrations.RemoveField(
            model_name='sellerrawdata',
            name='drop_reason',
        ),
        migrations.RemoveField(
            model_name='sellerrawdata',
            name='dropped_by',
        ),
        migrations.AlterField(
            model_name='sellerrawdata',
            name='acq_status',
            field=models.CharField(choices=[('KEEP', 'Keep'), ('DROP', 'Drop')], db_index=True, default='KEEP', help_text='Asset-level status: KEEP (in active pool) or DROP (excluded). Trade-level status controls lifecycle.', max_length=20),
        ),
    ]
