# Generated by Django 5.2.5 on 2025-12-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0038_remove_sellerrawdata_drop_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelevelassumption',
            name='bid_method',
            field=models.CharField(blank=True, choices=[('PCT_UPB', 'Percent of UPB'), ('TARGET_IRR', 'Target IRR')], help_text='Method used for bid (e.g., PCT_UPB or TARGET_IRR)', max_length=50, null=True),
        ),
    ]
