# Generated by Django 5.2.5 on 2025-12-03 21:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0039_tradelevelassumption_bid_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelevelassumption',
            name='pctUPB',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('85.00'), help_text='Purchase price as percentage of UPB', max_digits=15, null=True),
        ),
    ]
