# Generated by Django 5.2.5 on 2025-12-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0040_alter_tradelevelassumption_pctupb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelingDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_pct_upb', models.DecimalField(blank=True, decimal_places=2, help_text='Default purchase price as percentage of UPB for new trades (e.g., 85.00 = 85%)', max_digits=15, null=True)),
                ('default_discount_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Default discount rate for new trades as decimal (e.g., 0.12 = 12%)', max_digits=6, null=True)),
                ('default_perf_rpl_hold_period', models.IntegerField(blank=True, help_text='Default Perf/RPL hold period in months for new trades', null=True)),
                ('default_mod_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Default modification interest rate as decimal (e.g., 0.04 = 4%)', max_digits=6, null=True)),
                ('default_mod_legal_term', models.IntegerField(blank=True, help_text='Default modification legal term in months', null=True)),
                ('default_mod_amort_term', models.IntegerField(blank=True, help_text='Default modification amortization term in months', null=True)),
                ('default_max_mod_ltv', models.DecimalField(blank=True, decimal_places=4, help_text='Default maximum LTV for modifications as decimal (e.g., 0.95 = 95%)', max_digits=6, null=True)),
                ('default_mod_io_flag', models.BooleanField(default=False, help_text='Default IO (interest-only) flag for modifications')),
                ('default_mod_down_pmt', models.DecimalField(blank=True, decimal_places=4, help_text='Default modification down payment as decimal (e.g., 0.05 = 5%)', max_digits=6, null=True)),
                ('default_mod_orig_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Default modification origination cost in dollars per loan', max_digits=10, null=True)),
                ('default_mod_setup_duration', models.IntegerField(blank=True, help_text='Default modification setup duration in months', null=True)),
                ('default_mod_hold_duration', models.IntegerField(blank=True, help_text='Default modification hold duration in months', null=True)),
                ('default_acq_legal_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Default acquisition legal cost in dollars per loan', max_digits=10, null=True)),
                ('default_acq_dd_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Default acquisition due diligence cost in dollars per loan', max_digits=10, null=True)),
                ('default_acq_tax_title_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Default acquisition tax/title cost in dollars per loan', max_digits=10, null=True)),
                ('default_am_fee_pct', models.DecimalField(blank=True, decimal_places=4, help_text='Default AM fee as decimal for new trades (e.g., 0.01 = 1%)', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modeling Defaults',
                'verbose_name_plural': 'Modeling Defaults',
                'db_table': 'acq_modeling_defaults',
            },
        ),
    ]
