# Generated by Django 5.2.5 on 2025-12-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0041_modelingdefaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelevelassumption',
            name='total_discount',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Total discount rate (WACC result) - placeholder for testing, will be calculated later', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tradelevelassumption',
            name='wacc',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Weighted Average Cost of Capital as decimal (e.g., 0.12 for 12%) - will be calculated later', max_digits=6, null=True),
        ),
    ]
