# Generated by Django 5.2.5 on 2026-01-03 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0043_rehome_borrower_pii_to_acq'),
        ('core', '0095_remove_core_borrower_pii_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicerLoanExtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicer_loan_extracts', to='core.assetidhub')),
            ],
        ),
        migrations.CreateModel(
            name='ServicerTransactionExtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicer_transaction_extracts', to='core.assetidhub')),
            ],
        ),
    ]
