# Generated by Django 5.2.5 on 2026-01-30 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delinquency_status', models.CharField(choices=[('current', 'Current'), ('30', '30D'), ('60', '60D'), ('90', '90D'), ('120_plus', '120+D')], default='current', help_text='Bucketed delinquency status derived from ServicerLoanData dates.', max_length=16)),
                ('final_proceeds', models.DecimalField(blank=True, decimal_places=2, help_text='Final gross liquidation proceeds from any outcome track (REO, Short Sale, FC, etc.)', max_digits=12, null=True)),
                ('proceeds_source', models.CharField(blank=True, choices=[('reo', 'REO Sale'), ('short_sale', 'Short Sale'), ('foreclosure', 'Foreclosure Sale'), ('dil', 'Deed in Lieu'), ('modification', 'Loan Modification'), ('note_sale', 'Note Sale'), ('other', 'Other')], help_text='Which outcome track generated the final proceeds', max_length=20, null=True)),
                ('proceeds_date', models.DateField(blank=True, help_text='Date when final proceeds were realized', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated (any field).')),
            ],
            options={
                'verbose_name': 'AM Data',
                'verbose_name_plural': 'AM Data',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AMNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Note content')),
                ('tag', models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('legal', 'Legal'), ('qc', 'Quality Control'), ('ops', 'Operations'), ('info', 'Info')], help_text='Optional category tag (references core.models.NoteTag)', max_length=32, null=True)),
                ('pinned', models.BooleanField(default=False, help_text='Pin note to top of list')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When note was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When note was last updated')),
            ],
            options={
                'verbose_name': 'AM Note',
                'verbose_name_plural': 'AM Notes',
                'db_table': 'am_note',
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AMNoteSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_data', models.JSONField(default=dict, help_text='Structured summary data containing summary_text, bullets, and metadata')),
                ('notes_hash', models.CharField(db_index=True, help_text='Hash of note IDs and timestamps to detect changes', max_length=64)),
                ('generated_at', models.DateTimeField(auto_now=True, help_text='When this summary was last generated')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this summary record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this summary record was last updated')),
            ],
            options={
                'verbose_name': 'AM Note Summary',
                'verbose_name_plural': 'AM Note Summaries',
                'db_table': 'am_note_summary',
            },
        ),
        migrations.CreateModel(
            name='AssetCRMContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, db_index=True, help_text="Role of this contact for this asset (e.g., 'legal', 'servicer', 'broker')", max_length=32, null=True)),
                ('notes', models.TextField(blank=True, help_text="Notes about this contact's involvement with this asset", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset CRM Contact',
                'verbose_name_plural': 'Asset CRM Contacts',
                'db_table': 'am_asset_crm_contact',
                'ordering': ['role', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(help_text='Field name that was updated.', max_length=64)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (as text/JSON).', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value (as text/JSON).', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When the change occurred.')),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
