# Generated by Django 5.2 on 2025-09-19 02:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0001_initial'),
        ('core', '0006_alter_internalvaluation_internal_arv_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicerLoanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField(blank=True, help_text='Date this loan data was reported/effective.', null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Current principal balance of the loan.', max_digits=15, null=True)),
                ('deferred_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Portion of balance that has been deferred.', max_digits=15, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=3, help_text='Current interest rate (%).', max_digits=5, null=True)),
                ('next_due_date', models.DateField(blank=True, help_text='Next payment due date.', null=True)),
                ('last_paid_date', models.DateField(blank=True, help_text='Date of last payment received.', null=True)),
                ('term_remaining', models.IntegerField(blank=True, help_text='Remaining term in months.', null=True)),
                ('escrow_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Current escrow account balance.', max_digits=15, null=True)),
                ('escrow_advance_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Escrow advances made by servicer.', max_digits=15, null=True)),
                ('third_party_recov_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Third party recoverable balance.', max_digits=15, null=True)),
                ('suspense_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Funds held in suspense.', max_digits=15, null=True)),
                ('servicer_late_fees', models.DecimalField(blank=True, decimal_places=2, help_text='Late fees assessed by servicer.', max_digits=15, null=True)),
                ('other_charges', models.DecimalField(blank=True, decimal_places=2, help_text='Other charges on the loan.', max_digits=15, null=True)),
                ('interest_arrears', models.DecimalField(blank=True, decimal_places=2, help_text='Interest in arrears.', max_digits=15, null=True)),
                ('total_debt', models.DecimalField(blank=True, decimal_places=2, help_text='Total debt including all balances and fees.', max_digits=15, null=True)),
                ('lien_pos', models.IntegerField(blank=True, help_text='Lien position (1=first lien, 2=second lien, etc).', null=True)),
                ('maturity_date', models.DateField(blank=True, help_text='Date when loan matures/is due in full.', null=True)),
                ('default_rate', models.DecimalField(blank=True, decimal_places=3, help_text='Default interest rate (%).', max_digits=5, null=True)),
                ('origination_date', models.DateField(blank=True, help_text='Date when loan was originated.', null=True)),
                ('origination_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Original loan balance at origination.', max_digits=15, null=True)),
                ('origination_interest_rate', models.DecimalField(blank=True, decimal_places=3, help_text='Original interest rate at origination (%).', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated.')),
                ('asset_hub', models.OneToOneField(blank=True, help_text='Link to hub; one loan data record per asset.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicer_loan_data', to='core.assetidhub')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_servicer_loan_data', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_servicer_loan_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicer Loan Data',
                'verbose_name_plural': 'Servicer Loan Data',
                'db_table': 'am_servicer_loan_data',
                'ordering': ['-as_of_date', '-updated_at'],
                'indexes': [models.Index(fields=['asset_hub'], name='am_servicer_asset_h_9a31b8_idx'), models.Index(fields=['as_of_date'], name='am_servicer_as_of_d_89a10d_idx')],
            },
        ),
    ]
