# Generated by Django 5.2.5 on 2025-09-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='expected_moic',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Expected MOIC stored as decimal (0–100).', max_digits=6, null=True),
        ),
    ]
