# Generated by Django 5.2.5 on 2025-09-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerloandata',
            name='acquired_date',
            field=models.DateField(blank=True, help_text='Date the loan was acquired.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='acquisition_or_sale_identifier',
            field=models.CharField(blank=True, help_text='Identifier for acquisition or sale.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='actual_fc_sale_date',
            field=models.DateField(blank=True, help_text='Actual date of the foreclosure sale.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='address',
            field=models.CharField(blank=True, help_text='Address of the property.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='arm_audit_status',
            field=models.CharField(blank=True, help_text='Status of the ARM audit.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='arm_first_rate_change_date',
            field=models.DateField(blank=True, help_text='First rate change date for the ARM.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='arm_flag',
            field=models.BooleanField(blank=True, help_text='ARM flag.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='asset_manager',
            field=models.CharField(blank=True, help_text='Name of the asset manager.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='avm_date',
            field=models.DateField(blank=True, help_text='Date this loan data was reported/effective.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='avm_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current principal balance of the loan.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='balance_after_forgive',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Balance after forgiveness.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='balloon_date',
            field=models.DateField(blank=True, help_text='Date of the balloon payment.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='balloon_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of the balloon payment.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='bk_case_closed_date',
            field=models.DateField(blank=True, help_text='Date the BK case was closed.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='bk_ch',
            field=models.BooleanField(blank=True, help_text='BK change flag.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='bk_current_status',
            field=models.CharField(blank=True, help_text='BK current status.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='bk_discharge_date',
            field=models.DateField(blank=True, help_text='Date of bankruptcy discharge.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='bk_dismissed_date',
            field=models.DateField(blank=True, help_text='Date of bankruptcy dismissal.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='bk_filed_date',
            field=models.DateField(blank=True, help_text='Date bankruptcy was filed.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='bk_flag',
            field=models.BooleanField(blank=True, help_text='BK flag.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='bk_plan_end_date',
            field=models.DateField(blank=True, help_text='End date of the BK plan.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='bk_plan_length',
            field=models.IntegerField(blank=True, help_text='Length of the BK plan in months.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='bk_plan_start_date',
            field=models.DateField(blank=True, help_text='Start date of the BK plan.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='bk_post_petition_due_date',
            field=models.DateField(blank=True, help_text='Post-petition due date.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='borrower_count',
            field=models.IntegerField(blank=True, help_text='Number of borrowers on the loan.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='borrower_first_name',
            field=models.CharField(blank=True, help_text='First name of the borrower.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='borrower_home_phone',
            field=models.CharField(blank=True, help_text='Home phone number of the borrower.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='borrower_last_name',
            field=models.CharField(blank=True, help_text='Last name of the borrower.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='bpo_arv_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current principal balance of the loan.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='bpo_asis_date',
            field=models.DateField(blank=True, help_text='Date this loan data was reported/effective.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='bpo_asis_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current principal balance of the loan.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='city',
            field=models.CharField(blank=True, help_text='City of the property.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='co_borrower_fico',
            field=models.IntegerField(blank=True, help_text='FICO score of the co-borrower.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='co_borrower_fico_date',
            field=models.DateField(blank=True, help_text='Date of the co-borrower FICO score.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='collateral_count',
            field=models.IntegerField(blank=True, help_text='Number of collateral items.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='convert_to_fixed_rate',
            field=models.BooleanField(blank=True, help_text='Was the loan converted to a fixed rate?', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='current_fico',
            field=models.IntegerField(blank=True, help_text='Current FICO score of the borrower.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='current_fico_date',
            field=models.DateField(blank=True, help_text='Date this loan data was reported/effective.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='current_loan_term',
            field=models.IntegerField(blank=True, help_text='Current term of the loan in months.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='current_neg_am_bal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current negative amortization balance.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='current_pi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current principal balance of the loan.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='current_ti',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current interest balance of the loan.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='date_breach_letter_sent',
            field=models.DateField(blank=True, help_text='Date the breach letter was sent.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='date_inspection_completed',
            field=models.DateField(blank=True, help_text='Date of the last inspection.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='date_motion_for_relief_filed',
            field=models.DateField(blank=True, help_text='Date Motion for Relief was filed.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='date_object_to_confirmation_filed',
            field=models.DateField(blank=True, help_text='Date Objection to Confirmation was filed.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='date_of_meeting_of_creditors',
            field=models.DateField(blank=True, help_text='Date of the Meeting of Creditors.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='date_proof_of_claim_filed',
            field=models.DateField(blank=True, help_text='Date Proof of Claim was filed.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='date_referred_to_fc_atty',
            field=models.DateField(blank=True, help_text='Date referred to foreclosure attorney.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='days_in_foreclosure',
            field=models.IntegerField(blank=True, help_text='Number of days in foreclosure.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='deferred_advance_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deferred advance balance.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='deferred_interest',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deferred interest amount.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='deferred_principal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deferred principal amount.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='dil_completion_date',
            field=models.DateField(blank=True, help_text='Deed-in-Lieu completion date.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='escrowed_flag',
            field=models.BooleanField(blank=True, help_text='Escrowed flag.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='fc_completion_date',
            field=models.DateField(blank=True, help_text='Date foreclosure was completed.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='fc_flag',
            field=models.BooleanField(blank=True, help_text='FC flag.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='fc_status',
            field=models.CharField(blank=True, help_text='Current status of the foreclosure.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='first_due_date',
            field=models.DateField(blank=True, help_text='First payment due date.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='first_periodic_rate_cap',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='First periodic rate cap for an ARM.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='first_time_vacant_date',
            field=models.DateField(blank=True, help_text='Date the property was first found to be vacant.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='follow_up_date',
            field=models.DateField(blank=True, help_text='Date for next follow-up.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='forceplaced_flood_insurance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of force-placed flood insurance.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='forceplaced_hazard_insurance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of force-placed hazard insurance.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='foreclosure_business_area_status',
            field=models.CharField(blank=True, help_text='Status from the foreclosure business area.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='foreclosure_business_area_status_date',
            field=models.DateField(blank=True, help_text='Date of the foreclosure business area status.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='forgive_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of principal forgiven.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='inactive_date',
            field=models.DateField(blank=True, help_text='Date the loan became inactive.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='interest_method',
            field=models.CharField(blank=True, help_text='Method used for interest calculation.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='investor_id',
            field=models.IntegerField(blank=True, help_text='Investor ID associated with the loan.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='is_a_contested_fc',
            field=models.BooleanField(blank=True, help_text='Is the foreclosure contested?', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='is_house_for_sale',
            field=models.BooleanField(blank=True, help_text='Is the house currently for sale?', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='is_pay_option_arm',
            field=models.BooleanField(blank=True, help_text='Is this a pay-option ARM?', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='last_contact_outcome',
            field=models.CharField(blank=True, help_text='Outcome of the last contact.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='last_escrow_analysis_date',
            field=models.DateField(blank=True, help_text='Date of the last escrow analysis.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='last_successful_contact_date',
            field=models.DateField(blank=True, help_text='Date of the last successful contact.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='legal_status',
            field=models.CharField(blank=True, help_text='Legal status of the loan.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='life_cap',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Lifetime rate cap for an ARM.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='loan_age',
            field=models.IntegerField(blank=True, help_text='Age of the loan in months.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='loan_modification_date',
            field=models.DateField(blank=True, help_text='Date of loan modification.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='loan_modification_status',
            field=models.CharField(blank=True, help_text='Status of the loan modification.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='loan_purpose',
            field=models.CharField(blank=True, help_text='Purpose of the loan.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='loan_type',
            field=models.CharField(blank=True, help_text='Loan type.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='loan_warning',
            field=models.CharField(blank=True, help_text='Loan warning.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='loss_mitigation_business_area_status',
            field=models.CharField(blank=True, help_text='Status from the loss mitigation business area.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='loss_mitigation_business_area_status_date',
            field=models.DateField(blank=True, help_text='Date of the loss mitigation business area status.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='loss_mitigation_start_date',
            field=models.DateField(blank=True, help_text='Date loss mitigation started.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='loss_mitigation_status',
            field=models.CharField(blank=True, help_text='Current status of loss mitigation.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='max_rate',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum interest rate for an ARM loan.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='mba',
            field=models.BooleanField(blank=True, help_text='MBA flag.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='mers_num',
            field=models.CharField(blank=True, help_text='MERS MIN number.', max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='mi_active_policy',
            field=models.BooleanField(blank=True, help_text='Is the MI policy active?', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='mi_certificate_number',
            field=models.CharField(blank=True, help_text='MI certificate number.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='mi_claim',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='MI claim amount.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='mi_claim_filed_date',
            field=models.DateField(blank=True, help_text='Date the MI claim was filed.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='mi_claim_status',
            field=models.CharField(blank=True, help_text='Status of the MI claim.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='mi_company_name',
            field=models.CharField(blank=True, help_text='Mortgage insurance company name.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='mi_coverage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='MI coverage percentage.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='mi_date_closed',
            field=models.DateField(blank=True, help_text='Date the MI claim was closed.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='mi_date_paid',
            field=models.DateField(blank=True, help_text='Date the MI claim was paid.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='mi_last_review_date',
            field=models.DateField(blank=True, help_text='Last review date for the MI policy.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='mi_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid by MI.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='mi_rescind_date',
            field=models.DateField(blank=True, help_text='Date the MI policy was rescinded.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='mi_rescind_reason',
            field=models.CharField(blank=True, help_text='Reason for MI policy rescission.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='min_rate',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum interest rate for an ARM loan.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='mod_extended_maturity',
            field=models.DateField(blank=True, help_text='Extended maturity date after modification.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='mod_forbearance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Forbearance amount in modification.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='mod_forgiven',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount forgiven in modification.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='modification_type',
            field=models.CharField(blank=True, help_text='Type of loan modification.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='modified_first_payment_date',
            field=models.DateField(blank=True, help_text='First payment date after modification.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='neighborhood_condition',
            field=models.CharField(blank=True, help_text='Condition of the neighborhood.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='next_arm_rate_change_date',
            field=models.DateField(blank=True, help_text='Next ARM rate change date.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='noi_expiration_date',
            field=models.DateField(blank=True, help_text='Notice of Intent expiration date.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='non_recoverable_corporate_advance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Non-recoverable corporate advance.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='non_recoverable_escrow',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Non-recoverable escrow.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='non_recoverable_fees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Non-recoverable fees.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='non_recoverable_interest',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Non-recoverable interest.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='non_recoverable_principal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Non-recoverable principal.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='number_of_payments',
            field=models.IntegerField(blank=True, help_text='Number of payments in the plan.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='occupnacy',
            field=models.CharField(blank=True, help_text='Occupancy status.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='original_amt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original loan amount.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='original_appraised_date',
            field=models.DateField(blank=True, help_text='Date when loan was originated.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='original_appraised_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original appraised value of the property.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='original_first_payment_date',
            field=models.DateField(blank=True, help_text='Original first payment date.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='original_loan_term',
            field=models.IntegerField(blank=True, help_text='Original term of the loan in months.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='original_maturity_date',
            field=models.DateField(blank=True, help_text='Original maturity date.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='pay_option_negative_am_factor',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Negative amortization factor for pay-option ARM.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='periodic_rate_cap',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Periodic rate cap for an ARM.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='pif_date',
            field=models.DateField(blank=True, help_text='Paid-in-full date.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='pif_quote_date',
            field=models.DateField(blank=True, help_text='Date the PIF quote was generated.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='piti',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current principal balance of the loan.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='post_modification_coupon',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Coupon rate after modification.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='post_modification_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Payment amount after modification.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='post_modification_principal_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Principal balance after modification.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='pre_modification_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Balance before modification.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='pre_modification_coupon',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Coupon rate before modification.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='pre_modification_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Payment amount before modification.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='prepetition_unapplied_bal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pre-petition unapplied balance.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='previous_servicer_id',
            field=models.IntegerField(blank=True, help_text='Previous servicer ID associated with the loan.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='prim_stat',
            field=models.CharField(blank=True, help_text='Primary status.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='promise_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Promised payment amount.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='promise_date',
            field=models.DateField(blank=True, help_text='Date of the promised payment.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='property_condition_from_inspection',
            field=models.CharField(blank=True, help_text='Property condition from inspection.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='property_county',
            field=models.CharField(blank=True, help_text='County of the property.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='property_type',
            field=models.CharField(blank=True, help_text='Type of property.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='reason_for_default',
            field=models.CharField(blank=True, help_text='Reason for the loan default.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='relief_date',
            field=models.DateField(blank=True, help_text='Date relief was granted.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='repay_plan_type',
            field=models.CharField(blank=True, help_text='Type of repayment plan.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='repayment_plan_agreement_date',
            field=models.DateField(blank=True, help_text='Date of the repayment plan agreement.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='repayment_plan_start_date',
            field=models.DateField(blank=True, help_text='Start date of the repayment plan.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='repayment_plan_status',
            field=models.CharField(blank=True, help_text='Status of the repayment plan.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='res_service_fee_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Resolution service fee paid.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='resolution_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Balance at resolution.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='resolution_corporate_advance_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Resolution corporate advance balance.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='resolution_escrow_advance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Resolution escrow advance.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='resolution_fees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Resolution fees.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='resolution_post_date',
            field=models.DateField(blank=True, help_text='Date the resolution was posted.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='resolution_proceeds',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Proceeds from the resolution.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='resolution_type',
            field=models.CharField(blank=True, help_text='Type of resolution.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='right_party_date',
            field=models.DateField(blank=True, help_text='Date of right party contact.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='right_party_type',
            field=models.CharField(blank=True, help_text='Type of right party contacted.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='scheduled_fc_sale_date',
            field=models.DateField(blank=True, help_text='Scheduled date for the foreclosure sale.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='servicer_id',
            field=models.IntegerField(blank=True, help_text='Servicer ID associated with the loan.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='servicing_specialist',
            field=models.CharField(blank=True, help_text='Name of the servicing specialist.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='single_point_of_contact',
            field=models.CharField(blank=True, help_text='Single point of contact for the loan.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='ss_complete',
            field=models.BooleanField(blank=True, help_text='Short sale complete flag.', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='ss_proceeds_rcvd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Short sale proceeds received.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='state',
            field=models.CharField(blank=True, help_text='State of the property.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='stipulation_unapplied_bal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Stipulation unapplied balance.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='total_capitalized_by_mod',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount capitalized by modification.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='total_interest',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total interest amount.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='total_principal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total principal amount.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='trust_id',
            field=models.CharField(blank=True, help_text='ID of the trust.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='within_pay_option_period',
            field=models.BooleanField(blank=True, help_text='Is the loan within the pay-option period?', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='workout_option',
            field=models.CharField(blank=True, help_text='Selected workout option.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='zip_code',
            field=models.CharField(blank=True, help_text='Zip code of the property.', max_length=20, null=True),
        ),
    ]
