# Generated by Django 5.2.5 on 2025-09-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0002_blendedoutcomemodel_expected_moic'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerboardeddata',
            name='sellertape_altid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerboardeddata',
            name='sellertape_id',
            field=models.IntegerField(blank=True),
        ),
    ]
