# Generated by Django 5.2 on 2025-09-19 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0002_servicerloandata'),
        ('core', '0006_alter_internalvaluation_internal_arv_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerloandata',
            options={'ordering': ['-reporting_year', '-reporting_month', '-as_of_date'], 'verbose_name': 'Servicer Loan Data', 'verbose_name_plural': 'Servicer Loan Data'},
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='reporting_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Month of this loan data snapshot (1-12).', null=True),
        ),
        migrations.AddField(
            model_name='servicerloandata',
            name='reporting_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year of this loan data snapshot (e.g., 2025).', null=True),
        ),
        migrations.AlterField(
            model_name='servicerloandata',
            name='asset_hub',
            field=models.ForeignKey(blank=True, help_text='Link to hub; multiple loan data records per asset over time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicer_loan_data', to='core.assetidhub'),
        ),
        migrations.AddIndex(
            model_name='servicerloandata',
            index=models.Index(fields=['reporting_year', 'reporting_month'], name='am_servicer_reporti_4e5817_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicerloandata',
            constraint=models.UniqueConstraint(fields=('asset_hub', 'reporting_year', 'reporting_month'), name='unique_asset_reporting_period'),
        ),
    ]
