# Generated by Django 5.2.5 on 2025-09-23 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0002_servicerloandata_acquired_date_and_more'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmetrics',
            name='asset',
        ),
        migrations.AddField(
            model_name='assetmetrics',
            name='asset_hub',
            field=models.OneToOneField(default=1, help_text='The AssetIdHub this metrics record belongs to.', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='am_metrics', serialize=False, to='core.assetidhub'),
            preserve_default=False,
        ),
    ]
