# Generated by Django 5.2.5 on 2025-09-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0003_sellerboardeddata_sellertape_altid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerboardeddata',
            name='as_of_date',
        ),
        migrations.AlterField(
            model_name='sellerboardeddata',
            name='acq_seller_id',
            field=models.IntegerField(help_text='ID reference to the original Seller model in acq_module', null=True),
        ),
        migrations.AlterField(
            model_name='sellerboardeddata',
            name='acq_trade_id',
            field=models.IntegerField(help_text='ID reference to the original Trade model in acq_module', null=True),
        ),
    ]
