# Generated by Django 5.2.5 on 2025-09-23 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0003_remove_assetmetrics_asset_assetmetrics_asset_hub'),
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AMMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated (any field).')),
                ('asset_hub', models.ForeignKey(blank=True, help_text='Optional hub this data belongs to (NULL for global entries).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ammetrics', to='core.assetidhub')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record (if known).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ammetrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AM Data',
                'verbose_name_plural': 'AM Data',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AMMetricsChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Field name that was updated.', max_length=64)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (as text/JSON).', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value (as text/JSON).', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When the change occurred.')),
                ('asset_hub', models.ForeignKey(blank=True, help_text='Denormalized hub reference for direct filtering.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ammetrics_changes', to='core.assetidhub')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the change (if known).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ammetrics_changes', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(help_text='The metrics record this change belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='am_module.ammetrics')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AMNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Free-form note text for this asset.')),
                ('tag', models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('legal', 'Legal'), ('qc', 'Quality Control'), ('ops', 'Operations'), ('info', 'Info')], help_text='Optional single tag for categorizing the note.', max_length=32, null=True)),
                ('pinned', models.BooleanField(default=False, help_text='Pin this note for prominence in UI.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this note was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this note was last updated.')),
                ('asset_hub', models.ForeignKey(blank=True, help_text='Many notes per AssetIdHub (hub is the canonical asset key).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='am_notes', to='core.assetidhub')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this note (if known).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_am_notes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this note (if known).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_am_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DIL',
            fields=[
                ('asset_hub', models.OneToOneField(help_text='1:1 with hub; DIL keyed by AssetIdHub.', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='dil', serialize=False, to='core.assetidhub')),
                ('dil_completion_date', models.DateField(blank=True, help_text='Completion date of the DIL (optional).', null=True)),
                ('dil_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Average cost of the DIL (optional).', max_digits=10, null=True)),
                ('cfk_cost', models.DecimalField(blank=True, decimal_places=2, help_text='CFK cost of the DIL (optional).', max_digits=10, null=True)),
                ('legal_crm', models.ForeignKey(blank=True, help_text='Legal entity/contact from CRM associated with this DIL (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dils', to='core.mastercrm')),
            ],
        ),
        migrations.CreateModel(
            name='FCSale',
            fields=[
                ('asset_hub', models.OneToOneField(help_text='1:1 with hub; foreclosure sale keyed by AssetIdHub.', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='fc_sale', serialize=False, to='core.assetidhub')),
                ('fc_sale_sched_date', models.DateField(blank=True, help_text='Scheduled date of the foreclosure sale (optional).', null=True)),
                ('fc_sale_actual_date', models.DateField(blank=True, help_text='Actual date of the foreclosure sale (optional).', null=True)),
                ('fc_bid_price', models.DecimalField(blank=True, decimal_places=2, help_text='Bid price of the foreclosure sale (optional).', max_digits=10, null=True)),
                ('fc_sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price of the foreclosure sale (optional).', max_digits=10, null=True)),
                ('legal_crm', models.ForeignKey(blank=True, help_text='Legal entity/contact from CRM associated with this foreclosure sale (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fc_sales', to='core.mastercrm')),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('asset_hub', models.OneToOneField(help_text='1:1 with hub; modification keyed by AssetIdHub.', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='modification', serialize=False, to='core.assetidhub')),
                ('modification_date', models.DateField(blank=True, help_text='Date of the modification (optional).', null=True)),
                ('modification_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost of the modification (optional).', max_digits=10, null=True)),
                ('modification_upb', models.DecimalField(blank=True, decimal_places=2, help_text='UPB of the modification (optional).', max_digits=10, null=True)),
                ('modification_term', models.IntegerField(blank=True, help_text='Term of the modification (optional).', null=True)),
                ('modification_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Rate of the modification (optional).', max_digits=6, null=True)),
                ('modification_maturity_date', models.DateField(blank=True, help_text='Maturity date of the modification (optional).', null=True)),
                ('modification_pi', models.CharField(blank=True, choices=[('pi', 'P&I'), ('io', 'Interest Only'), ('other', 'Other')], help_text='Payment of the modification (optional).', max_length=32, null=True)),
                ('modification_down_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Down payment of the modification (optional).', max_digits=10, null=True)),
                ('broker_crm', models.ForeignKey(blank=True, help_text='Broker entity/contact from CRM associated with this modification (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='core.mastercrm')),
            ],
        ),
        migrations.CreateModel(
            name='REOData',
            fields=[
                ('asset_hub', models.OneToOneField(help_text='1:1 with hub; REO data keyed by AssetIdHub.', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='reo_data', serialize=False, to='core.assetidhub')),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, help_text='List price of the REO property (optional).', max_digits=10, null=True)),
                ('list_date', models.DateField(blank=True, help_text='Date the property was listed (optional).', null=True)),
                ('under_contract_flag', models.BooleanField(default=False, help_text='Whether the property is under contract (optional).')),
                ('under_contract_date', models.DateField(blank=True, help_text='Date the property went under contract (optional).', null=True)),
                ('contract_price', models.DecimalField(blank=True, decimal_places=2, help_text='Contract price of the REO property (optional).', max_digits=10, null=True)),
                ('estimated_close_date', models.DateField(blank=True, help_text='Estimated close date of the REO property (optional).', null=True)),
                ('actual_close_date', models.DateField(blank=True, help_text='Actual close date of the REO property (optional).', null=True)),
                ('seller_credit_amt', models.DecimalField(blank=True, decimal_places=2, help_text='Seller credit amount (optional).', max_digits=10, null=True)),
                ('purchase_type', models.CharField(blank=True, choices=[('cash', 'Cash'), ('financing', 'Financing'), ('seller_financing', 'Seller Financing')], help_text='How the property was purchased (Cash, Financing, Seller Financing).', max_length=32, null=True)),
                ('gross_purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Gross purchase price of the REO property (optional).', max_digits=10, null=True)),
                ('broker_crm', models.OneToOneField(blank=True, help_text='Linked CRM contact (Broker) for this REO asset (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reo_record', to='core.mastercrm')),
            ],
        ),
        migrations.CreateModel(
            name='ShortSale',
            fields=[
                ('asset_hub', models.OneToOneField(help_text='1:1 with hub; short sale keyed by AssetIdHub.', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='short_sale', serialize=False, to='core.assetidhub')),
                ('acceptable_min_offer', models.DecimalField(blank=True, decimal_places=2, help_text='Acceptable minimum offer for the short sale (optional).', max_digits=10, null=True)),
                ('short_sale_date', models.DateField(blank=True, help_text='Date of the short sale (optional).', null=True)),
                ('broker_crm', models.ForeignKey(blank=True, help_text='Broker entity/contact from CRM associated with this short sale (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_sales', to='core.mastercrm')),
            ],
        ),
        migrations.AddIndex(
            model_name='ammetrics',
            index=models.Index(fields=['asset_hub'], name='am_module_a_asset_h_76b285_idx'),
        ),
        migrations.AddIndex(
            model_name='ammetricschange',
            index=models.Index(fields=['record', 'changed_at'], name='am_module_a_record__db193f_idx'),
        ),
        migrations.AddIndex(
            model_name='ammetricschange',
            index=models.Index(fields=['field_name', 'changed_at'], name='am_module_a_field_n_3e7084_idx'),
        ),
        migrations.AddIndex(
            model_name='ammetricschange',
            index=models.Index(fields=['asset_hub', 'changed_at'], name='am_module_a_asset_h_9b6b98_idx'),
        ),
        migrations.AddIndex(
            model_name='amnote',
            index=models.Index(fields=['asset_hub', 'pinned', 'updated_at'], name='am_module_a_asset_h_a56c46_idx'),
        ),
    ]
