# Generated by Django 5.2.5 on 2025-09-23 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0004_ammetrics_ammetricschange_amnote_dil_fcsale_and_more'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DILTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('owner_contacted', 'Owner/Heirs contacted'), ('dil_drafted', 'Deed-in-Lieu Drafted'), ('dil_successful', 'Deed-in-Lieu Successful')], help_text='DIL workflow stage for this task.', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this task was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this task was last updated.')),
                ('asset_hub', models.ForeignKey(help_text='The asset hub this DIL task belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='dil_tasks', to='core.assetidhub')),
                ('dil', models.ForeignKey(help_text='The DIL record this task is associated with (many-to-one).', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='am_module.dil')),
            ],
        ),
        migrations.CreateModel(
            name='FCTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('nod_noi', 'NOD/NOI'), ('fc_filing', 'FC Filing'), ('mediation', 'Mediation'), ('judgement', 'Judgement'), ('redemption', 'Redemption'), ('sale_scheduled', 'Sale Scheduled'), ('sold', 'Sold')], help_text='Foreclosure workflow stage for this task.', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this task was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this task was last updated.')),
                ('asset_hub', models.ForeignKey(help_text='The asset hub this foreclosure task belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='fc_tasks', to='core.assetidhub')),
                ('fc_sale', models.ForeignKey(help_text='The FCSale record this task is associated with (many-to-one).', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='am_module.fcsale')),
            ],
        ),
        migrations.CreateModel(
            name='ModificationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('mod_negotiations', 'Mod negotiations'), ('mod_accepted', 'Mod Accepted'), ('mod_started', 'Mod Started'), ('mod_failed', 'Mod Failed')], help_text='Modification workflow stage for this task.', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this task was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this task was last updated.')),
                ('asset_hub', models.ForeignKey(help_text='The asset hub this modification task belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='modification_tasks', to='core.assetidhub')),
                ('modification', models.ForeignKey(help_text='The Modification record this task is associated with (many-to-one).', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='am_module.modification')),
            ],
        ),
        migrations.CreateModel(
            name='REOtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('eviction', 'Eviction'), ('trashout', 'Trashout'), ('renovation', 'Renovation'), ('marketing', 'Marketing'), ('under_contract', 'Under Contract'), ('sold', 'Sold')], help_text='Type of REO task (Eviction, Trashout, Renovation, Marketing, Under Contract, Sold).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this task row was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this task row was last updated.')),
                ('asset_hub', models.ForeignKey(help_text='The asset hub this REO task belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='reo_tasks', to='core.assetidhub')),
                ('reo_outcome', models.ForeignKey(help_text='The REOData record this task is associated with (many-to-one).', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='am_module.reodata')),
            ],
        ),
        migrations.CreateModel(
            name='ShortSaleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('list_price_accepted', 'List Price Accepted'), ('listed', 'Listed'), ('under_contract', 'Under-Contract'), ('sold', 'Sold')], help_text='Short Sale workflow stage for this task.', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this task was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this task was last updated.')),
                ('short_sale', models.ForeignKey(help_text='The ShortSale record this task is associated with (many-to-one).', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='am_module.shortsale')),
            ],
        ),
    ]
