# Generated by Django 5.2.5 on 2025-09-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0004_remove_sellerboardeddata_as_of_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerboardeddata',
            name='bk_flag',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sellerboardeddata',
            name='boarded_by',
            field=models.CharField(blank=True, help_text='User who initiated the boarding process', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerboardeddata',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerboardeddata',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerboardeddata',
            name='fc_flag',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sellerboardeddata',
            name='mod_flag',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sellerboardeddata',
            name='seller_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerboardeddata',
            name='sellertape_altid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sellerboardeddata',
            name='sellertape_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sellerboardeddata',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerboardeddata',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerboardeddata',
            name='trade_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerboardeddata',
            name='zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
