# Generated by Django 5.2.5 on 2025-09-23 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0005_diltask_fctask_modificationtask_reotask_and_more'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortsaletask',
            name='asset_hub',
            field=models.ForeignKey(default=1, help_text='The asset hub this short sale task belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='short_sale_tasks', to='core.assetidhub'),
            preserve_default=False,
        ),
    ]
