# Generated by Django 5.2.5 on 2025-09-17 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0005_alter_sellerboardeddata_bk_flag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blendedoutcomemodel',
            old_name='exit_date',
            new_name='expected_exit_date',
        ),
        migrations.RenameField(
            model_name='blendedoutcomemodel',
            old_name='total_expenses',
            new_name='expected_total_expenses',
        ),
        migrations.RenameField(
            model_name='blendedoutcomemodel',
            old_name='total_hold',
            new_name='expected_total_hold',
        ),
    ]
