# Generated by Django 5.2.5 on 2025-09-23 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0006_shortsaletask_asset_hub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ammetricschange',
            options={'ordering': ['-changed_at', '-id'], 'verbose_name': 'AM Metrics Change', 'verbose_name_plural': 'AM Metrics Changes'},
        ),
        migrations.AlterModelOptions(
            name='amnote',
            options={'ordering': ['-pinned', '-updated_at', '-id'], 'verbose_name': 'AM Note', 'verbose_name_plural': 'AM Notes'},
        ),
        migrations.AlterModelOptions(
            name='dil',
            options={'verbose_name': 'Deed in Lieu (DIL)', 'verbose_name_plural': 'Deeds in Lieu (DILs)'},
        ),
        migrations.AlterModelOptions(
            name='diltask',
            options={'verbose_name': 'DIL Task', 'verbose_name_plural': 'DIL Tasks'},
        ),
        migrations.AlterModelOptions(
            name='fcsale',
            options={'verbose_name': 'Foreclosure Sale', 'verbose_name_plural': 'Foreclosure Sales'},
        ),
        migrations.AlterModelOptions(
            name='fctask',
            options={'verbose_name': 'Foreclosure Task', 'verbose_name_plural': 'Foreclosure Tasks'},
        ),
        migrations.AlterModelOptions(
            name='modification',
            options={'verbose_name': 'Loan Modification', 'verbose_name_plural': 'Loan Modifications'},
        ),
        migrations.AlterModelOptions(
            name='modificationtask',
            options={'verbose_name': 'Modification Task', 'verbose_name_plural': 'Modification Tasks'},
        ),
        migrations.AlterModelOptions(
            name='reodata',
            options={'ordering': ['-list_date'], 'verbose_name': 'REO Data', 'verbose_name_plural': 'REO Data'},
        ),
        migrations.AlterModelOptions(
            name='reotask',
            options={'verbose_name': 'REO Task', 'verbose_name_plural': 'REO Tasks'},
        ),
        migrations.AlterModelOptions(
            name='shortsale',
            options={'verbose_name': 'Short Sale', 'verbose_name_plural': 'Short Sales'},
        ),
        migrations.AlterModelOptions(
            name='shortsaletask',
            options={'verbose_name': 'Short Sale Task', 'verbose_name_plural': 'Short Sale Tasks'},
        ),
    ]
