# Generated by Django 5.2.5 on 2025-09-24 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0007_alter_ammetricschange_options_alter_amnote_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ammetricschange',
            options={'ordering': ['-changed_at', '-id'], 'verbose_name': 'AM Metrics Change (Deprecated)', 'verbose_name_plural': 'AM Metrics Changes (Deprecated)'},
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(help_text='Field name that was updated.', max_length=64)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (as text/JSON).', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value (as text/JSON).', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When the change occurred.')),
                ('asset_hub', models.ForeignKey(blank=True, help_text='Denormalized hub reference for direct filtering.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.assetidhub')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the change (if known).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-changed_at', '-id'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'changed_at'], name='am_module_a_content_5c8793_idx'), models.Index(fields=['field_name', 'changed_at'], name='am_module_a_field_n_10e0fd_idx'), models.Index(fields=['asset_hub', 'changed_at'], name='am_module_a_asset_h_ad72ea_idx'), models.Index(fields=['changed_by', 'changed_at'], name='am_module_a_changed_323684_idx')],
            },
        ),
    ]
