# Generated by Django 5.2.5 on 2025-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0008_alter_ammetricschange_options_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ammetrics',
            name='delinquency_status',
            field=models.CharField(choices=[('current', 'Current'), ('30', '30D'), ('60', '60D'), ('90', '90D'), ('120_plus', '120+D')], default='current', help_text='Bucketed delinquency status derived from ServicerLoanData dates.', max_length=16),
        ),
    ]
