# Generated by Django 5.2.5 on 2025-09-25 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0010_alter_sellerboardeddata_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reotask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this task was created.'),
        ),
        migrations.AlterField(
            model_name='reotask',
            name='reo_outcome',
            field=models.ForeignKey(help_text='The REO outcome record this task is associated with (many-to-one).', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='am_module.reodata'),
        ),
        migrations.AlterField(
            model_name='reotask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this task was last updated.'),
        ),
    ]
