# Generated by Django 5.2.5 on 2025-09-26 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0011_alter_reotask_created_at_alter_reotask_reo_outcome_and_more'),
        ('core', '0003_assetidhub_servicer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reotask',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'REO Task', 'verbose_name_plural': 'REO Tasks'},
        ),
        migrations.AddField(
            model_name='amnote',
            name='context_outcome',
            field=models.CharField(blank=True, choices=[('dil', 'Deed-in-Lieu'), ('fc', 'Foreclosure'), ('reo', 'REO'), ('short_sale', 'Short Sale'), ('modification', 'Modification')], help_text='Outcome context this note relates to (nullable for asset-level notes).', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='amnote',
            name='context_task_id',
            field=models.IntegerField(blank=True, help_text='Optional specific task row id if tying directly to a task instance.', null=True),
        ),
        migrations.AddField(
            model_name='amnote',
            name='context_task_type',
            field=models.CharField(blank=True, help_text="Task type key this note relates to (e.g., 'eviction', 'owner_contacted').", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='amnote',
            name='scope',
            field=models.CharField(choices=[('asset', 'Asset'), ('outcome', 'Outcome'), ('task', 'Task')], default='asset', help_text='Primary attachment context for this note (asset, outcome, or task).', max_length=16),
        ),
        migrations.AddIndex(
            model_name='amnote',
            index=models.Index(fields=['asset_hub', 'context_outcome', 'updated_at'], name='am_module_a_asset_h_81ea49_idx'),
        ),
        migrations.AddIndex(
            model_name='amnote',
            index=models.Index(fields=['asset_hub', 'context_task_type', 'updated_at'], name='am_module_a_asset_h_8c9eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='amnote',
            index=models.Index(fields=['asset_hub', 'context_task_id', 'updated_at'], name='am_module_a_asset_h_e8e82b_idx'),
        ),
    ]
