# Generated by Django 5.2.5 on 2025-09-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0012_alter_reotask_options_amnote_context_outcome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diltask',
            name='task_type',
            field=models.CharField(choices=[('owner_contacted', 'Owner/Heirs contacted'), ('no_cooperation', 'No Cooperation'), ('dil_drafted', 'Deed-in-Lieu Drafted'), ('dil_successful', 'Deed-in-Lieu Successful')], help_text='DIL workflow stage for this task.', max_length=32),
        ),
    ]
