# Generated by Django 5.2.5 on 2025-09-26 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0013_alter_diltask_task_type'),
        ('core', '0003_assetidhub_servicer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dil',
            name='legal_crm',
        ),
        migrations.RemoveField(
            model_name='fcsale',
            name='legal_crm',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='broker_crm',
        ),
        migrations.RemoveField(
            model_name='reodata',
            name='broker_crm',
        ),
        migrations.RemoveField(
            model_name='shortsale',
            name='broker_crm',
        ),
        migrations.AddField(
            model_name='dil',
            name='crm',
            field=models.ForeignKey(blank=True, help_text='CRM contact associated with this DIL (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dils', to='core.mastercrm'),
        ),
        migrations.AddField(
            model_name='fcsale',
            name='crm',
            field=models.ForeignKey(blank=True, help_text='CRM contact associated with this foreclosure sale (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fc_sales', to='core.mastercrm'),
        ),
        migrations.AddField(
            model_name='modification',
            name='crm',
            field=models.ForeignKey(blank=True, help_text='CRM contact associated with this modification (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='core.mastercrm'),
        ),
        migrations.AddField(
            model_name='reodata',
            name='crm',
            field=models.OneToOneField(blank=True, help_text='Linked CRM contact for this REO asset (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reo_record', to='core.mastercrm'),
        ),
        migrations.AddField(
            model_name='shortsale',
            name='crm',
            field=models.ForeignKey(blank=True, help_text='CRM contact associated with this short sale (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_sales', to='core.mastercrm'),
        ),
    ]
