# Generated by Django 5.2 on 2025-09-29 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0014_remove_dil_legal_crm_remove_fcsale_legal_crm_and_more'),
        ('core', '0003_assetidhub_servicer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='REOScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_kind', models.CharField(blank=True, choices=[('trashout', 'Trashout'), ('renovation', 'Renovation')], help_text='Scope classification (Trashout or Renovation). Optional but recommended.', max_length=16, null=True)),
                ('vendor_name', models.CharField(help_text='Vendor/company name providing the scope/bid.', max_length=255)),
                ('contact_name', models.CharField(blank=True, help_text='Primary contact name (optional).', max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone (optional).', max_length=32, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Primary contact email (optional).', max_length=254, null=True)),
                ('scope_date', models.DateField(blank=True, help_text='Date of the scope/bid (optional).', null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total cost quoted or expected (optional).', max_digits=10, null=True)),
                ('expected_completion', models.DateField(blank=True, help_text='Expected completion date (optional).', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or itemization (optional).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this scope record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this scope record was last updated.')),
                ('asset_hub', models.ForeignKey(help_text='The asset hub this scope/bid belongs to (many-to-one).', on_delete=django.db.models.deletion.PROTECT, related_name='reo_scopes', to='core.assetidhub')),
                ('crm', models.ForeignKey(blank=True, help_text='Optional CRM contact/vendor associated with this scope/bid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reo_scopes', to='core.mastercrm')),
                ('reo_task', models.ForeignKey(blank=True, help_text='Optional link to the related REO task (Trashout/Renovation).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scopes', to='am_module.reotask')),
            ],
            options={
                'verbose_name': 'REO Scope / Bid',
                'verbose_name_plural': 'REO Scopes / Bids',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['asset_hub', 'created_at'], name='am_module_r_asset_h_ddf53b_idx'), models.Index(fields=['asset_hub', 'scope_date'], name='am_module_r_asset_h_8ed2e4_idx'), models.Index(fields=['asset_hub', 'expected_completion'], name='am_module_r_asset_h_21aed1_idx'), models.Index(fields=['asset_hub', 'scope_kind'], name='am_module_r_asset_h_36e1d8_idx'), models.Index(fields=['crm'], name='am_module_r_crm_id_7a81d0_idx'), models.Index(fields=['reo_task'], name='am_module_r_reo_tas_97ef49_idx')],
            },
        ),
    ]
