# Generated by Django 5.2 on 2025-09-30 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0015_reoscope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reoscope',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='reoscope',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='reoscope',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='reoscope',
            name='vendor_name',
        ),
    ]
