# Generated by Django 5.2.5 on 2025-09-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0016_remove_reoscope_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blendedoutcomemodel',
            old_name='month_hoa',
            new_name='total_hoa',
        ),
        migrations.RenameField(
            model_name='blendedoutcomemodel',
            old_name='month_insurance',
            new_name='total_insurance',
        ),
        migrations.RenameField(
            model_name='blendedoutcomemodel',
            old_name='month_other',
            new_name='total_other',
        ),
        migrations.RenameField(
            model_name='blendedoutcomemodel',
            old_name='month_property_tax',
            new_name='total_property_tax',
        ),
        migrations.RenameField(
            model_name='blendedoutcomemodel',
            old_name='month_utility',
            new_name='total_utility',
        ),
    ]
