# Generated by Django 5.2.5 on 2025-09-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0017_rename_month_hoa_blendedoutcomemodel_total_hoa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The purchase price of the asset.', max_digits=15, null=True),
        ),
    ]
