# Generated by Django 5.2.5 on 2025-09-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0018_blendedoutcomemodel_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='cam_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The CAM income.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='interest_collect',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The interest collected.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='mod_down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The modified down payment.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='other_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The other income.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='principal_collect',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The principal collected.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='rental_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The rental income.', max_digits=15, null=True),
        ),
    ]
