# Generated by Django 5.2.5 on 2025-09-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0019_blendedoutcomemodel_cam_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='trashout_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The trashout cost.', max_digits=15, null=True),
        ),
    ]
