# Generated by Django 5.2.5 on 2025-10-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0020_blendedoutcomemodel_trashout_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='The purchase date of the asset.', null=True),
        ),
    ]
