# Generated by Django 5.2.5 on 2025-10-01 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0021_blendedoutcomemodel_purchase_date'),
        ('core', '0007_rename_acq_due_diligence_llcashflowseries_acq_due_diligence_expenses_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sellerboardeddata',
            name='am_module_s_id_c9db5e_idx',
        ),
        migrations.RemoveField(
            model_name='sellerboardeddata',
            name='id',
        ),
        migrations.AlterField(
            model_name='sellerboardeddata',
            name='asset_hub',
            field=models.OneToOneField(default=1, help_text="1:1 with hub; this model's PK equals the hub ID.", on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='am_boarded', serialize=False, to='core.assetidhub'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='sellerboardeddata',
            index=models.Index(fields=['asset_hub'], name='am_module_s_asset_h_c6a65d_idx'),
        ),
    ]
