# Generated by Django 5.2.5 on 2025-10-02 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0022_remove_sellerboardeddata_am_module_s_id_c9db5e_idx_and_more'),
        ('core', '0009_msareference_fcstatus_fctimelines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p0',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p1',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p10',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p11',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p12',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p13',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p14',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p15',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p16',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p17',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p18',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p19',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p2',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p20',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p21',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p22',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p23',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p24',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p25',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p26',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p27',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p28',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p29',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p3',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p30',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p4',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p5',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p6',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p7',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p8',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='cf_p9',
        ),
        migrations.CreateModel(
            name='UWCashFlows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField(help_text='Period number: 0 = acquisition, 1+ = monthly periods')),
                ('period_date', models.DateField(help_text='Month/year of this period (first day of month)')),
                ('net_cash_flow_underwritten', models.DecimalField(blank=True, decimal_places=2, help_text='Projected net cash flow from acquisition model (can be negative)', max_digits=15, null=True)),
                ('net_cash_flow_realized', models.DecimalField(blank=True, decimal_places=2, help_text='Actual net cash flow (calculated from realized line items)', max_digits=15, null=True)),
                ('realized_income_principal', models.DecimalField(blank=True, decimal_places=2, help_text='Principal collected', max_digits=15, null=True)),
                ('realized_income_interest', models.DecimalField(blank=True, decimal_places=2, help_text='Interest collected', max_digits=15, null=True)),
                ('realized_income_rent', models.DecimalField(blank=True, decimal_places=2, help_text='Rent collected', max_digits=15, null=True)),
                ('realized_income_cam', models.DecimalField(blank=True, decimal_places=2, help_text='CAM income', max_digits=15, null=True)),
                ('realized_income_mod_down_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Modification down payment', max_digits=15, null=True)),
                ('realized_net_liquidation_proceeds', models.DecimalField(blank=True, decimal_places=2, help_text='Net proceeds from liquidation', max_digits=15, null=True)),
                ('realized_purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price (period 0 only)', max_digits=15, null=True)),
                ('realized_acq_due_diligence', models.DecimalField(blank=True, decimal_places=2, help_text='Due diligence expenses', max_digits=15, null=True)),
                ('realized_acq_legal', models.DecimalField(blank=True, decimal_places=2, help_text='Acquisition legal expenses', max_digits=15, null=True)),
                ('realized_acq_title', models.DecimalField(blank=True, decimal_places=2, help_text='Title expenses', max_digits=15, null=True)),
                ('realized_expense_servicing', models.DecimalField(blank=True, decimal_places=2, help_text='Servicing fees', max_digits=15, null=True)),
                ('realized_expense_am_fees', models.DecimalField(blank=True, decimal_places=2, help_text='Asset management fees', max_digits=15, null=True)),
                ('realized_expense_property_tax', models.DecimalField(blank=True, decimal_places=2, help_text='Property taxes', max_digits=15, null=True)),
                ('realized_expense_property_insurance', models.DecimalField(blank=True, decimal_places=2, help_text='Property insurance', max_digits=15, null=True)),
                ('realized_legal_foreclosure', models.DecimalField(blank=True, decimal_places=2, help_text='Foreclosure legal fees', max_digits=15, null=True)),
                ('realized_legal_bankruptcy', models.DecimalField(blank=True, decimal_places=2, help_text='Bankruptcy legal fees', max_digits=15, null=True)),
                ('realized_reo_hoa', models.DecimalField(blank=True, decimal_places=2, help_text='HOA fees', max_digits=15, null=True)),
                ('realized_reo_utilities', models.DecimalField(blank=True, decimal_places=2, help_text='Utilities', max_digits=15, null=True)),
                ('realized_reo_renovation', models.DecimalField(blank=True, decimal_places=2, help_text='Renovation costs', max_digits=15, null=True)),
                ('realized_reo_property_preservation', models.DecimalField(blank=True, decimal_places=2, help_text='Property preservation', max_digits=15, null=True)),
                ('realized_cre_marketing', models.DecimalField(blank=True, decimal_places=2, help_text='Marketing expenses', max_digits=15, null=True)),
                ('realized_cre_maintenance', models.DecimalField(blank=True, decimal_places=2, help_text='Maintenance expenses', max_digits=15, null=True)),
                ('is_current_period', models.BooleanField(default=False, help_text="True if this is the current period (based on today's date)")),
                ('notes', models.TextField(blank=True, help_text='Optional notes for this period')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this period record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this period record was last updated')),
                ('asset_hub', models.ForeignKey(help_text='Asset this period belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_periods', to='core.assetidhub')),
            ],
            options={
                'verbose_name': 'UW Cash Flows',
                'verbose_name_plural': 'UW Cash Flows',
                'ordering': ['asset_hub', 'period_number'],
                'indexes': [models.Index(fields=['asset_hub', 'period_number'], name='am_module_u_asset_h_c2b42b_idx'), models.Index(fields=['period_date'], name='am_module_u_period__729b3d_idx')],
                'unique_together': {('asset_hub', 'period_number')},
            },
        ),
    ]
