# Generated by Django 5.2.5 on 2025-10-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0023_remove_blendedoutcomemodel_cf_p0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerboardeddata',
            name='property_type',
            field=models.CharField(blank=True, choices=[('SFR', 'SFR'), ('Manufactured', 'Manufactured'), ('Condo', 'Condo'), ('2-4 Family', '2-4 Family'), ('Land', 'Land'), ('Multifamily 5+', 'Multifamily 5+'), ('Healthcare', 'Healthcare')], default='SFR', help_text='Categorized property type synced with acquisition import definitions.', max_length=100, null=True),
        ),
    ]
