# Generated by Django 5.2 on 2025-10-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0026_alter_sbdailyloandata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerloandata',
            name='reporting_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day of this loan data snapshot (1-31).', null=True),
        ),
    ]
