# Generated by Django 5.2 on 2025-10-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0028_remove_servicerloandata_arm_audit_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerloandata',
            name='investor_id',
            field=models.CharField(blank=True, help_text='Investor ID associated with the loan (stored as text to preserve long identifiers).', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='servicerloandata',
            name='previous_servicer_id',
            field=models.CharField(blank=True, help_text='Previous servicer ID associated with the loan (stored as text to preserve long identifiers).', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='servicerloandata',
            name='servicer_id',
            field=models.CharField(blank=True, help_text='Servicer ID associated with the loan (stored as text to preserve long identifiers).', max_length=64, null=True),
        ),
    ]
