# Generated by Django 5.2.5 on 2025-10-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0029_alter_servicerloandata_investor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='outcome_blend',
            field=models.CharField(blank=True, help_text='The blended outcome of the asset.', max_length=100, null=True),
        ),
    ]
