# Generated by Django 5.2 on 2025-10-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0030_blendedoutcomemodel_outcome_blend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetMetrics',
        ),
    ]
