# Generated by Django 5.2 on 2025-10-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0031_delete_assetmetrics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AMMetricsChange',
        ),
    ]
