# Generated by Django 5.2 on 2025-10-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0032_delete_ammetricschange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerBoardedData',
        ),
    ]
