# Generated by Django 5.2.5 on 2025-10-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0033_delete_sellerboardeddata'),
        ('core', '0026_delete_internalvaluation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='diltask',
            constraint=models.UniqueConstraint(fields=('asset_hub', 'task_type'), name='dil_task_unique_type_per_asset'),
        ),
        migrations.AddConstraint(
            model_name='fctask',
            constraint=models.UniqueConstraint(fields=('asset_hub', 'task_type'), name='fc_task_unique_type_per_asset'),
        ),
        migrations.AddConstraint(
            model_name='modificationtask',
            constraint=models.UniqueConstraint(fields=('asset_hub', 'task_type'), name='modification_task_unique_type_per_asset'),
        ),
        migrations.AddConstraint(
            model_name='reotask',
            constraint=models.UniqueConstraint(fields=('asset_hub', 'task_type'), name='reo_task_unique_type_per_asset'),
        ),
        migrations.AddConstraint(
            model_name='shortsaletask',
            constraint=models.UniqueConstraint(fields=('asset_hub', 'task_type'), name='short_sale_task_unique_type_per_asset'),
        ),
    ]
