# Generated by Django 5.2.5 on 2025-10-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0034_diltask_dil_task_unique_type_per_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diltask',
            name='task_started',
            field=models.DateField(blank=True, help_text='Date when this task was started (defaults to today if not specified).', null=True),
        ),
        migrations.AddField(
            model_name='fctask',
            name='task_started',
            field=models.DateField(blank=True, help_text='Date when this task was started (defaults to today if not specified).', null=True),
        ),
        migrations.AddField(
            model_name='modificationtask',
            name='task_started',
            field=models.DateField(blank=True, help_text='Date when this task was started (defaults to today if not specified).', null=True),
        ),
        migrations.AddField(
            model_name='reotask',
            name='task_started',
            field=models.DateField(blank=True, help_text='Date when this task was started (defaults to today if not specified).', null=True),
        ),
        migrations.AddField(
            model_name='shortsaletask',
            name='task_started',
            field=models.DateField(blank=True, help_text='Date when this task was started (defaults to today if not specified).', null=True),
        ),
    ]
