# Generated by Django 5.2.5 on 2025-10-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0035_diltask_task_started_fctask_task_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcsale',
            name='nod_noi_expire_date',
            field=models.DateField(blank=True, help_text='Date NOI expires (optional).', null=True),
        ),
        migrations.AddField(
            model_name='fcsale',
            name='nod_noi_sent_date',
            field=models.DateField(blank=True, help_text='Date NOI was sent to NOD (optional).', null=True),
        ),
    ]
