# Generated by Django 5.2.5 on 2025-10-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0036_fcsale_nod_noi_expire_date_fcsale_nod_noi_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fctask',
            name='nod_noi_expire_date',
            field=models.DateField(blank=True, help_text='Date NOI expires (optional, for NOD/NOI tasks).', null=True),
        ),
        migrations.AddField(
            model_name='fctask',
            name='nod_noi_sent_date',
            field=models.DateField(blank=True, help_text='Date NOI was sent to NOD (optional, for NOD/NOI tasks).', null=True),
        ),
    ]
