# Generated by Django 5.2.5 on 2025-10-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0037_fctask_nod_noi_expire_date_fctask_nod_noi_sent_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fctask',
            name='nod_noi_expire_date',
        ),
        migrations.RemoveField(
            model_name='fctask',
            name='nod_noi_sent_date',
        ),
    ]
