# Generated by Django 5.2.5 on 2025-10-24 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0038_remove_fctask_nod_noi_expire_date_and_more'),
        ('core', '0027_alter_mastercrm_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcsale',
            name='crm',
        ),
        migrations.CreateModel(
            name='AssetCRMContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, db_index=True, help_text="Role of this contact for this asset (e.g., 'legal', 'servicer', 'broker')", max_length=32, null=True)),
                ('notes', models.TextField(blank=True, help_text="Notes about this contact's involvement with this asset", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_hub', models.ForeignKey(help_text='Asset this contact is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='crm_contacts', to='core.assetidhub')),
                ('crm', models.ForeignKey(help_text='CRM contact associated with this asset', on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='core.mastercrm')),
            ],
            options={
                'verbose_name': 'Asset CRM Contact',
                'verbose_name_plural': 'Asset CRM Contacts',
                'db_table': 'am_asset_crm_contact',
                'ordering': ['role', 'created_at'],
                'indexes': [models.Index(fields=['asset_hub', 'role'], name='am_asset_cr_asset_h_bc8952_idx'), models.Index(fields=['crm', 'role'], name='am_asset_cr_crm_id_93ed08_idx')],
                'unique_together': {('asset_hub', 'crm', 'role')},
            },
        ),
    ]
