# Generated by Django 5.2.5 on 2025-10-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0039_remove_fcsale_crm_assetcrmcontact'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reoscope',
            name='am_module_r_crm_id_7a81d0_idx',
        ),
        migrations.RemoveField(
            model_name='dil',
            name='crm',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='crm',
        ),
        migrations.RemoveField(
            model_name='reodata',
            name='crm',
        ),
        migrations.RemoveField(
            model_name='reoscope',
            name='crm',
        ),
        migrations.RemoveField(
            model_name='shortsale',
            name='crm',
        ),
    ]
