# Generated by Django 5.2 on 2025-10-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0042_sbdailycommentdata_sbdailypayhistorydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBDailyTransactionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('loan_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('previous_ln_num', models.CharField(blank=True, max_length=50, null=True)),
                ('loan_transaction_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('transaction_date', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('transaction_code', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_description', models.CharField(blank=True, max_length=255, null=True)),
                ('effective_date', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_amt', models.CharField(blank=True, max_length=50, null=True)),
                ('due_date', models.CharField(blank=True, max_length=20, null=True)),
                ('principal_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('interest_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('suspense_paid', models.CharField(blank=True, max_length=50, null=True)),
                ('non_recoverable_advance', models.CharField(blank=True, max_length=50, null=True)),
                ('recoverable_advance', models.CharField(blank=True, max_length=50, null=True)),
                ('corporate_advance_reason_code', models.CharField(blank=True, max_length=50, null=True)),
                ('escrow_advance_balance', models.CharField(blank=True, max_length=50, null=True)),
                ('escrow_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('restricted_escrow', models.CharField(blank=True, max_length=10, null=True)),
                ('fee_code', models.CharField(blank=True, max_length=50, null=True)),
                ('fee_description', models.CharField(blank=True, max_length=255, null=True)),
                ('unapplied_pmt', models.CharField(blank=True, max_length=50, null=True)),
                ('stipulation_unapplied_pmt', models.CharField(blank=True, max_length=50, null=True)),
                ('pre_petition_unapplied_pmt', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'StateBridge Daily Transaction Data',
                'verbose_name_plural': 'StateBridge Daily Transaction Data',
                'db_table': 'transaction_records',
                'indexes': [models.Index(fields=['loan_id'], name='transaction_loan_id_a1ee8f_idx'), models.Index(fields=['previous_ln_num'], name='transaction_previou_ab528a_idx'), models.Index(fields=['loan_transaction_id'], name='transaction_loan_tr_9256e6_idx'), models.Index(fields=['transaction_date'], name='transaction_transac_75c4f7_idx'), models.Index(fields=['transaction_code'], name='transaction_transac_c919df_idx'), models.Index(fields=['effective_date'], name='transaction_effecti_56902d_idx'), models.Index(fields=['due_date'], name='transaction_due_dat_ac2d63_idx'), models.Index(fields=['loan_id', 'transaction_date'], name='transaction_loan_id_cf33b5_idx')],
                'unique_together': {('loan_id', 'loan_transaction_id', 'transaction_date')},
            },
        ),
    ]
