# Generated by Django 5.2 on 2025-10-25 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0043_sbdailytransactiondata'),
        ('core', '0027_alter_mastercrm_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortsale',
            name='gross_proceeds',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross proceeds of the short sale (optional).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shortsale',
            name='settlement_date',
            field=models.DateField(blank=True, help_text='Settlement date of the short sale (optional).', null=True),
        ),
        migrations.AddField(
            model_name='shortsale',
            name='short_sale_list_date',
            field=models.DateField(blank=True, help_text='Date of the short sale list (optional).', null=True),
        ),
        migrations.AddField(
            model_name='shortsale',
            name='short_sale_list_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='List price of the short sale (optional).', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_source', models.CharField(choices=[('short_sale', 'Short Sale'), ('reo', 'REO')], help_text='Which track this offer came from', max_length=20)),
                ('offer_price', models.DecimalField(decimal_places=2, help_text='Offered purchase price', max_digits=12)),
                ('offer_date', models.DateField(help_text='Date offer was received')),
                ('seller_credits', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Seller credits/concessions offered', max_digits=10, null=True)),
                ('financing_type', models.CharField(choices=[('cash', 'Cash'), ('conventional', 'Conventional Financing'), ('fha', 'FHA Financing'), ('va', 'VA Financing'), ('usda', 'USDA Financing'), ('hard_money', 'Hard Money'), ('other', 'Other Financing')], help_text='Type of financing for this offer', max_length=20)),
                ('buyer_name', models.CharField(help_text='Name of buyer making offer', max_length=200)),
                ('buyer_agent', models.CharField(blank=True, help_text="Buyer's real estate agent (optional)", max_length=200, null=True)),
                ('offer_status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('countered', 'Counter Offer Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='pending', help_text='Current status of this offer', max_length=20)),
                ('expiration_date', models.DateField(blank=True, help_text='Date offer expires (optional)', null=True)),
                ('closing_date', models.DateField(blank=True, help_text='Proposed closing date (optional)', null=True)),
                ('earnest_money', models.DecimalField(blank=True, decimal_places=2, help_text='Earnest money deposit amount (optional)', max_digits=10, null=True)),
                ('inspection_period_days', models.PositiveIntegerField(blank=True, help_text='Number of days for inspection period (optional)', null=True)),
                ('financing_contingency_days', models.PositiveIntegerField(blank=True, help_text='Number of days for financing contingency (optional)', null=True)),
                ('appraisal_contingency', models.BooleanField(default=True, help_text='Whether offer includes appraisal contingency')),
                ('special_terms', models.TextField(blank=True, help_text='Any special terms or conditions (optional)', null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes about this offer (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='User who created this offer record', max_length=100, null=True)),
                ('asset_hub', models.ForeignKey(help_text='Asset this offer is for', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.assetidhub')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-offer_date', '-created_at'],
                'indexes': [models.Index(fields=['asset_hub', 'offer_status'], name='am_module_o_asset_h_9e82e2_idx'), models.Index(fields=['offer_source', 'offer_status'], name='am_module_o_offer_s_e5ad8c_idx'), models.Index(fields=['offer_date'], name='am_module_o_offer_d_6c50ba_idx')],
            },
        ),
    ]
