# Generated by Django 5.2 on 2025-10-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0044_shortsale_gross_proceeds_shortsale_settlement_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortsale',
            name='settlement_date',
        ),
        migrations.AlterField(
            model_name='offers',
            name='buyer_name',
            field=models.CharField(blank=True, help_text='Name of buyer making offer (optional)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='financing_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('conventional', 'Conventional Financing'), ('fha', 'FHA Financing'), ('va', 'VA Financing'), ('usda', 'USDA Financing'), ('hard_money', 'Hard Money'), ('other', 'Other Financing')], help_text='Type of financing for this offer (optional)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='offer_date',
            field=models.DateField(blank=True, help_text='Date offer was received (optional)', null=True),
        ),
    ]
