# Generated by Django 5.2 on 2025-10-26 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0045_make_offer_fields_nullable'),
        ('core', '0027_alter_mastercrm_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='reoscope',
            name='crm',
            field=models.ForeignKey(blank=True, help_text='Vendor/contractor who provided this scope/bid (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reo_scopes', to='core.mastercrm'),
        ),
    ]
