# Generated by Django 5.2.5 on 2025-10-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0046_add_crm_to_reoscope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modificationtask',
            name='task_type',
            field=models.CharField(choices=[('mod_drafted', 'Drafted'), ('mod_executed', 'Executed'), ('mod_rpl', 'Re-Performing'), ('mod_failed', 'Failed')], help_text='Modification workflow stage for this task.', max_length=32),
        ),
    ]
