# Generated by Django 5.2.5 on 2025-10-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0047_alter_modificationtask_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diltask',
            name='task_type',
            field=models.CharField(choices=[('owner_contacted', 'Owner/Heirs contacted'), ('no_cooperation', 'No Cooperation'), ('dil_drafted', 'Drafted'), ('dil_executed', 'Executed')], help_text='DIL workflow stage for this task.', max_length=32),
        ),
    ]
