# Generated by Django 5.2 on 2025-10-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0048_alter_diltask_task_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sbdailycommentdata',
            unique_together=set(),
        ),
    ]
