# Generated by Django 5.2 on 2025-10-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0049_alter_sbdailycommentdata_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sbdailybankruptcydata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sbdailyforeclosuredata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sbdailyloandata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sbdailypayhistorydata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sbdailytransactiondata',
            unique_together=set(),
        ),
    ]
