# Generated by Django 5.2 on 2025-10-30 04:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0050_alter_sbdailybankruptcydata_unique_together_and_more'),
        ('core', '0035_statereference_broker_closing_cost_fees_avg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ammetrics',
            name='final_proceeds',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final gross liquidation proceeds from any outcome track (REO, Short Sale, FC, etc.)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ammetrics',
            name='proceeds_date',
            field=models.DateField(blank=True, help_text='Date when final proceeds were realized', null=True),
        ),
        migrations.AddField(
            model_name='ammetrics',
            name='proceeds_source',
            field=models.CharField(blank=True, choices=[('reo', 'REO Sale'), ('short_sale', 'Short Sale'), ('foreclosure', 'Foreclosure Sale'), ('dil', 'Deed in Lieu'), ('modification', 'Loan Modification'), ('other', 'Other')], help_text='Which outcome track generated the final proceeds', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modification',
            name='note_sale_date',
            field=models.DateField(blank=True, help_text='Date of the note sale (optional).', null=True),
        ),
        migrations.AddField(
            model_name='modification',
            name='note_sale_proceeds',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross proceeds from note sale (when modification track leads to note sale).', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='modificationtask',
            name='task_type',
            field=models.CharField(choices=[('mod_drafted', 'Drafted'), ('mod_executed', 'Executed'), ('mod_rpl', 'Re-Performing'), ('mod_failed', 'Failed'), ('note_sale', 'Note Sale')], help_text='Modification workflow stage for this task.', max_length=32),
        ),
        migrations.AddIndex(
            model_name='ammetrics',
            index=models.Index(fields=['asset_hub', 'final_proceeds'], name='am_module_a_asset_h_a8888b_idx'),
        ),
        migrations.AddIndex(
            model_name='ammetrics',
            index=models.Index(fields=['proceeds_source', 'final_proceeds'], name='am_module_a_proceed_0739a1_idx'),
        ),
        migrations.AddIndex(
            model_name='ammetrics',
            index=models.Index(fields=['proceeds_date'], name='am_module_a_proceed_ca605f_idx'),
        ),
    ]
