# Generated by Django 5.2.5 on 2025-11-05 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0051_ammetrics_final_proceeds_ammetrics_proceeds_date_and_more'),
        ('core', '0044_lltransactionsummary_gross_purchase_price_realized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammetrics',
            name='proceeds_source',
            field=models.CharField(blank=True, choices=[('reo', 'REO Sale'), ('short_sale', 'Short Sale'), ('foreclosure', 'Foreclosure Sale'), ('dil', 'Deed in Lieu'), ('modification', 'Loan Modification'), ('note_sale', 'Note Sale'), ('other', 'Other')], help_text='Which outcome track generated the final proceeds', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amnote',
            name='context_outcome',
            field=models.CharField(blank=True, choices=[('dil', 'Deed-in-Lieu'), ('fc', 'Foreclosure'), ('reo', 'REO'), ('short_sale', 'Short Sale'), ('modification', 'Modification'), ('note_sale', 'Note Sale')], help_text='Outcome context this note relates to (nullable for asset-level notes).', max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='NoteSale',
            fields=[
                ('asset_hub', models.OneToOneField(help_text='1:1 with hub; Note Sale keyed by AssetIdHub.', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='note_sale', serialize=False, to='core.assetidhub')),
                ('sold_date', models.DateField(blank=True, help_text='Date when the note was sold (optional).', null=True)),
                ('proceeds', models.DecimalField(blank=True, decimal_places=2, help_text='Gross proceeds received from the note sale (optional).', max_digits=12, null=True)),
                ('trading_partner', models.ForeignKey(blank=True, help_text="Trading partner who purchased the note (optional, filtered by tag='trading_partner').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_sales', to='core.mastercrm')),
            ],
            options={
                'verbose_name': 'Note Sale',
                'verbose_name_plural': 'Note Sales',
            },
        ),
        migrations.CreateModel(
            name='NoteSaleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('potential_note_sale', 'Potential Note Sale'), ('out_to_market', 'Out to Market'), ('pending_sale', 'Pending Sale'), ('sold', 'Sold')], help_text='Note Sale workflow stage for this task.', max_length=32)),
                ('task_started', models.DateField(blank=True, help_text='Date when this task was started (defaults to today if not specified).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this task was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this task was last updated.')),
                ('asset_hub', models.ForeignKey(help_text='The asset hub this note sale task belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='note_sale_tasks', to='core.assetidhub')),
                ('note_sale', models.ForeignKey(help_text='The NoteSale record this task is associated with (many-to-one).', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='am_module.notesale')),
            ],
            options={
                'verbose_name': 'Note Sale Task',
                'verbose_name_plural': 'Note Sale Tasks',
                'constraints': [models.UniqueConstraint(fields=('asset_hub', 'task_type'), name='note_sale_task_unique_type_per_asset')],
            },
        ),
    ]
