# Generated by Django 5.2.5 on 2025-11-06 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0052_alter_ammetrics_proceeds_source_and_more'),
        ('core', '0044_lltransactionsummary_gross_purchase_price_realized'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='trading_partner',
            field=models.ForeignKey(blank=True, help_text='Trading partner who made the offer (for note sale offers only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_sale_offers', to='core.mastercrm'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='offer_source',
            field=models.CharField(choices=[('short_sale', 'Short Sale'), ('reo', 'REO'), ('note_sale', 'Note Sale')], help_text='Which track this offer came from', max_length=20),
        ),
    ]
