# Generated by Django 5.2.5 on 2025-11-06 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0053_offers_trading_partner_alter_offers_offer_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesale',
            name='sold_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Date when the note was sold (defaults to today).', null=True),
        ),
    ]
