# Generated by Django 5.2.5 on 2025-11-06 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0054_add_sold_date_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diltask',
            name='task_started',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Date when this task was started (defaults to today).', null=True),
        ),
        migrations.AlterField(
            model_name='fctask',
            name='task_started',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Date when this task was started (defaults to today).', null=True),
        ),
        migrations.AlterField(
            model_name='modificationtask',
            name='task_started',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Date when this task was started (defaults to today).', null=True),
        ),
        migrations.AlterField(
            model_name='reotask',
            name='task_started',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Date when this task was started (defaults to today).', null=True),
        ),
        migrations.AlterField(
            model_name='shortsaletask',
            name='task_started',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Date when this task was started (defaults to today).', null=True),
        ),
    ]
