# Generated by Django 5.2.5 on 2025-11-06 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0055_add_task_started_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesaletask',
            name='task_started',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Date when this task was started (defaults to today).', null=True),
        ),
    ]
