# Generated by Django 5.2.5 on 2025-11-06 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0056_add_notesale_task_started_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diltask',
            name='task_started',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Date when this task was started (defaults to today).', null=True),
        ),
        migrations.AlterField(
            model_name='fctask',
            name='task_started',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Date when this task was started (defaults to today).', null=True),
        ),
        migrations.AlterField(
            model_name='modificationtask',
            name='task_started',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Date when this task was started (defaults to today).', null=True),
        ),
        migrations.AlterField(
            model_name='notesale',
            name='sold_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Date when the note was sold (defaults to today).', null=True),
        ),
        migrations.AlterField(
            model_name='reotask',
            name='task_started',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Date when this task was started (defaults to today).', null=True),
        ),
        migrations.AlterField(
            model_name='shortsaletask',
            name='task_started',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Date when this task was started (defaults to today).', null=True),
        ),
    ]
