# Generated by Django 5.2.5 on 2025-11-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0057_fix_date_defaults_use_date_not_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diltask',
            name='task_type',
            field=models.CharField(choices=[('pursuing_dil', 'Pursuing DIL'), ('owner_contacted', 'Owner/Heirs contacted'), ('dil_failed', 'DIL Failed'), ('dil_drafted', 'Drafted'), ('dil_executed', 'Executed')], help_text='DIL workflow stage for this task.', max_length=32),
        ),
    ]
