# Generated by Django 5.2.5 on 2025-11-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0058_refactor_dil_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blendedoutcomemodel',
            old_name='am_fees',
            new_name='fund_am_fees',
        ),
        migrations.RenameField(
            model_name='blendedoutcomemodel',
            old_name='other_fc_fees',
            new_name='outher_fc_fees',
        ),
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='am_liq_fees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The total liq fees.', max_digits=15, null=True),
        ),
    ]
