# Generated by Django 5.2.5 on 2025-11-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0059_rename_am_fees_blendedoutcomemodel_fund_am_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='expected_hold_duration',
            field=models.IntegerField(blank=True, help_text='Expected hold duration (in months).', null=True),
        ),
    ]
