# Generated by Django 5.2.5 on 2025-11-24 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0060_blendedoutcomemodel_expected_hold_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='fc_legal_fees',
        ),
        migrations.RemoveField(
            model_name='blendedoutcomemodel',
            name='outher_fc_fees',
        ),
    ]
