# Generated by Django 5.2.5 on 2025-11-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0061_remove_blendedoutcomemodel_fc_legal_fees_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='uwcashflows',
            name='am_module_u_asset_h_c2b42b_idx',
        ),
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='fc_legal_fees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The total FC legal fees.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='other_fc_fees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The total other FC fees.', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='blendedoutcomemodel',
            name='servicing_120d',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The total 120 day servicing costs.', max_digits=15, null=True),
        ),
    ]
