# Generated by Django 5.2.5 on 2025-11-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0062_remove_uwcashflows_am_module_u_asset_h_c2b42b_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blendedoutcomemodel',
            old_name='acq_costs',
            new_name='fund_acq_fee',
        ),
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='due_diligence',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The total due diligence costs.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='legal_costs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The total legal costs.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='other_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The total title fees.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='taxtitle_fees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The total transfer fees.', max_digits=15, null=True),
        ),
    ]
