# Generated by Django 5.2.5 on 2025-11-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0063_rename_acq_costs_blendedoutcomemodel_fund_acq_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blendedoutcomemodel',
            old_name='broker_fees',
            new_name='broker_closing_fees',
        ),
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='broker_acq_fees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The total broker fees.', max_digits=15, null=True),
        ),
    ]
