# Generated by Django 5.2 on 2025-12-12 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "etl",
            "0009_add_sbdailyloandata_from_am_module",
        ),
        (
            "am_module",
            "0064_rename_broker_fees_blendedoutcomemodel_broker_closing_fees_and_more",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="servicerloandata",
                    name="raw_source_snapshot",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Links to the specific SBDailyLoanData snapshot this cleaned record was derived from for provenance tracking.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cleaned_records",
                        to="etl.sbdailyloandata",
                    ),
                ),
                migrations.DeleteModel(
                    name="SBDailyLoanData",
                ),
            ],
        )
    ]
