# Generated by Django 5.2 on 2025-12-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0010_add_statebridge_raw_models_from_am_module"),
        ("am_module", "0065_move_sbdailyloandata_to_etl"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="SBDailyForeclosureData"),
                migrations.DeleteModel(name="SBDailyBankruptcyData"),
                migrations.DeleteModel(name="SBDailyCommentData"),
                migrations.DeleteModel(name="SBDailyPayHistoryData"),
                migrations.DeleteModel(name="SBDailyTransactionData"),
            ],
        )
    ]
