# Generated by Django 5.2.5 on 2026-01-02 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0067_servicerarmdata_servicerbankruptcydata_and_more'),
        ('core', '0095_remove_core_borrower_pii_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amnote',
            options={'ordering': ['-pinned', '-created_at'], 'verbose_name': 'AM Note', 'verbose_name_plural': 'AM Notes'},
        ),
        migrations.RemoveIndex(
            model_name='amnote',
            name='am_module_a_asset_h_a56c46_idx',
        ),
        migrations.RemoveIndex(
            model_name='amnote',
            name='am_module_a_asset_h_81ea49_idx',
        ),
        migrations.RemoveIndex(
            model_name='amnote',
            name='am_module_a_asset_h_8c9eb1_idx',
        ),
        migrations.RemoveIndex(
            model_name='amnote',
            name='am_module_a_asset_h_e8e82b_idx',
        ),
        migrations.RemoveField(
            model_name='amnote',
            name='context_outcome',
        ),
        migrations.RemoveField(
            model_name='amnote',
            name='context_task_id',
        ),
        migrations.RemoveField(
            model_name='amnote',
            name='context_task_type',
        ),
        migrations.RemoveField(
            model_name='amnote',
            name='scope',
        ),
        migrations.AlterField(
            model_name='amnote',
            name='asset_hub',
            field=models.ForeignKey(default=1, help_text='Asset this note is attached to', on_delete=django.db.models.deletion.PROTECT, related_name='am_notes', to='core.assetidhub'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amnote',
            name='body',
            field=models.TextField(help_text='Note content'),
        ),
        migrations.AlterField(
            model_name='amnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When note was created'),
        ),
        migrations.AlterField(
            model_name='amnote',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_am_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='amnote',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Pin note to top of list'),
        ),
        migrations.AlterField(
            model_name='amnote',
            name='tag',
            field=models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('legal', 'Legal'), ('qc', 'Quality Control'), ('ops', 'Operations'), ('info', 'Info')], help_text='Optional category tag (references core.models.NoteTag)', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='amnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When note was last updated'),
        ),
        migrations.AlterField(
            model_name='amnote',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_am_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='amnote',
            index=models.Index(fields=['asset_hub', '-created_at'], name='am_note_asset_h_599efb_idx'),
        ),
        migrations.AddIndex(
            model_name='amnote',
            index=models.Index(fields=['asset_hub', 'pinned', '-created_at'], name='am_note_asset_h_780e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='amnote',
            index=models.Index(fields=['tag', '-created_at'], name='am_note_tag_d5582c_idx'),
        ),
        migrations.AlterModelTable(
            name='amnote',
            table='am_note',
        ),
    ]
