# Generated by Django 5.2.5 on 2026-01-03 01:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0068_alter_amnote_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amnote',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When note was created'),
        ),
    ]
