# Generated by Django 5.2.5 on 2026-01-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0069_alter_amnote_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dil',
            name='contact_address',
            field=models.TextField(blank=True, help_text='Mailing address of borrower or heir contact.', null=True),
        ),
        migrations.AddField(
            model_name='dil',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email address of borrower or heir contact.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='dil',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Name of borrower or heir contact.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dil',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Phone number of borrower or heir contact.', max_length=20, null=True),
        ),
    ]
