# Generated by Django 5.2.5 on 2026-01-03 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0070_add_dil_contact_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dil',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='dil',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='dil',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='dil',
            name='contact_phone',
        ),
        migrations.CreateModel(
            name='HeirContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(help_text='Name of borrower or heir contact.', max_length=255)),
                ('contact_phone', models.CharField(blank=True, help_text='Phone number of borrower or heir contact.', max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Email address of borrower or heir contact.', max_length=254, null=True)),
                ('contact_address', models.TextField(blank=True, help_text='Mailing address of borrower or heir contact.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this contact was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this contact was last updated.')),
                ('dil_task', models.ForeignKey(help_text='The DIL task this contact is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='heir_contacts', to='am_module.diltask')),
            ],
            options={
                'verbose_name': 'Heir Contact',
                'verbose_name_plural': 'Heir Contacts',
                'ordering': ['created_at'],
            },
        ),
    ]
