# Generated by Django 5.2.5 on 2026-01-03 05:52

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0071_remove_dil_contacts_add_heircontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heircontact',
            name='contact_address',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, help_text='Mailing address of borrower or heir contact (encrypted).', null=True),
        ),
        migrations.AlterField(
            model_name='heircontact',
            name='contact_email',
            field=encrypted_fields.fields.EncryptedEmailField(blank=True, help_text='Email address of borrower or heir contact (encrypted).', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='heircontact',
            name='contact_name',
            field=encrypted_fields.fields.EncryptedCharField(help_text='Name of borrower or heir contact (encrypted).', max_length=255),
        ),
        migrations.AlterField(
            model_name='heircontact',
            name='contact_phone',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Phone number of borrower or heir contact (encrypted).', max_length=20, null=True),
        ),
    ]
