# Generated by Django 5.2.5 on 2026-01-06 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0073_amprojections'),
        ('core', '0095_remove_core_borrower_pii_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReUWAMProjections',
            fields=[
                ('asset_hub', models.OneToOneField(help_text="1:1 with hub; this model's PK equals the hub ID.", on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='reuw_am_projections', serialize=False, to='core.assetidhub')),
                ('reuw_projected_gross_proceeds', models.DecimalField(blank=True, decimal_places=2, help_text='Re-underwritten projected gross liquidation proceeds (currency).', max_digits=15, null=True)),
                ('reuw_projected_net_proceeds', models.DecimalField(blank=True, decimal_places=2, help_text='Re-underwritten projected net liquidation proceeds (gross - closing costs).', max_digits=15, null=True)),
                ('reuw_projected_liq_date', models.DateField(blank=True, help_text='Re-underwritten projected liquidation date (if known).', null=True)),
                ('reuw_projection_notes', models.TextField(blank=True, help_text='Optional notes about factors influencing this re-underwriting projection.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this projection record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this projection record was last updated.')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this re-underwriting projection (if known).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_reuw_am_projections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Re-UW AM Projections',
                'verbose_name_plural': 'Re-UW AM Projections',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='AMProjections',
        ),
        migrations.AddIndex(
            model_name='reuwamprojections',
            index=models.Index(fields=['reuw_projected_liq_date'], name='am_module_r_reuw_pr_4eb9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='reuwamprojections',
            index=models.Index(fields=['updated_at'], name='am_module_r_updated_4c7208_idx'),
        ),
    ]
