# Generated by Django 5.2.5 on 2026-01-06 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0074_reuwamprojections_delete_amprojections_and_more'),
        ('core', '0095_remove_core_borrower_pii_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AMNoteSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_data', models.JSONField(default=dict, help_text='Structured summary data containing summary_text, bullets, and metadata')),
                ('notes_hash', models.CharField(db_index=True, help_text='Hash of note IDs and timestamps to detect changes', max_length=64)),
                ('generated_at', models.DateTimeField(auto_now=True, help_text='When this summary was last generated')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this summary record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this summary record was last updated')),
                ('asset_hub', models.OneToOneField(help_text='Asset hub this summary belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='note_summary', to='core.assetidhub')),
                ('generated_by', models.ForeignKey(blank=True, help_text='User/system that generated this summary (usually null for auto-generated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_note_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AM Note Summary',
                'verbose_name_plural': 'AM Note Summaries',
                'db_table': 'am_note_summary',
                'indexes': [models.Index(fields=['asset_hub'], name='am_note_sum_asset_h_b7bd47_idx'), models.Index(fields=['notes_hash'], name='am_note_sum_notes_h_6e2407_idx'), models.Index(fields=['-generated_at'], name='am_note_sum_generat_b639e7_idx')],
            },
        ),
    ]
