# Generated by Django 5.2.5 on 2026-01-12 18:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0075_amnotesummary'),
        ('core', '0100_simplify_calendar_event_to_tasks_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelinquentTrack',
            fields=[
                ('asset_hub', models.OneToOneField(help_text='1:1 with hub; Delinquent Track keyed by AssetIdHub.', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='delinquent_track', serialize=False, to='core.assetidhub')),
            ],
            options={
                'verbose_name': 'Delinquent Track',
                'verbose_name_plural': 'Delinquent Tracks',
            },
        ),
        migrations.CreateModel(
            name='PerformingTrack',
            fields=[
                ('asset_hub', models.OneToOneField(help_text='1:1 with hub; Performing Track keyed by AssetIdHub.', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='performing_track', serialize=False, to='core.assetidhub')),
            ],
            options={
                'verbose_name': 'Performing Track',
                'verbose_name_plural': 'Performing Tracks',
            },
        ),
        migrations.CreateModel(
            name='DelinquentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('dq_30', '30 Days Delinquent'), ('dq_60', '60 Days Delinquent'), ('dq_90', '90 Days Delinquent'), ('dq_120_plus', '120+ Days Delinquent'), ('loss_mit', 'Loss Mit'), ('fc_dil', 'FC/DIL')], help_text='Delinquent workflow stage for this task.', max_length=32)),
                ('task_started', models.DateField(blank=True, default=datetime.date.today, help_text='Date when this task was started (defaults to today).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this task was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this task was last updated.')),
                ('asset_hub', models.ForeignKey(help_text='The asset hub this delinquent task belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='delinquent_tasks', to='core.assetidhub')),
                ('delinquent_track', models.ForeignKey(help_text='The DelinquentTrack record this task is associated with (many-to-one).', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='am_module.delinquenttrack')),
            ],
            options={
                'verbose_name': 'Delinquent Task',
                'verbose_name_plural': 'Delinquent Tasks',
                'constraints': [models.UniqueConstraint(fields=('asset_hub', 'task_type'), name='delinquent_task_unique_type_per_asset')],
            },
        ),
        migrations.CreateModel(
            name='PerformingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('perf', 'Performing'), ('rpl', 'Re-Performing (RPL)'), ('note_sold', 'Note Sold')], help_text='Performing workflow stage for this task.', max_length=32)),
                ('task_started', models.DateField(blank=True, default=datetime.date.today, help_text='Date when this task was started (defaults to today).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this task was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this task was last updated.')),
                ('asset_hub', models.ForeignKey(help_text='The asset hub this performing task belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='performing_tasks', to='core.assetidhub')),
                ('performing_track', models.ForeignKey(help_text='The PerformingTrack record this task is associated with (many-to-one).', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='am_module.performingtrack')),
            ],
            options={
                'verbose_name': 'Performing Task',
                'verbose_name_plural': 'Performing Tasks',
                'constraints': [models.UniqueConstraint(fields=('asset_hub', 'task_type'), name='performing_task_unique_type_per_asset')],
            },
        ),
    ]
