# Generated by Django 5.2.5 on 2026-01-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0076_delinquenttrack_performingtrack_delinquenttask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reotask',
            name='task_type',
            field=models.CharField(choices=[('eviction', 'Eviction'), ('trashout', 'Trashout'), ('renovation', 'Renovation'), ('pre_marketing', 'Pre-Marketing'), ('listed', 'Listed'), ('under_contract', 'Under Contract'), ('sold', 'Sold')], help_text='Type of REO task (Eviction, Trashout, Renovation, Pre-Marketing, Listed, Under Contract, Sold).', max_length=20),
        ),
    ]
