# Generated by Django 5.2.5 on 2026-01-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0077_update_reo_task_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delinquenttask',
            name='task_type',
            field=models.CharField(choices=[('dq_30', '30 DLQ'), ('dq_60', '60 DLQ'), ('dq_90', '90 DLQ'), ('dq_120_plus', '120+ DLQ'), ('loss_mit', 'Loss Mit'), ('fc_dil', 'FC/DIL')], help_text='Delinquent workflow stage for this task.', max_length=32),
        ),
    ]
