# Generated by Django 5.2.5 on 2026-01-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0079_custom_asset_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='blendedoutcomemodel',
            name='expected_gross_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The expected gross cost.', max_digits=15, null=True),
        ),
    ]
