# Generated by Django 5.2.5 on 2026-01-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0080_blendedoutcomemodel_expected_gross_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blendedoutcomemodel',
            name='expected_gross_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The expected gross cost (purchase price + acquisition costs).', max_digits=15, null=True),
        ),
    ]
