# Generated by Cascade on 2026-01-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0081_alter_blendedoutcomemodel_expected_gross_cost'),
        ('core', '0101_assetdetails_asset_class'),
        ('etl', '0018_remove_tradesettlementstatementetl_currency_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicerTrialBalanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_date', models.DateField(blank=True, db_index=True, null=True)),
                ('loan_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('investor_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('investor_loan_id', models.CharField(blank=True, max_length=50, null=True)),
                ('borrower_name', models.CharField(blank=True, max_length=150, null=True)),
                ('principal_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('escrow_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('other_funds_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('late_charge_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('legal_fee_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('deferred_prin', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('unapplied_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('loss_draft_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('asst_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('nsf_fee_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('oth_fee_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('deferred_int', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('primary_status', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('loan_type', models.CharField(blank=True, max_length=50, null=True)),
                ('legal_status', models.CharField(blank=True, max_length=50, null=True)),
                ('warning_status', models.CharField(blank=True, max_length=50, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('date_inactive', models.DateField(blank=True, null=True)),
                ('asset_hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.assetidhub')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('raw_source_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaned_records', to='etl.eomtrialbalancedata')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicer Trial Balance Data',
                'verbose_name_plural': 'Servicer Trial Balance Data',
                'db_table': 'am_servicer_trial_balance_data',
                'indexes': [
                    models.Index(fields=['asset_hub'], name='am_trial_asset_hub_idx'),
                    models.Index(fields=['file_date'], name='am_trial_file_date_idx'),
                    models.Index(fields=['loan_id'], name='am_trial_loan_id_idx'),
                    models.Index(fields=['investor_id'], name='am_trial_investor_id_idx'),
                    models.Index(fields=['primary_status'], name='am_trial_status_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('file_date', 'loan_id'), name='uniq_am_trial_fdate_loanid'),
                ],
            },
        ),
    ]
