# Generated by Django 5.2.5 on 2026-01-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0082_servicertrialbalancedata'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='servicertrialbalancedata',
            new_name='am_servicer_asset_h_d9f1d6_idx',
            old_name='am_trial_asset_hub_idx',
        ),
        migrations.RenameIndex(
            model_name='servicertrialbalancedata',
            new_name='am_servicer_file_da_e2ae6a_idx',
            old_name='am_trial_file_date_idx',
        ),
        migrations.RenameIndex(
            model_name='servicertrialbalancedata',
            new_name='am_servicer_loan_id_82c311_idx',
            old_name='am_trial_loan_id_idx',
        ),
        migrations.RenameIndex(
            model_name='servicertrialbalancedata',
            new_name='am_servicer_investo_77e702_idx',
            old_name='am_trial_investor_id_idx',
        ),
        migrations.RenameIndex(
            model_name='servicertrialbalancedata',
            new_name='am_servicer_primary_10a859_idx',
            old_name='am_trial_status_idx',
        ),
    ]
