# Generated by Cascade on 2026-01-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0082_servicertrialbalancedata'),
        ('core', '0101_assetdetails_asset_class'),
        ('etl', '0019_eomtrackingpayoffdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicerTrackingPayoffData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_date', models.DateField(blank=True, db_index=True, null=True)),
                ('loan_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('investor_loan_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('received_date', models.DateField(blank=True, db_index=True, null=True)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('principal_paid_off', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('interest_collected', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sf_collected', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('net_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('payoff_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.assetidhub')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('raw_source_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaned_records', to='etl.eomtrackingpayoffdata')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicer Tracking Payoff Data',
                'verbose_name_plural': 'Servicer Tracking Payoff Data',
                'db_table': 'am_servicer_tracking_payoff_data',
                'indexes': [
                    models.Index(fields=['asset_hub'], name='am_track_asset_hub_idx'),
                    models.Index(fields=['file_date'], name='am_track_file_date_idx'),
                    models.Index(fields=['loan_id'], name='am_track_loan_id_idx'),
                    models.Index(fields=['received_date'], name='am_track_received_date_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('file_date', 'loan_id'), name='uniq_am_trackpay_fdate_loanid'),
                ],
            },
        ),
    ]
