# Generated by Django 5.2.5 on 2026-01-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('am_module', '0083_rename_am_trial_asset_hub_idx_am_servicer_asset_h_d9f1d6_idx_and_more'),
        ('am_module', '0083_servicertrackingpayoffdata'),
    ]

    operations = [
    ]
