# Generated by Django 5.2.5 on 2026-01-30 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerPortalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Opaque portal token used in public URL.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='When this portal token expires.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('broker', models.ForeignKey(help_text='Broker this portal token is issued for.', on_delete=django.db.models.deletion.CASCADE, related_name='portal_tokens', to='core.mastercrm')),
            ],
            options={
                'verbose_name': 'Broker Portal Token',
                'verbose_name_plural': 'Broker Portal Tokens',
                'db_table': 'user_admin_broker_portal_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['broker'], name='user_admin__broker__253327_idx'), models.Index(fields=['expires_at'], name='user_admin__expires_af3abf_idx')],
            },
        ),
        migrations.CreateModel(
            name='BrokerTokenAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Opaque invite token used in public URL.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='When this token expires.')),
                ('single_use', models.BooleanField(default=True, help_text='If true, lock after first successful submit.')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the token was first used to submit values.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('asset_hub', models.ForeignKey(help_text='Asset hub ID this token is for (hub-first architecture).', on_delete=django.db.models.deletion.CASCADE, related_name='broker_tokens', to='core.assetidhub')),
                ('broker', models.ForeignKey(blank=True, help_text='Directory record of the broker this token is intended for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_tokens', to='core.mastercrm')),
            ],
            options={
                'verbose_name': 'Broker Token Auth',
                'verbose_name_plural': 'Broker Token Auth',
                'db_table': 'user_admin_broker_token_auth',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asset_hub'], name='user_admin__asset_h_539147_idx'), models.Index(fields=['expires_at'], name='user_admin__expires_54f7b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAssetAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('am_manager', 'AM Manager'), ('reo_manager', 'REO Manager')], db_index=True, max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access_assignments', to='core.assetidhub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_access_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_admin_user_asset_access',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asset_hub', 'role'], name='user_admin__asset_h_c97c79_idx'), models.Index(fields=['user', 'role'], name='user_admin__user_id_7ea270_idx'), models.Index(fields=['role', 'is_active'], name='user_admin__role_29f7e0_idx')],
                'unique_together': {('asset_hub', 'user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('access_level', models.IntegerField(default=10)),
                ('theme_preference', models.CharField(default='light', max_length=20)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='user_admin__user_id_000ad6_idx'), models.Index(fields=['access_level'], name='user_admin__access__32389e_idx')],
            },
        ),
    ]
