# Generated by Django 5.2.5 on 2025-11-08 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_valuation_appliances_grade_valuation_bath_grade_and_more'),
        ('user_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brokertokenauth',
            name='user_admin__seller__aaabe0_idx',
        ),
        migrations.RemoveField(
            model_name='brokertokenauth',
            name='seller_raw_data',
        ),
        migrations.AddField(
            model_name='brokertokenauth',
            name='asset_hub',
            field=models.ForeignKey(default=1, help_text='Asset hub ID this token is for (hub-first architecture).', on_delete=django.db.models.deletion.CASCADE, related_name='broker_tokens', to='core.assetidhub'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='brokertokenauth',
            index=models.Index(fields=['asset_hub'], name='user_admin__asset_h_539147_idx'),
        ),
    ]
