# Generated by Django 5.2 on 2025-08-22 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0011_alter_brokerphoto_photo'),
        ('user_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerTokenAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Opaque invite token used in public URL.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='When this token expires.')),
                ('single_use', models.BooleanField(default=True, help_text='If true, lock after first successful submit.')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the token was first used to submit values.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('broker', models.ForeignKey(blank=True, help_text='Directory record of the broker this token is intended for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_tokens', to='acq_module.brokercrm')),
                ('seller_raw_data', models.ForeignKey(help_text='SellerRawData row this token is for.', on_delete=django.db.models.deletion.CASCADE, related_name='broker_tokens', to='acq_module.sellerrawdata')),
            ],
            options={
                'verbose_name': 'Broker Token Auth',
                'verbose_name_plural': 'Broker Token Auth',
                'db_table': 'user_admin_broker_token_auth',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller_raw_data'], name='user_admin__seller__aaabe0_idx'), models.Index(fields=['expires_at'], name='user_admin__expires_54f7b0_idx')],
            },
        ),
    ]
