# Generated by Django 5.2.5 on 2025-08-25 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0015_alter_brokerphoto_photo'),
        ('user_admin', '0002_brokertokenauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerPortalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Opaque portal token used in public URL.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='When this portal token expires.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('broker', models.ForeignKey(help_text='Broker this portal token is issued for.', on_delete=django.db.models.deletion.CASCADE, related_name='portal_tokens', to='acq_module.brokercrm')),
            ],
            options={
                'verbose_name': 'Broker Portal Token',
                'verbose_name_plural': 'Broker Portal Tokens',
                'db_table': 'user_admin_broker_portal_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['broker'], name='user_admin__broker__253327_idx'), models.Index(fields=['expires_at'], name='user_admin__expires_af3abf_idx')],
            },
        ),
    ]
