# Generated by Django 5.2.5 on 2025-12-15 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_lldataenrichment_geocode_block_code_and_more'),
        ('user_admin', '0002_remove_brokertokenauth_user_admin__seller__aaabe0_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssetAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('am_manager', 'AM Manager'), ('reo_manager', 'REO Manager')], db_index=True, max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access_assignments', to='core.assetidhub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_access_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_admin_user_asset_access',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asset_hub', 'role'], name='user_admin__asset_h_c97c79_idx'), models.Index(fields=['user', 'role'], name='user_admin__user_id_7ea270_idx'), models.Index(fields=['role', 'is_active'], name='user_admin__role_29f7e0_idx')],
                'unique_together': {('asset_hub', 'user', 'role')},
            },
        ),
    ]
