# Generated by Django 5.2.5 on 2025-09-16 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('user_admin', '0003_brokerportaltoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerportaltoken',
            name='broker',
            field=models.ForeignKey(help_text='Broker this portal token is issued for.', on_delete=django.db.models.deletion.CASCADE, related_name='portal_tokens', to='core.brokercrm'),
        ),
        migrations.AlterField(
            model_name='brokertokenauth',
            name='broker',
            field=models.ForeignKey(blank=True, help_text='Directory record of the broker this token is intended for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_tokens', to='core.brokercrm'),
        ),
    ]
