# Generated by Django 5.2.5 on 2026-01-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0004_userprofile_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
