# Generated by Django 5.2.5 on 2026-01-30 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePointDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(blank=True, db_index=True, help_text='Trade ID (e.g., TRD-2024-001)', max_length=50, null=True)),
                ('asset_id', models.CharField(blank=True, db_index=True, help_text='Asset ID within trade', max_length=50, null=True)),
                ('category', models.CharField(choices=[('trade_bid', 'Trade - Bid'), ('trade_legal', 'Trade - Legal'), ('trade_post_close', 'Trade - Post Close'), ('asset_valuation', 'Asset - Valuation'), ('asset_collateral', 'Asset - Collateral'), ('asset_legal', 'Asset - Legal'), ('asset_tax', 'Asset - Tax'), ('asset_title', 'Asset - Title'), ('asset_photos', 'Asset - Photos')], help_text='Document category - determines SharePoint folder location', max_length=50)),
                ('file_name', models.CharField(help_text='Original uploaded file name', max_length=256)),
                ('file_type', models.CharField(help_text='File extension (pdf, xlsx, jpg, etc.)', max_length=50)),
                ('file_size_bytes', models.BigIntegerField(help_text='File size in bytes')),
                ('sharepoint_path', models.CharField(help_text='Full path in SharePoint (e.g., /Trades/TRD-2024-001/Legal/contract.pdf)', max_length=1024)),
                ('sharepoint_item_id', models.CharField(help_text='SharePoint item ID from Microsoft Graph API', max_length=255, unique=True)),
                ('sharepoint_drive_id', models.CharField(help_text='SharePoint drive ID from Microsoft Graph API', max_length=255)),
                ('sharepoint_web_url', models.URLField(help_text='Direct URL to view file in SharePoint', max_length=1024)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags for categorizing file (e.g., ['BPO', 'Updated', '2024'])")),
                ('is_validated', models.BooleanField(default=False, help_text='Whether file passed naming/content validation')),
                ('validation_errors', models.JSONField(blank=True, default=dict, help_text='Validation errors if any')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When file was uploaded to SharePoint')),
                ('last_modified_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - file archived in SharePoint')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When file was deleted/archived', null=True)),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_sharepoint_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SharePoint Document',
                'verbose_name_plural': 'SharePoint Documents',
                'db_table': 'sharepoint_document',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['trade_id', 'asset_id'], name='sharepoint__trade_i_8ad400_idx'), models.Index(fields=['sharepoint_item_id'], name='sharepoint__sharepo_74cec7_idx'), models.Index(fields=['category'], name='sharepoint__categor_94d74a_idx'), models.Index(fields=['is_deleted'], name='sharepoint__is_dele_308dba_idx')],
            },
        ),
    ]
