# Generated by Django 5.2.5 on 2025-12-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharepoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharepointdocument',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Tags for categorizing file (e.g., ['BPO', 'Updated', '2024'])"),
        ),
    ]
