# Generated by Django 5.2.5 on 2025-11-08 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(help_text='Location of the source document in storage (e.g., SharePoint path).', max_length=1024)),
                ('file_mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(help_text='Timestamp when the document became available for processing.')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('partial', 'Partial'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuation_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'etl_valuation_document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='info', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='etl.valuationdocument')),
            ],
            options={
                'db_table': 'etl_valuation_extraction_log',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionFieldResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model', models.CharField(help_text='Django model label receiving the value (e.g., etl.ValuationETL).', max_length=100)),
                ('target_field', models.CharField(max_length=100)),
                ('value_text', models.TextField(blank=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('confidence', models.DecimalField(decimal_places=4, help_text='Confidence score between 0 and 1.', max_digits=5)),
                ('extraction_method', models.CharField(choices=[('rule', 'Rule'), ('ocr', 'OCR'), ('ai', 'AI'), ('manual', 'Manual')], default='rule', max_length=20)),
                ('requires_review', models.BooleanField(default=False, help_text='True when the value needs human validation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_results', to='etl.valuationdocument')),
            ],
            options={
                'db_table': 'etl_valuation_extraction_field',
                'unique_together': {('document', 'target_model', 'target_field')},
            },
        ),
    ]
