# Generated by Django 5.2.5 on 2025-11-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_valuationdocument_extractionlogentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuationetl',
            name='source',
            field=models.CharField(blank=True, choices=[('internalInitialUW', 'Internal Initial UW Valuation'), ('internal', 'Internal Valuation'), ('broker', 'Broker Valuation'), ('desktop', 'Desktop Valuation'), ('BPOI', 'BPOI'), ('BPOE', 'BPOE'), ('seller', 'Seller Provided'), ('appraisal', 'Professional Appraisal')], help_text='Valuation source code aligned with core Valuation model choices.', max_length=20, null=True),
        ),
    ]
