# Generated by Django 5.2.5 on 2025-11-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_alter_repairitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparablesetl',
            name='adjustments_description',
        ),
    ]
