# Generated by Django 5.2.5 on 2025-11-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_remove_comparablesetl_adjustments_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparablesetl',
            name='financing_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('conventional', 'Conventional'), ('fha', 'FHA'), ('va', 'VA'), ('usda', 'USDA'), ('seller_financing', 'Seller Financing'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='sales_type',
            field=models.CharField(blank=True, choices=[('retail', 'Retail'), ('arms_length', 'Arms Length / Fair Market'), ('fair_market', 'Fair Market'), ('reo', 'REO/Bank Owned'), ('short_sale', 'Short Sale'), ('foreclosure', 'Foreclosure'), ('estate_sale', 'Estate Sale'), ('relocation', 'Relocation'), ('non_arms_length', 'Non-Arms Length'), ('unknown', 'Unknown')], max_length=20, null=True),
        ),
    ]
