# Generated by Django 5.2.5 on 2025-11-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_alter_comparablesetl_financing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparablesetl',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Total bathrooms (e.g., 2.5)', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='comp_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='comp_type',
            field=models.CharField(blank=True, choices=[('sold', 'Closed Sale'), ('listing', 'Active Listing'), ('pending', 'Pending Sale'), ('expired', 'Expired Listing'), ('withdrawn', 'Withdrawn Listing')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='condition',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='cooling_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='data_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='data_source_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='foundation_type',
            field=models.CharField(blank=True, choices=[('basement', 'Basement'), ('full_basement', 'Full Basement'), ('partial_basement', 'Partial Basement'), ('crawl_space', 'Crawl Space'), ('slab', 'Slab'), ('pier_beam', 'Pier & Beam'), ('none', 'None'), ('n/a', 'N/A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='garage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='general_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='has_deck',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='has_fencing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='has_fireplace',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='has_pool',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='heating_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='living_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='number_of_units',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='parking_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='property_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='school_district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='sewer_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='style',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='subdivision',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='total_adjustments',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total $ adjustments made to comparable', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='water_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparablesetl',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='repairitem',
            name='category',
            field=models.CharField(blank=True, choices=[('paint_int', 'Paint (Interior)'), ('walls_ceiling', 'Walls/Ceiling'), ('flooring', 'Flooring/Carpet'), ('kitchen', 'Kitchen'), ('cabinets_countertops', 'Cabinets/Countertops'), ('bathrooms', 'Bathrooms'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('hvac', 'Heating/Cooling/HVAC'), ('appliances', 'Appliances'), ('doors_trim_int', 'Doors/Trim (Interior)'), ('stairs', 'Stairs/Railings'), ('basement', 'Basement'), ('cleaning', 'Cleaning/Debris Removal'), ('other_internal', 'Other (Internal)'), ('roof', 'Roof'), ('siding', 'Siding'), ('trim', 'Trim/Soffit/Fascia'), ('structural', 'Structural'), ('windows', 'Windows'), ('doors_ext', 'Doors (Exterior)'), ('paint_ext', 'Paint (Exterior)'), ('power_wash', 'Power Wash'), ('foundation', 'Foundation'), ('garage', 'Garage'), ('driveway', 'Driveway'), ('walkway', 'Walkway/Sidewalk'), ('landscaping', 'Landscaping'), ('trees_removal', 'Tree Removal/Trimming'), ('fence', 'Fence/Gate'), ('deck_patio', 'Deck/Patio'), ('pool', 'Pool/Spa'), ('gutters', 'Gutters/Downspouts'), ('grading_drainage', 'Grading/Drainage'), ('other_external', 'Other (External)'), ('septic', 'Septic System'), ('well', 'Well'), ('other_systems', 'Other Systems')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='repairitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repairitem',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='repairitem',
            name='repair_recommended',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this repair is recommended', null=True),
        ),
        migrations.AlterField(
            model_name='repairitem',
            name='repair_type',
            field=models.CharField(blank=True, choices=[('internal', 'Internal'), ('external', 'External'), ('systems', 'Systems')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='bpo_type',
            field=models.CharField(blank=True, choices=[('interior', 'Interior Inspection'), ('exterior', 'Exterior Inspection'), ('drive_by', 'Drive By'), ('desktop', 'Desktop/Remote')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='condition',
            field=models.CharField(blank=True, choices=[('C1', 'C1 - Excellent'), ('C2', 'C2 - Very Good'), ('C3', 'C3 - Good'), ('C4', 'C4 - Average'), ('C5', 'C5 - Fair'), ('C6', 'C6 - Poor'), ('Q1', 'Q1 - Excellent'), ('Q2', 'Q2 - Very Good'), ('Q3', 'Q3 - Good'), ('Q4', 'Q4 - Average'), ('Q5', 'Q5 - Fair'), ('Q6', 'Q6 - Poor'), ('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('average', 'Average'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='cooling_type',
            field=models.CharField(blank=True, choices=[('central', 'Central AC'), ('wall', 'Wall Unit'), ('window', 'Window Units'), ('evaporative', 'Evaporative/Swamp Cooler'), ('heat_pump', 'Heat Pump'), ('none', 'None')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='crime_vandalism_risk',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='currently_listed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='data_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='data_source_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='deal_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='economic_trend',
            field=models.CharField(blank=True, choices=[('stable', 'Stable'), ('declining', 'Declining'), ('improving', 'Improving'), ('under_improvement', 'Under Improvement'), ('rapid_growth', 'Rapid Growth')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='estimated_marketing_time',
            field=models.CharField(blank=True, choices=[('0-30', '0 to 30 Days'), ('30-60', '30 to 60 Days'), ('30-90', '30 to 90 Days'), ('60-90', '60 to 90 Days'), ('90-120', '90 to 120 Days'), ('90-180', '90 to 180 Days'), ('180-365', '180 to 365 Days'), ('365+', 'Over 365 Days')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='financeable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='foundation_type',
            field=models.CharField(blank=True, choices=[('basement', 'Basement'), ('full_basement', 'Full Basement'), ('partial_basement', 'Partial Basement'), ('crawl_space', 'Crawl Space'), ('slab', 'Slab'), ('pier_beam', 'Pier & Beam'), ('none', 'None'), ('n/a', 'N/A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='garage',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('carport', 'Carport'), ('1_car', '1 Car'), ('1_attached', '1 Car Attached'), ('2_attached', '2 Car Attached'), ('3_attached', '3+ Car Attached'), ('1_detached', '1 Car Detached'), ('2_detached', '2 Car Detached'), ('3_detached', '3+ Car Detached'), ('1_builtin', '1 Car Built-in'), ('2_builtin', '2 Car Built-in')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='general_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='general_repair_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='has_deck',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='has_fencing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='has_fireplace',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='has_pool',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='heating_type',
            field=models.CharField(blank=True, choices=[('gas', 'Gas'), ('electric', 'Electric'), ('oil', 'Oil'), ('forced_air', 'Forced Air'), ('baseboard', 'Baseboard'), ('radiant', 'Radiant'), ('heat_pump', 'Heat Pump'), ('wood', 'Wood/Pellet'), ('none', 'None')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='housing_supply',
            field=models.CharField(blank=True, choices=[('shortage', 'Shortage/Under Supply'), ('balanced', 'Balanced/In Balance'), ('stable', 'Stable'), ('oversupply', 'Over Supply')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='inspection_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='listing_agent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='listing_agent_firm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='listing_broker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='listing_currently_pending',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='loan_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='market_trend',
            field=models.CharField(blank=True, choices=[('stable', 'Stable'), ('declining', 'Declining'), ('improving', 'Improving'), ('under_improvement', 'Under Improvement'), ('rapid_growth', 'Rapid Growth')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='marketability_concerns',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='neighborhood_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='neighborhood_trend',
            field=models.CharField(blank=True, choices=[('stable', 'Stable'), ('declining', 'Declining'), ('improving', 'Improving'), ('under_improvement', 'Under Improvement'), ('rapid_growth', 'Rapid Growth')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='new_construction_in_area',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='number_of_units',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='occupancy_status',
            field=models.CharField(blank=True, choices=[('owner', 'Owner Occupied'), ('tenant', 'Tenant Occupied'), ('vacant', 'Vacant'), ('unknown', 'Unknown')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='parcel_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='parking_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='preparer_comments',
            field=models.TextField(blank=True, help_text='Comments or notes from the preparer', null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='preparer_company',
            field=models.CharField(blank=True, help_text='Company of the preparer', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='preparer_email',
            field=models.EmailField(blank=True, help_text='Email of the preparer', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='preparer_name',
            field=models.CharField(blank=True, help_text='Name of BPO agent or appraiser who prepared the valuation', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='preparer_phone',
            field=models.CharField(blank=True, help_text='Phone number of the preparer', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='property_address',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='property_appears_secure',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='property_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='property_rights_appraised',
            field=models.CharField(blank=True, choices=[('fee_simple', 'Fee Simple'), ('leasehold', 'Leasehold'), ('leased_fee', 'Leased Fee')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='property_type',
            field=models.CharField(blank=True, choices=[('sf_detached', 'Single Family Detached'), ('sf_attached', 'Single Family Attached'), ('condo', 'Condominium'), ('townhouse', 'Townhouse'), ('pud', 'PUD'), ('2_4_unit', '2-4 Unit Multi-Family'), ('5plus_unit', '5+ Unit Multi-Family'), ('mobile', 'Mobile/Manufactured'), ('land', 'Land/Vacant'), ('commercial', 'Commercial'), ('mixed_use', 'Mixed Use')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='property_values_trend',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='recommended_sales_strategy',
            field=models.CharField(blank=True, choices=[('as_is', 'As-Is'), ('as_repaired', 'As-Repaired'), ('quick_sale', 'Quick Sale')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='reo_driven_market',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='school_district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='seasonal_market',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='sewer_type',
            field=models.CharField(blank=True, choices=[('public', 'Public Sewer'), ('septic', 'Septic'), ('cesspool', 'Cesspool'), ('holding_tank', 'Holding Tank')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='sold_in_last_12_months',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='style',
            field=models.CharField(blank=True, choices=[('single_story', 'Single Story / Ranch'), ('1_story', '1 Story'), ('1.5_story', '1.5 Story'), ('2_story', '2 Story'), ('2_story_conv', '2 Story Conventional'), ('3_story', '3+ Story'), ('split_level', 'Split Level'), ('split_foyer', 'Split Foyer'), ('bi_level', 'Bi-Level'), ('tri_level', 'Tri-Level'), ('colonial', 'Colonial'), ('contemporary', 'Contemporary'), ('cape_cod', 'Cape Cod'), ('bungalow', 'Bungalow'), ('victorian', 'Victorian'), ('tudor', 'Tudor'), ('mediterranean', 'Mediterranean'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='subdivision',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='subject_appeal_compared_to_avg',
            field=models.CharField(blank=True, choices=[('superior', 'Superior'), ('above_average', 'Above Average'), ('average', 'Average'), ('below_average', 'Below Average'), ('under_improvement', 'Under Improvement'), ('low', 'Low')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='subject_value_compared_to_avg',
            field=models.CharField(blank=True, choices=[('superior', 'Superior'), ('above_average', 'Above Average'), ('average', 'Average'), ('below_average', 'Below Average'), ('under_improvement', 'Under Improvement'), ('low', 'Low')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='valuation_type',
            field=models.CharField(blank=True, choices=[('bpo', 'Broker Price Opinion'), ('appraisal', 'Appraisal'), ('avm', 'Automated Valuation Model')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='water_type',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('well', 'Well'), ('shared_well', 'Shared Well'), ('cistern', 'Cistern')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='valuationetl',
            name='zip_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
