# Generated by Django 5.2.5 on 2025-11-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0007_alter_comparablesetl_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparablesetl',
            name='price_per_sqft',
        ),
        migrations.RemoveField(
            model_name='valuationetl',
            name='housing_supply',
        ),
        migrations.RemoveField(
            model_name='valuationetl',
            name='new_construction_in_area',
        ),
        migrations.RemoveField(
            model_name='valuationetl',
            name='num_boarded_properties',
        ),
        migrations.RemoveField(
            model_name='valuationetl',
            name='num_reo_ss_listings',
        ),
        migrations.RemoveField(
            model_name='valuationetl',
            name='reo_driven_market',
        ),
        migrations.RemoveField(
            model_name='valuationetl',
            name='seasonal_market',
        ),
    ]
