# Generated by Django 5.2 on 2025-12-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0008_remove_calculated_and_unused_fields"),
        (
            "am_module",
            "0064_rename_broker_fees_blendedoutcomemodel_broker_closing_fees_and_more",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="SBDailyLoanData",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "date",
                            models.CharField(
                                blank=True, max_length=20, null=True
                            ),
                        ),
                        (
                            "investor_id",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "loan_number",
                            models.CharField(
                                blank=True, max_length=50, null=True
                            ),
                        ),
                        (
                            "investor_loan_number",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "prior_servicer_loan_number",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "avm_appraisal_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "avm_appraisal_type",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "avm_appraisal_value",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "original_appraisal_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "original_appraisal_value",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "bpo_as_is_value",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "bpo_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "bpo_repaired_value",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "borrower_first_name",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "borrower_last_name",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "borrower_home_phone",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "borrower_count",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "corporate_advance_balance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "current_upb",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "current_interest_rate",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "current_principal_and_interest_payment",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "current_taxes_and_insurance_payment",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "current_fico_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "current_fico",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "co_borrower_fico",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "co_borrower_fico_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "date_last_payment_received",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "due_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "first_due_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "escrow_advance_balance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "escrow_balance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "is_escrowed",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "restricted_escrow",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "last_escrow_analysis_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "is_arm",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "lien_position",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "loan_status",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "loan_type",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "loan_purpose",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "loan_warning",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "mba",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "occupancy_status",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "legal_status",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "property_state",
                            models.CharField(blank=True, max_length=2, null=True),
                        ),
                        (
                            "property_zip",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "property_address",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "property_city",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "property_county",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "property_type",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "active_bk_plan",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "bankruptcy_business_area_status_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "bankruptcy_business_area_status",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "bk_case_number",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "bk_chapter",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "bk_court_district",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "bk_discharge_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "bk_dismissed_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "bk_filed_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "bk_plan_end_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "bk_plan_length",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "bk_plan_start_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "bk_post_petition_due_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "bk_case_closed_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "date_motion_for_relief_filed",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "date_object_to_confirmation_filed",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "date_of_meeting_of_creditors",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "date_proof_of_claim_filed",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "relief_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "actual_fc_sale_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "date_referred_to_fc_atty",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "fc_completion_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "fc_status",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "foreclosure_business_area_status_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "foreclosure_business_area_status",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "is_a_contested_fc",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "reason_for_default",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "scheduled_fc_sale_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "days_in_foreclosure",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "date_breach_letter_sent",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "dil_completion_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "loss_mitigation_business_area_status_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "loss_mitigation_business_area_status",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "loss_mitigation_start_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "loss_mitigation_status",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "workout_option",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "convert_to_fixed_rate",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "loan_modification_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "loan_modification_status",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "number_of_payments",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "post_modification_principal_balance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "pre_modification_balance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "post_modification_coupon",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "post_modification_payment",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "pre_modification_coupon",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "pre_modification_payment",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "total_capitalized_by_mod",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "modification_type",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "modified_first_payment_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "mod_extended_maturity",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "mod_forbearance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "mod_forgiven",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "repayment_plan_agreement_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "repayment_plan_start_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "repayment_plan_status",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "repay_plan_type",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "date_inspection_completed",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "deferred_advance_balance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "first_time_vacant_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "follow_up_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "is_house_for_sale",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "neighborhood_condition",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "property_condition_from_inspection",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "forceplaced_flood_insurance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "forceplaced_hazard_insurance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "last_contact_outcome",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "last_successful_contact_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "next_arm_rate_change_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "arm_audit_status",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "arm_first_rate_change_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "max_rate",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "min_rate",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "first_periodic_rate_cap",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "periodic_rate_cap",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "life_cap",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "is_pay_option_arm",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "pay_option_negative_amort_factor",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "within_pay_option_period",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "current_neg_am_bal",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "pif_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "pif_quote_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "promise_amount",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "promise_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "res_service_fee_paid",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "resolution_corporate_advance_balance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "resolution_escrow_advance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "resolution_fees",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "resolution_post_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "resolution_proceeds",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "resolution_type",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "resolution_balance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "ss_complete",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "ss_proceeds_rcvd",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "acquired_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "inactive_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "prim_stat",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "noi_expiration_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "forgive_amount",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "balance_after_forgive",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "acquisition_or_sale_identifier",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "total_principal",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "total_interest",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "non_recoverable_principal",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "non_recoverable_interest",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "non_recoverable_escrow",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "non_recoverable_fees",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "non_recoverable_corporate_advance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "non_recoverable_corp_adv_balance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "collateral_count",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "current_loan_term",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "deferred_interest",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "deferred_principal",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "prior_deferred_principal",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "interest_method",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "loan_age",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "maturity_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "original_maturity_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "original_loan_term",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "original_amt",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "original_first_payment_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "origination_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "remaining_term",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "mers_num",
                            models.CharField(
                                blank=True,
                                help_text="MERS Number",
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "trust_id",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "mi_company_name",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "mi_active_policy",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "mi_certificate_number",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "mi_claim",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "mi_claim_status",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "mi_claim_filed_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "mi_coverage",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "mi_date_closed",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "mi_date_paid",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "mi_last_review_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "mi_paid_amount",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "mi_rescind_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "mi_rescind_reason",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "balloon_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "balloon_payment",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "asset_manager",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "servicing_specialist",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "single_point_of_contact",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "right_party_type",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "right_party_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "prepetition_unapplied_bal",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "stipulation_unapplied_bal",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "unapplied_balance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "total_due",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "principal_due",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "interest_due",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "escrow_due",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "legal_fees",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "other_fees",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "nsf_fees",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "accrued_late_fees",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(auto_now_add=True),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(auto_now=True),
                        ),
                    ],
                    options={
                        "db_table": "loan_records",
                        "verbose_name": "StateBridge Daily Loan Data",
                        "verbose_name_plural": "StateBridge Daily Loan Data",
                        "indexes": [
                            models.Index(fields=["loan_number"], name="loan_record_loan_nu_a822c9_idx"),
                            models.Index(fields=["investor_loan_number"], name="loan_record_investo_ffcd41_idx"),
                            models.Index(fields=["borrower_last_name", "borrower_first_name"], name="loan_record_borrowe_073caf_idx"),
                            models.Index(fields=["property_state", "property_zip"], name="loan_record_propert_164947_idx"),
                            models.Index(fields=["loan_status"], name="loan_record_loan_st_08b3b3_idx"),
                            models.Index(fields=["date"], name="loan_record_date_f4c38c_idx"),
                            models.Index(fields=["loan_number", "date"], name="loan_record_loan_nu_c13584_idx"),
                        ],
                    },
                ),
            ],
        )
    ]
