# Generated by Django 5.2 on 2025-12-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0009_add_sbdailyloandata_from_am_module"),
        ("am_module", "0065_move_sbdailyloandata_to_etl"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="SBDailyArmData",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "file_date",
                            models.CharField(
                                blank=True,
                                db_index=True,
                                max_length=20,
                                null=True,
                            ),
                        ),
                        (
                            "loan_id",
                            models.CharField(
                                blank=True,
                                db_index=True,
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "loan_number",
                            models.CharField(
                                blank=True,
                                db_index=True,
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "investor_id",
                            models.CharField(
                                blank=True,
                                db_index=True,
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "row_data",
                            models.JSONField(blank=True, null=True),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(auto_now_add=True),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(auto_now=True),
                        ),
                    ],
                    options={
                        "verbose_name": "StateBridge Daily ARM Data",
                        "verbose_name_plural": "StateBridge Daily ARM Data",
                        "db_table": "arm_records",
                        "indexes": [
                            models.Index(
                                fields=["loan_number"],
                                name="arm_record_loan_nu_3e7fdc_idx",
                            ),
                            models.Index(
                                fields=["loan_id"],
                                name="arm_record_loan_id_1e6f7e_idx",
                            ),
                            models.Index(
                                fields=["investor_id"],
                                name="arm_record_investo_8fbe0c_idx",
                            ),
                            models.Index(
                                fields=["file_date"],
                                name="arm_record_file_d_24dd7b_idx",
                            ),
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="SBDailyForeclosureData",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "file_date",
                            models.CharField(
                                blank=True, db_index=True, max_length=20, null=True
                            ),
                        ),
                        (
                            "loan_id",
                            models.CharField(
                                blank=True, db_index=True, max_length=50, null=True
                            ),
                        ),
                        (
                            "investor_id",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "investor_loan_number",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "prior_servicer_loan_number",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "prior_servicer_name",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "prior_servicer_contact",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "prior_servicer_contact_phone",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "legal_status",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "prim_stat",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "warning",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "due_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "loan_type",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "original_loan_amount",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "current_upb",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "lien_position",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "borrower_name",
                            models.CharField(blank=True, max_length=200, null=True),
                        ),
                        (
                            "borrower_first_name",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "borrower_last_name",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "borrower_deceased",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "property_state",
                            models.CharField(blank=True, max_length=2, null=True),
                        ),
                        (
                            "property_zip",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "mortgage_asgmnt_complete_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "current_assignee",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "mi_insurance",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "mi_company_name",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "mi_claim_filed",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "mi_paid_amount",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "mi_claim_paid_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "bpo_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "bpo_as_is_value",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "bpo_repaired_value",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "occupancy_status",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "property_condition_from_inspection",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "date_inspection_completed",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "fc_attorney",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "last_atty_note_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "last_atty_note_topic",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "last_atty_note",
                            models.CharField(blank=True, max_length=1000, null=True),
                        ),
                        (
                            "delinquent_taxes",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "title_issue",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "title_received",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "fc_specialist",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "date_breach_letter_sent",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "noi_expiration_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "original_fc_referral_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "date_referred_to_fc_atty",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "reason_for_default",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "is_a_contested_fc",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "current_fc_step",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "fc_step_completed_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "next_fc_step",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "next_fc_step_due_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "hold_start_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "hold_reason",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "hold_end_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "projected_fc_sale_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "scheduled_fc_sale_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "actual_fc_sale_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "bid_amount",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "sale_amount",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "sale_results",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "rrc_expired",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "fc_completion_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "deed_recorded",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "first_legal_action_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "verbose_name": "StateBridge Daily Foreclosure Data",
                        "verbose_name_plural": "StateBridge Daily Foreclosure Data",
                        "db_table": "foreclosure_records",
                        "indexes": [
                            models.Index(
                                fields=["loan_id"],
                                name="foreclosure_loan_id_0679d9_idx",
                            ),
                            models.Index(
                                fields=["investor_loan_number"],
                                name="foreclosure_investo_cb2199_idx",
                            ),
                            models.Index(
                                fields=["borrower_last_name", "borrower_first_name"],
                                name="foreclosure_borrowe_ddceb2_idx",
                            ),
                            models.Index(
                                fields=["property_state", "property_zip"],
                                name="foreclosure_propert_977e84_idx",
                            ),
                            models.Index(
                                fields=["legal_status"],
                                name="foreclosure_legal_s_309be1_idx",
                            ),
                            models.Index(
                                fields=["file_date"],
                                name="foreclosure_file_da_c4958f_idx",
                            ),
                            models.Index(
                                fields=["loan_id", "file_date"],
                                name="foreclosure_loan_id_59c89d_idx",
                            ),
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="SBDailyBankruptcyData",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "asset_manager",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "loan_id",
                            models.CharField(
                                blank=True, db_index=True, max_length=50, null=True
                            ),
                        ),
                        (
                            "investor_loan_id",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "previous_ln_num",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "acquisition_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "loan_due_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "mba",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "legal",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "warning",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "investor_id",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "chapter",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "case_number",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "bk_filed_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "state_filed",
                            models.CharField(blank=True, max_length=2, null=True),
                        ),
                        (
                            "filing_court",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "filing_borrower",
                            models.CharField(blank=True, max_length=200, null=True),
                        ),
                        (
                            "joint_filer",
                            models.CharField(blank=True, max_length=200, null=True),
                        ),
                        (
                            "trustee_name",
                            models.CharField(blank=True, max_length=200, null=True),
                        ),
                        (
                            "statebridge_atty_name",
                            models.CharField(blank=True, max_length=200, null=True),
                        ),
                        (
                            "borrower_atty_name",
                            models.CharField(blank=True, max_length=200, null=True),
                        ),
                        (
                            "bankruptcy_status",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "prepetition_claim_amt",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "active_plan",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "plan_start_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "pre_petition_payment",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "plan_length",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "projected_plan_end_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "actual_plan_completion_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "last_pre_petition_payment_rcvd_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "last_payment_applied",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "pre_petition_balance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "stipulation_claim_amt",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "stipulation_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "stipulation_first_pmt_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "stipulation_last_pmt_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "stipulation_monthly_pmt",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "stipulation_repay_months",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "last_stipulation_payment_rcvd_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "first_post_petition_due_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "next_post_petition_due_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "post_petition_pmt_amt",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "bk_case_closed_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "bk_discharge_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "bk_dismissed_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "date_motion_for_relief_filed",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "date_proof_of_claim_filed",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "date_of_meeting_of_creditors",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "date_object_to_confirmation_filed",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "relief_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "bankruptcy_business_area_status",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "bankruptcy_business_area_status_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "order_of_confirmation_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "active_bankruptcy",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "verbose_name": "StateBridge Daily Bankruptcy Data",
                        "verbose_name_plural": "StateBridge Daily Bankruptcy Data",
                        "db_table": "bankruptcy_records",
                        "indexes": [
                            models.Index(
                                fields=["loan_id"],
                                name="bankruptcy__loan_id_0b2105_idx",
                            ),
                            models.Index(
                                fields=["investor_loan_id"],
                                name="bankruptcy__investo_55480c_idx",
                            ),
                            models.Index(
                                fields=["case_number"],
                                name="bankruptcy__case_nu_8d6298_idx",
                            ),
                            models.Index(
                                fields=["filing_borrower"],
                                name="bankruptcy__filing__a7e889_idx",
                            ),
                            models.Index(
                                fields=["bankruptcy_status"],
                                name="bankruptcy__bankrup_dc4437_idx",
                            ),
                            models.Index(
                                fields=["bk_filed_date"],
                                name="bankruptcy__bk_file_3512a6_idx",
                            ),
                            models.Index(
                                fields=["loan_id", "bk_filed_date"],
                                name="bankruptcy__loan_id_d2e610_idx",
                            ),
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="SBDailyCommentData",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "investor_id",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "loan_number",
                            models.CharField(
                                blank=True, db_index=True, max_length=50, null=True
                            ),
                        ),
                        (
                            "investor_loan_number",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "prior_servicer_loan_number",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "comment_date",
                            models.CharField(
                                blank=True, db_index=True, max_length=20, null=True
                            ),
                        ),
                        (
                            "department",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "comment",
                            models.CharField(blank=True, max_length=4000, null=True),
                        ),
                        (
                            "additional_notes",
                            models.CharField(blank=True, max_length=4000, null=True),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "verbose_name": "StateBridge Daily Comment Data",
                        "verbose_name_plural": "StateBridge Daily Comment Data",
                        "db_table": "comment_records",
                        "indexes": [
                            models.Index(
                                fields=["loan_number"],
                                name="comment_rec_loan_nu_ad6a2d_idx",
                            ),
                            models.Index(
                                fields=["investor_loan_number"],
                                name="comment_rec_investo_7cae45_idx",
                            ),
                            models.Index(
                                fields=["comment_date"],
                                name="comment_rec_comment_a4d9b1_idx",
                            ),
                            models.Index(
                                fields=["department"],
                                name="comment_rec_departm_f7e086_idx",
                            ),
                            models.Index(
                                fields=["loan_number", "comment_date"],
                                name="comment_rec_loan_nu_e9e187_idx",
                            ),
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="SBDailyPayHistoryData",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "investor",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "loan_number",
                            models.CharField(
                                blank=True, db_index=True, max_length=50, null=True
                            ),
                        ),
                        (
                            "previous_ln_num",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "borrower_name",
                            models.CharField(blank=True, max_length=200, null=True),
                        ),
                        (
                            "property_address",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "city",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "state",
                            models.CharField(blank=True, max_length=2, null=True),
                        ),
                        (
                            "zip",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "property_type",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "number_of_units",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "occupancy_status",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "original_upb",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "second_upb",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "current_upb",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "account_type",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "lien",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "loan_term",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "remaining_term",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "maturity_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "rate_type",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "arm",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "balloon",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "piggyback",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "current_ir",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "current_pi",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "current_ti",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "current_piti",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "last_full_payment_dt",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "next_payment_due_dt",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "escrow_indicator",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "restricted_escrow",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "escrow_advance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "rec_corp_advance_balance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "third_party_rec_balance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "accrued_interest",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "accrued_late_fees",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "fc_status",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "fc_type",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "fc_first_legal_filed_dt",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "fc_judgement_entered_dt",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "fc_sale_scheduled_dt",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "fc_suspended_dt",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "fc_removal_dt",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "fc_removal_description",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "bk_status",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "bk_code",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "bk_filing_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "bk_case_number",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "bk_removal_dt",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "original_appraised_value",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "as_is_bpo",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "bpo_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "fico_original",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "fico",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "fico_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "loan_mod_dt",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "mod_upb",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "mod_ir",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "mod_pi",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "mod_first_payment_dt",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "mod_maturity",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "origination_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "original_principal",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "orig_rate",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "fp_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "mt_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "interest_only_indicator",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "interest_only_expiration_dt",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "hoi_expiration_dt",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "m0",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "m1",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "m2",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "m3",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "m4",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "m5",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "m6",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "m7",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "m8",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "m9",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "m10",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "m11",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "m12",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "id0_0",
                            models.CharField(
                                blank=True,
                                db_column="ID0 0 - $",
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "id0_1",
                            models.CharField(
                                blank=True,
                                db_column="ID0 1 - $",
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "id0_2",
                            models.CharField(
                                blank=True,
                                db_column="ID0 2 - $",
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "id0_3",
                            models.CharField(
                                blank=True,
                                db_column="ID0 3 - $",
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "id0_4",
                            models.CharField(
                                blank=True,
                                db_column="ID0 4 - $",
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "id0_5",
                            models.CharField(
                                blank=True,
                                db_column="ID0 5 - $",
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "id0_6",
                            models.CharField(
                                blank=True,
                                db_column="ID0 6 - $",
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "id0_7",
                            models.CharField(
                                blank=True,
                                db_column="ID0 7 - $",
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "id0_8",
                            models.CharField(
                                blank=True,
                                db_column="ID0 8 - $",
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "id0_9",
                            models.CharField(
                                blank=True,
                                db_column="ID0 9 - $",
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "id0_10",
                            models.CharField(
                                blank=True,
                                db_column="ID0 10 - $",
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "id0_11",
                            models.CharField(
                                blank=True,
                                db_column="ID0 11 - $",
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "id0_12",
                            models.CharField(
                                blank=True,
                                db_column="ID0 12 - $",
                                max_length=50,
                                null=True,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "verbose_name": "StateBridge Daily Pay History Data",
                        "verbose_name_plural": "StateBridge Daily Pay History Data",
                        "db_table": "pay_history_records",
                        "indexes": [
                            models.Index(
                                fields=["loan_number"],
                                name="pay_history_loan_nu_4d1dfe_idx",
                            ),
                            models.Index(
                                fields=["previous_ln_num"],
                                name="pay_history_previou_59bbbd_idx",
                            ),
                            models.Index(
                                fields=["borrower_name"],
                                name="pay_history_borrowe_19e60f_idx",
                            ),
                            models.Index(
                                fields=["state", "zip"],
                                name="pay_history_state_f88917_idx",
                            ),
                            models.Index(
                                fields=["fc_status"],
                                name="pay_history_fc_stat_c65467_idx",
                            ),
                            models.Index(
                                fields=["bk_status"],
                                name="pay_history_bk_stat_f92c65_idx",
                            ),
                            models.Index(
                                fields=["next_payment_due_dt"],
                                name="pay_history_next_pa_db51a2_idx",
                            ),
                            models.Index(
                                fields=["loan_number", "next_payment_due_dt"],
                                name="pay_history_loan_nu_366299_idx",
                            ),
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="SBDailyTransactionData",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "investor_id",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "loan_id",
                            models.CharField(
                                blank=True, db_index=True, max_length=50, null=True
                            ),
                        ),
                        (
                            "previous_ln_num",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "loan_transaction_id",
                            models.CharField(
                                blank=True, db_index=True, max_length=50, null=True
                            ),
                        ),
                        (
                            "transaction_date",
                            models.CharField(
                                blank=True, db_index=True, max_length=20, null=True
                            ),
                        ),
                        (
                            "transaction_code",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "transaction_description",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "effective_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "transaction_amt",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "due_date",
                            models.CharField(blank=True, max_length=20, null=True),
                        ),
                        (
                            "principal_amount",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "interest_amount",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "suspense_paid",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "non_recoverable_advance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "recoverable_advance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "corporate_advance_reason_code",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "escrow_advance_balance",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "escrow_amount",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "restricted_escrow",
                            models.CharField(blank=True, max_length=10, null=True),
                        ),
                        (
                            "fee_code",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "fee_description",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "unapplied_pmt",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "stipulation_unapplied_pmt",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "pre_petition_unapplied_pmt",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        (
                            "asset_manager",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "verbose_name": "StateBridge Daily Transaction Data",
                        "verbose_name_plural": "StateBridge Daily Transaction Data",
                        "db_table": "transaction_records",
                        "indexes": [
                            models.Index(
                                fields=["loan_id"],
                                name="transaction_loan_id_a1ee8f_idx",
                            ),
                            models.Index(
                                fields=["previous_ln_num"],
                                name="transaction_previou_ab528a_idx",
                            ),
                            models.Index(
                                fields=["loan_transaction_id"],
                                name="transaction_loan_tr_9256e6_idx",
                            ),
                            models.Index(
                                fields=["transaction_date"],
                                name="transaction_transac_75c4f7_idx",
                            ),
                            models.Index(
                                fields=["transaction_code"],
                                name="transaction_transac_c919df_idx",
                            ),
                            models.Index(
                                fields=["effective_date"],
                                name="transaction_effecti_56902d_idx",
                            ),
                            models.Index(
                                fields=["due_date"],
                                name="transaction_due_dat_ac2d63_idx",
                            ),
                            models.Index(
                                fields=["loan_id", "transaction_date"],
                                name="transaction_loan_id_cf33b5_idx",
                            ),
                        ],
                    },
                ),
            ],
        )
    ]
