# Generated by Django 5.2 on 2025-12-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0010_add_statebridge_raw_models_from_am_module"),
    ]

    operations = [
        migrations.CreateModel(
            name="SBDailyArmData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_date",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                (
                    "loan_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "loan_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "investor_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("row_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "StateBridge Daily ARM Data",
                "verbose_name_plural": "StateBridge Daily ARM Data",
                "db_table": "arm_records",
                "indexes": [
                    models.Index(
                        fields=["loan_number"], name="arm_record_loan_nu_3e7fdc_idx"
                    ),
                    models.Index(
                        fields=["loan_id"], name="arm_record_loan_id_1e6f7e_idx"
                    ),
                    models.Index(
                        fields=["investor_id"], name="arm_record_investo_8fbe0c_idx"
                    ),
                    models.Index(
                        fields=["file_date"], name="arm_record_file_d_24dd7b_idx"
                    ),
                ],
            },
        ),
    ]
