# Generated by Django 5.2 on 2025-12-17

from django.db import migrations, models


_ARM_ROW_DATA_KEY_TO_FIELD = {
    "Previous Ln Num": "previous_ln_num",
    "Manual Adjustment": "manual_adjustment",
    "Audit Flag": "audit_flag",
    "Carry Over Flag": "carry_over_flag",
    "Convertible Flag": "convertible_flag",
    "Current Index": "current_index",
    "Floor Rate": "floor_rate",
    "Frst Chg Period Dec": "frst_chg_period_dec",
    "Frst Chg Period Inc": "frst_chg_period_inc",
    "Frst PIChg Date": "frst_pichg_date",
    "Frst Rate Chg Date": "frst_rate_chg_date",
    "Index": "index",
    "Letter Lead Days": "letter_lead_days",
    "Lookback Period": "lookback_period",
    "Margin": "margin",
    "Life Rate Decrease": "life_rate_decrease",
    "Life Rate Increase": "life_rate_increase",
    "Min Rate Chg": "min_rate_chg",
    "Period Rate Dec": "period_rate_dec",
    "Period Rate Inc": "period_rate_inc",
    "Neg Am Cap Flag": "neg_am_cap_flag",
    "Neg Am Cap": "neg_am_cap",
    "Next PIChg Date": "next_pichg_date",
    "Next Rate Chg Date": "next_rate_chg_date",
    "Original Index": "original_index",
    "Original Int Rate": "original_int_rate",
    "Original PIPmt": "original_pipmt",
    "PIChg Frequency": "pichg_frequency",
    "PIPmt Cap Flag": "pipmt_cap_flag",
    "PIPmt Cap": "pipmt_cap",
    "Rate Calc": "rate_calc",
    "Rate Chg Frequency": "rate_chg_frequency",
    "Rounding": "rounding",
    "Rounding Factor": "rounding_factor",
    "Teaser Rate": "teaser_rate",
    "Tot Carry Over Percent": "tot_carry_over_percent",
    "Investor Margin": "investor_margin",
    "Recast Year": "recast_year",
    "PIPmt Down Cap": "pipmt_down_cap",
}


def _backfill_arm_fields_from_row_data(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    SBDailyArmData = apps.get_model("etl", "SBDailyArmData")

    qs = (
        SBDailyArmData.objects.using(db_alias)
        .exclude(row_data__isnull=True)
        .only("id", "row_data")
    )

    to_update = []
    for row in qs.iterator(chunk_size=500):
        row_data = getattr(row, "row_data", None) or {}
        changed = False

        for key, field_name in _ARM_ROW_DATA_KEY_TO_FIELD.items():
            if hasattr(row, field_name) and getattr(row, field_name) in (None, ""):
                value = row_data.get(key)
                if value not in (None, ""):
                    setattr(row, field_name, value)
                    changed = True

        if changed:
            to_update.append(row)

        if len(to_update) >= 500:
            SBDailyArmData.objects.using(db_alias).bulk_update(
                to_update,
                [
                    *list(_ARM_ROW_DATA_KEY_TO_FIELD.values()),
                ],
                batch_size=500,
            )
            to_update = []

    if to_update:
        SBDailyArmData.objects.using(db_alias).bulk_update(
            to_update,
            [
                *list(_ARM_ROW_DATA_KEY_TO_FIELD.values()),
            ],
            batch_size=500,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0011_add_sbdailyarmdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="previous_ln_num",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="manual_adjustment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="audit_flag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="carry_over_flag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="convertible_flag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="current_index",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="floor_rate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="frst_chg_period_dec",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="frst_chg_period_inc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="frst_pichg_date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="frst_rate_chg_date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="index",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="letter_lead_days",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="lookback_period",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="margin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="life_rate_decrease",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="life_rate_increase",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="min_rate_chg",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="period_rate_dec",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="period_rate_inc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="neg_am_cap_flag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="neg_am_cap",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="next_pichg_date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="next_rate_chg_date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="original_index",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="original_int_rate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="original_pipmt",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="pichg_frequency",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="pipmt_cap_flag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="pipmt_cap",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="rate_calc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="rate_chg_frequency",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="rounding",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="rounding_factor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="teaser_rate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="tot_carry_over_percent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="investor_margin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="recast_year",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbdailyarmdata",
            name="pipmt_down_cap",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(_backfill_arm_fields_from_row_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="sbdailyarmdata",
            name="row_data",
        ),
    ]
