# Generated by Django 5.2 on 2025-12-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0012_expand_sbdailyarmdata_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sbdailybankruptcydata",
            name="file_date",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="sbdailycommentdata",
            name="file_date",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="sbdailypayhistorydata",
            name="file_date",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="sbdailytransactiondata",
            name="file_date",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name="sbdailyloandata",
            constraint=models.UniqueConstraint(
                fields=("date", "loan_number"),
                name="uniq_loan_date_loannum",
                condition=models.Q(date__isnull=False)
                & ~models.Q(date="")
                & models.Q(loan_number__isnull=False)
                & ~models.Q(loan_number=""),
            ),
        ),
        migrations.AddConstraint(
            model_name="sbdailyarmdata",
            constraint=models.UniqueConstraint(
                fields=("file_date", "loan_id"),
                name="uniq_arm_fdate_loanid",
                condition=models.Q(file_date__isnull=False)
                & ~models.Q(file_date="")
                & models.Q(loan_id__isnull=False)
                & ~models.Q(loan_id=""),
            ),
        ),
        migrations.AddConstraint(
            model_name="sbdailyforeclosuredata",
            constraint=models.UniqueConstraint(
                fields=("file_date", "loan_id"),
                name="uniq_fc_fdate_loanid",
                condition=models.Q(file_date__isnull=False)
                & ~models.Q(file_date="")
                & models.Q(loan_id__isnull=False)
                & ~models.Q(loan_id=""),
            ),
        ),
        migrations.AddConstraint(
            model_name="sbdailybankruptcydata",
            constraint=models.UniqueConstraint(
                fields=("file_date", "loan_id", "case_number"),
                name="uniq_bk_fdate_loanid_case",
                condition=models.Q(file_date__isnull=False)
                & ~models.Q(file_date="")
                & models.Q(loan_id__isnull=False)
                & ~models.Q(loan_id="")
                & models.Q(case_number__isnull=False)
                & ~models.Q(case_number=""),
            ),
        ),
        migrations.AddConstraint(
            model_name="sbdailycommentdata",
            constraint=models.UniqueConstraint(
                fields=("file_date", "loan_number", "comment_date", "department"),
                name="uniq_comment_fdate_ln_cdt_dept",
                condition=models.Q(file_date__isnull=False)
                & ~models.Q(file_date="")
                & models.Q(loan_number__isnull=False)
                & ~models.Q(loan_number="")
                & models.Q(comment_date__isnull=False)
                & ~models.Q(comment_date="")
                & models.Q(department__isnull=False)
                & ~models.Q(department=""),
            ),
        ),
        migrations.AddConstraint(
            model_name="sbdailypayhistorydata",
            constraint=models.UniqueConstraint(
                fields=("file_date", "loan_number"),
                name="uniq_payhist_fdate_loannum",
                condition=models.Q(file_date__isnull=False)
                & ~models.Q(file_date="")
                & models.Q(loan_number__isnull=False)
                & ~models.Q(loan_number=""),
            ),
        ),
        migrations.AddConstraint(
            model_name="sbdailytransactiondata",
            constraint=models.UniqueConstraint(
                fields=("file_date", "loan_transaction_id"),
                name="uniq_trans_fdate_txnid",
                condition=models.Q(file_date__isnull=False)
                & ~models.Q(file_date="")
                & models.Q(loan_transaction_id__isnull=False)
                & ~models.Q(loan_transaction_id=""),
            ),
        ),
    ]
