# Generated by Django 5.2.5 on 2025-12-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0013_statebridge_raw_unique_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sbdailycommentdata',
            name='uniq_comment_fdate_ln_cdt_dept',
        ),
        migrations.AddField(
            model_name='sbdailycommentdata',
            name='row_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='sbdailycommentdata',
            constraint=models.UniqueConstraint(condition=models.Q(('file_date__isnull', False), models.Q(('file_date', ''), _negated=True), ('loan_number__isnull', False), models.Q(('loan_number', ''), _negated=True), ('comment_date__isnull', False), models.Q(('comment_date', ''), _negated=True), ('department__isnull', False), models.Q(('department', ''), _negated=True), ('row_hash__isnull', False), models.Q(('row_hash', ''), _negated=True)), fields=('file_date', 'loan_number', 'comment_date', 'department', 'row_hash'), name='uniq_comment_fdate_ln_cdt_dept_hash'),
        ),
    ]
