# Generated by Django 5.2.5 on 2025-12-18 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq_module', '0042_tradelevelassumption_total_discount_and_more'),
        ('etl', '0014_remove_sbdailycommentdata_uniq_comment_fdate_ln_cdt_dept_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_name', models.CharField(help_text='Descriptive name for this mapping (e.g., "ABC Seller - Standard Format")', max_length=255)),
                ('column_mapping', models.JSONField(help_text='JSON mapping of source columns to model fields')),
                ('source_columns', models.JSONField(blank=True, default=list, help_text='List of column names from the source file')),
                ('mapping_method', models.CharField(choices=[('AI', 'AI-Generated'), ('MANUAL', 'Manual'), ('EXACT', 'Exact Match'), ('HYBRID', 'AI + Manual Edits')], default='AI', help_text='How this mapping was created', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Use this mapping as default for this seller')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this mapping is active')),
                ('original_filename', models.CharField(blank=True, help_text='Original file name this mapping was created from', max_length=255, null=True)),
                ('import_stats', models.JSONField(blank=True, default=dict, help_text='Statistics from import (records imported, errors, etc.)')),
                ('notes', models.TextField(blank=True, help_text='User notes about this mapping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this mapping was used for an import', null=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this mapping has been used')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this mapping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mappings', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this mapping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_mappings', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, help_text='Seller this mapping is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_mappings', to='acq_module.seller')),
                ('trade', models.ForeignKey(blank=True, help_text='Trade this mapping was created from (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_mappings', to='acq_module.trade')),
            ],
            options={
                'verbose_name': 'Import Mapping',
                'verbose_name_plural': 'Import Mappings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller'], name='etl_importm_seller__fca4a2_idx'), models.Index(fields=['trade'], name='etl_importm_trade_i_c6e315_idx'), models.Index(fields=['seller', 'is_default', 'is_active'], name='etl_importm_seller__85e96b_idx'), models.Index(fields=['is_active'], name='etl_importm_is_acti_f0c4ee_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('seller', 'is_default'), name='unique_default_per_seller')],
            },
        ),
    ]
