# Generated by Django 5.2.5 on 2026-01-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0015_add_import_mapping_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='EOMTrialBalanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_date', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('loan_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('investor_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('investor_loan_id', models.CharField(blank=True, max_length=50, null=True)),
                ('borrower_name', models.CharField(blank=True, max_length=150, null=True)),
                ('principal_bal', models.CharField(blank=True, max_length=50, null=True)),
                ('escrow_bal', models.CharField(blank=True, max_length=50, null=True)),
                ('other_funds_bal', models.CharField(blank=True, max_length=50, null=True)),
                ('late_charge_bal', models.CharField(blank=True, max_length=50, null=True)),
                ('legal_fee_bal', models.CharField(blank=True, max_length=50, null=True)),
                ('deferred_prin', models.CharField(blank=True, max_length=50, null=True)),
                ('unapplied_bal', models.CharField(blank=True, max_length=50, null=True)),
                ('loss_draft_bal', models.CharField(blank=True, max_length=50, null=True)),
                ('asst_bal', models.CharField(blank=True, max_length=50, null=True)),
                ('nsf_fee_bal', models.CharField(blank=True, max_length=50, null=True)),
                ('oth_fee_bal', models.CharField(blank=True, max_length=50, null=True)),
                ('deferred_int', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_status', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('loan_type', models.CharField(blank=True, max_length=50, null=True)),
                ('legal_status', models.CharField(blank=True, max_length=50, null=True)),
                ('warning_status', models.CharField(blank=True, max_length=50, null=True)),
                ('due_date', models.CharField(blank=True, max_length=20, null=True)),
                ('date_inactive', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'StateBridge EOM Trial Balance Data',
                'verbose_name_plural': 'StateBridge EOM Trial Balance Data',
                'db_table': 'eom_trial_balance_records',
                'indexes': [models.Index(fields=['loan_id'], name='eom_trial_loan_id_idx'), models.Index(fields=['investor_id'], name='eom_trial_investor_id_idx'), models.Index(fields=['file_date'], name='eom_trial_file_date_idx'), models.Index(fields=['primary_status'], name='eom_trial_status_idx'), models.Index(fields=['loan_id', 'file_date'], name='eom_trial_loan_date_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('file_date__isnull', False), models.Q(('file_date', ''), _negated=True), ('loan_id__isnull', False), models.Q(('loan_id', ''), _negated=True)), fields=('file_date', 'loan_id'), name='uniq_eom_trial_fdate_loanid')],
            },
        ),
        migrations.CreateModel(
            name='EOMTrustTrackingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_date', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('loan_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('investor_loan_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('received_date', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('due_date', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('principal_paid_off', models.CharField(blank=True, max_length=50, null=True)),
                ('interest_collected', models.CharField(blank=True, max_length=50, null=True)),
                ('sf_collected', models.CharField(blank=True, max_length=50, null=True)),
                ('net_interest', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('payoff_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'StateBridge EOM Trust Tracking Data',
                'verbose_name_plural': 'StateBridge EOM Trust Tracking Data',
                'db_table': 'eom_trust_tracking_records',
                'indexes': [models.Index(fields=['loan_id'], name='eom_trust_loan_id_idx'), models.Index(fields=['investor_loan_id'], name='eom_trust_investor_loan_id_idx'), models.Index(fields=['received_date'], name='eom_trust_received_date_idx'), models.Index(fields=['due_date'], name='eom_trust_due_date_idx'), models.Index(fields=['loan_id', 'received_date'], name='eom_trust_loan_received_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('file_date__isnull', False), models.Q(('file_date', ''), _negated=True), ('loan_id__isnull', False), models.Q(('loan_id', ''), _negated=True), ('received_date__isnull', False), models.Q(('received_date', ''), _negated=True)), fields=('file_date', 'loan_id', 'received_date'), name='uniq_eom_trust_fdate_loanid_recd')],
            },
        ),
    ]
