# Generated by Django 5.2.5 on 2026-01-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0017_etl_settlement_statement_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradesettlementstatementetl',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='tradesettlementstatementetl',
            name='net_purchase_price',
        ),
        migrations.RemoveField(
            model_name='tradesettlementstatementetl',
            name='total_adjustments',
        ),
        migrations.RemoveField(
            model_name='tradesettlementstatementetl',
            name='total_purchase_price',
        ),
        migrations.RemoveField(
            model_name='tradesettlementstatementetl',
            name='total_upb',
        ),
        migrations.RemoveField(
            model_name='tradesettlementstatementetl',
            name='trade_name',
        ),
    ]
